### ISSUE TITLE
Question: excluding my IP from the polymere api

### ISSUE THREAD

**Issue by Grevard** [googleanalytics/ga-dev-tools#100]
Hello,

We've excluded our IP from the Google Analytics (within GA), and we used the Google Analytics Polymere API for our clients to show them their results. But our IP isn't excluded from those results?  Please tell me how i can exclude there our IP aswell, if possible!

Thanks in advance!

**Comment by philipwalton** [comment]
I'm not sure what you mean when you say "but our IP isn't excluded from those results". The Polymer elements don't send tracking data to Google Analytics, so there's nothing to exclude.

**Comment by Grevard** [comment]
Hmm, weird.. in the Polymere API it shows our visits even when we excluded our ip bij GA filters from the statics. In GA it doesn't show us so how could this be possible?

**Comment by philipwalton** [comment]
What Polymer API are you talking about? If you're talking about the [`<google-analytics>`](https://ga-dev-tools.appspot.com/polymer-elements/) Polymer elements, then those just use the [Core Reporting API](https://developers.google.com/analytics/devguides/reporting/core/) under the hood, the same as the [Query Explorer](https://ga-dev-tools.appspot.com/query-explorer/) and the [Embed API](https://ga-dev-tools.appspot.com/embed-api/). Are you seeing the same problem with those?

**Comment by philipwalton** [comment]
I'm going to close this due to inactivity. Feel free to reopen if you're still having an issue.
