### ISSUE TITLE
Custom Dimension in a Segment is Much More Accurate Than Other Views

### ISSUE THREAD

**Issue by jerbove** [googleanalytics/ga-dev-tools#101]
Using this definition in the segment field returns the accurate results (41,965):
sessions::condition::ga:dimension3==Lender

If I choose this same dimension in the dimensions field, I see a much lower number for Lender (5,598) or any other category.

This is also happening within the Analytics application. Custom reports or dashboards are showing much lower numbers for my custom dimensions. Other dimensions are accurate.

I have samplingLevel set to HIGHER_PRECISION.

This has caused some inaccurate reporting to surface in a meeting with executives :(... so, I would love to see this fixed for the future :)

**Comment by philipwalton** [comment]
@jerbove if you think this is a bug with the Core Reporting API, you should report it on our [issue tracker](https://code.google.com/p/analytics-issues/issues/entry). The issues on this Github repo are specifically for this site's demos and tools, and as far as I can tell, those are working for you. Correct?

**Comment by jerbove** [comment]
Yes... I wasn't sure where to report this... Thanks!
