### ISSUE TITLE
asp.net demo for server side authorisation using analytics api 3 

### ISSUE THREAD

**Issue by mykeblack** [googleanalytics/ga-dev-tools#102]
Hi, could you please add an asp.net demo for using server side authorisation to display analytics data on my website using a service account.  This page https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/ just shows how to parse the key using python, but would be handy to have asp.net version please?

**Comment by philipwalton** [comment]
Sorry, the Demos & Tools site runs on Google AppEngine using the Python SDK. asp.net isn't available, so I can't host a demo of it.

The concepts are the same, though, so you might try taking a look the [Google APIs client library for .NET](https://developers.google.com/api-client-library/dotnet/guide/aaa_oauth).
