### ISSUE TITLE
Send Hit to google Analytics

### ISSUE THREAD

**Issue by ifegade** [googleanalytics/ga-dev-tools#103]
Hi Admin,

I tried using the Hit Builder for google analytics to validate my payloads but anytime I click on "Send hit to google analytics" the system does not give me any feedback and I can't see the reflection on my Dashboard.

Please look into this.

Thanks 

Cheers

**Comment by philipwalton** [comment]
The button icon should turn to a "check" when the hit is successfully sent, and you should be able to see the hit coming in when looking at your [Real-Time dashboard](https://support.google.com/analytics/answer/1638635?hl=en).

You most likely will not be able to see the hits in your regular reports until 24-48 hours after sending them.
