### ISSUE TITLE
Style is not proper on Third Party Visualizations

### ISSUE THREAD

**Issue by sudipta26889** [googleanalytics/ga-dev-tools#104]
I have implemented  Third Party Visualizations. but it not showing the chart properly. have a look at the below screen shot. 
![screenshot from 2015-09-13 09 19 50](https://cloud.githubusercontent.com/assets/5617675/9835145/a4247e3e-59f8-11e5-8c33-a453c3ec7362.png)
Please tell me how do i fix it. It needs to be look like following image
![screenshot from 2015-09-13 09 21 03](https://cloud.githubusercontent.com/assets/5617675/9835148/dec57020-59f8-11e5-9ddc-586427340809.png)

**Comment by philipwalton** [comment]
It looks like you're not including any CSS. If you want it to look like the demos, you can just use the same CSS file, or you can code your own styles.

**Comment by DaMinaup6** [comment]
I have the same problem but don't know which css file should be included.

I included all files under ```/public/css``` and ```/src/css``` but still not work.
