### ISSUE TITLE
How to edit the query response before it gets shown on the Charts

### ISSUE THREAD

**Issue by Signoo** [googleanalytics/ga-dev-tools#108]
I need to edit some of the data from the query (when it comes to % or seconds the query returns only number, I want to make those data readable for my users) is there a method that gets fired when the response is ready but the chart is still waiting for the data? Because I tried inside the on("success") method but it gets after the execute() so the chart is already populated by the data

**Comment by philipwalton** [comment]
There's currently no way to do what you want with the `DataChart` component, but you could always run the query yourself with the `Data` component, update the data however you want, and then create a Google Chart with your new data manually.

I know that's not as easy as you were probably hoping for, but it *is* possible.
