### ISSUE TITLE
Blocked when logging in

### ISSUE THREAD

**Issue by bizinbarefeet** [googleanalytics/ga-dev-tools#1097]
**What page is this happening on**

(https://ga-dev-tools.web.app/account-explorer/)

Refused login with google developer account

**Describe the bug**
Am following your instructions: https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/web-js
The app refused to accept a login from a Google developer account authorized for 

**To Reproduce**
1. Go to '...' page about
2. Click on '....' login
3. Scroll down to '....'  receive error page about blocked
![blocked](https://user-images.githubusercontent.com/17591598/212542012-f9c9c265-9ce8-4083-b4bd-ead41c6639cc.jpg)

**Expected behavior**
Log in and be able to access View ID as describedd in your startup instructions

**Screenshots**
SEE ATTACHED

**Desktop (please complete the following information):**

 - 
 WIN11 - 22621.1105
 Chrome - Version 108.0.5359.126 (Official Build) (64-bit)

**Comment by BZ-Andy** [comment]
Same as above post. Error after login.
https://ga-dev-tools.web.app/

**"This app is blocked".**

Microsoft Edge
Version 108.0.1462.76 (Official build) (64-bit)

**Comment by sergeypolevich** [comment]
The same. Safari macosx, safari ios 16.1.1

**Comment by onyxcode** [comment]
Same as OP
-----
Chrome OS
108.0.5359.172 (Official Build) (64-bit)
