### ISSUE TITLE
embed api demos don't work

### ISSUE THREAD

**Issue by tomaszbrudzinski** [googleanalytics/ga-dev-tools#110]
Hi, I just want to report that the demos of Embed API available here: https://ga-dev-tools.appspot.com/embed-api/ don't work. There are some JS errors, and only thing I see is "waiting for authorization"...

![zrzut ekranu 2015-09-28 o 16 49 00](https://cloud.githubusercontent.com/assets/8254931/10138910/de4b5628-6600-11e5-8e46-996c4ad868e5.png)

**Comment by philipwalton** [comment]
The errors you see in the console are a known issue, but they don't affect the loading of the page. They result from the initial auth attempt that fails (since you're not yet logged in).

To use the page you have to click the big orange banner that reads: **Click here to authorize →**
