### ISSUE TITLE
Cannot login because of google blocking login to this app

### ISSUE THREAD

**Issue by OleksandrAndrieianov** [googleanalytics/ga-dev-tools#1107]
**What page is this happening on**
https://ga-dev-tools.web.app/ga4/query-explorer/

**Describe the bug**
When I'm trying to login, google accounts returns me an error: 

_This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access._

I've tried to login from 3 separate accounts, 2 browsers (chrome/safari), 2 notebooks and always gets the same response.

**To Reproduce**
1. Go to https://ga-dev-tools.web.app/ga4/query-explorer/
2. Click on LOGIN
3. Choose your account

**Expected behavior**
successful login

**Screenshots**
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/118672377/213534559-e95f8260-3a0e-4d59-8f0e-0e2ba94af6e8.png">

**Desktop (please complete the following information):**
 - OS: [MacOS 13.1 (22C65) / Windows 10]
 - Browser [chrome, safari]
 - Version [Chrome - 108.0.5359.124 / Safari - 16.2 (18614.3.7.1.5)]

**Comment by fridahelenejoh** [comment]
can i get help to solve this problem?

**Comment by OleksandrAndrieianov** [comment]
> can i get help to solve this problem?

Excuse me, you want to help me, or you have same issue and also waiting for solution? :)
