### ISSUE TITLE
Can't log in with Google account

### ISSUE THREAD

**Issue by litalert** [googleanalytics/ga-dev-tools#1109]
**What page is this happening on**
[Copy the URL of the page this issue is happening on. ](https://ga-dev-tools.web.app/ga4/dimensions-metrics-explorer/)

**Describe the bug**
When clicking log in, it prompted to use Google Account to log in. Once picked the account, I got an error message that says "this app is blocked"

**To Reproduce**
1. Go to 'https://ga-dev-tools.web.app/ga4/dimensions-metrics-explorer/'
2. Click on 'Log In'
3. Pick an account

**Comment by davidjkeller** [comment]
I get the same issue 
![image](https://user-images.githubusercontent.com/16836400/214259477-4240308e-d031-4ffa-b496-5f2f0847f5f8.png)

**Comment by hajime-goshima** [comment]
I get the same issue

**Comment by qubitinua** [comment]
Same problem

**Comment by martinix06** [comment]
I heva same issue. App password not work fo app: `ga-dev-tools.web.app` or `https://ga-dev-tools.web.app`

**Comment by julesgilson** [comment]
Me too - Google actually link to the Dimensions Metrics Explorer from their API docs....

**Comment by erlancarreira** [comment]
Same problem here
