### ISSUE TITLE
Google won't let me login

### ISSUE THREAD

**Issue by donohoe** [googleanalytics/ga-dev-tools#1122]
I am directed to this service from this page:
https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/service-php

I was trying to get the View ID. I am using Google Chrome as my browser. I am logged in to my Google account but I get this message:

"Login status could not be determined. Please ensure cookies are enabled."

I open Safari and go to the same page. I am prompted to login. I do this, but after providing my user/pass I get this message:

"This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access."

**Comment by chrisjimallen** [comment]
A lot of similar issues being raised on here, and no response from the project owner. I’d say at this point the tool is dead.

**Comment by blackarcanis** [comment]
Yes, what is going on here? 
How can we test that properly while Google is forcing the move to GA4 for this summer?

**Comment by TheRealVincentVanGogh** [comment]
Yeah, Google's handling of GA4 documentation and their transitioning from UA4 and 360 hasn't been the smoothest...

I managed to get a workaround working here: #1131 but it's only useful if you have access to Google Admin.

Good Luck!

**Comment by chrisjimallen** [comment]
Thank you @ikuleshov! Much appreciated.
