### ISSUE TITLE
Google blocks login

### ISSUE THREAD

**Issue by TheRealFaruhaan** [googleanalytics/ga-dev-tools#1126]
**What page is this happening on**
https://ga-dev-tools.web.app/query-explorer/

**Describe the bug**
When prompted to login using google, after an account has been selected, google blocks the login. Page says this app has been blocked. "This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access."

**To Reproduce**
1. Go to 'https://ga-dev-tools.web.app/query-explorer/'
2. Click on 'Login'
3. Click on the account/sign in to account

**Expected behavior**
Fully log into the website using google.

**Screenshots**
![image](https://user-images.githubusercontent.com/26362259/215303200-3dc76ad2-b9d4-44e0-9ece-5b91c2a967fb.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version Live

**Comment by frelena13** [comment]
same problem here :(
