### ISSUE TITLE
Cannot login to GA4 Event Builder due to blocked access (sensitive info)

### ISSUE THREAD

**Issue by uangst** [googleanalytics/ga-dev-tools#1127]
**What page is this happening on**
https://ga-dev-tools.web.app/ga4/event-builder/

**Describe the bug**
On that page I am asked to login with my Google Account. However when I try I won't get access. I get an alert window back with the message: "This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access."

**To Reproduce**
1. Go to https://ga-dev-tools.web.app/ga4/event-builder/
2. Click on the Login Button
3. Enter your Google Account login details
4. See error/alert message "This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access."

**Expected behavior**
I would like to get logged into this application (the GA4 Event Builder) in order to prepare a query to be sent to my Analytics account.
![event-builder-login-error](https://user-images.githubusercontent.com/77646556/215316902-2f045b29-f897-4589-8ec5-33ac97eaeff2.jpg)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac Ventura 13.1
 - Browser Chrome 
 - Version 109.0.5414.119 (Official Build) (x86_64)

**Comment by TheRealVincentVanGogh** [comment]
Hey, just posted a workaround here: #1131
