### ISSUE TITLE
Google Query Explorer dropdown 

### ISSUE THREAD

**Issue by uanaen** [googleanalytics/ga-dev-tools#113]
Hi Recently I am not able to view dimensions and matrix in the dropdown view when I query for new API. Would you be able to check if there is an issue?

**Comment by philipwalton** [comment]
I have not heard any complaints about this issue, and have not been able to reproduce it myself. Can you please give me more details, or attach screenshots?

**Comment by philipwalton** [comment]
I'm going to close this due to inactivity. Feel free to submit another issue if you're still seeing the problem.
