### ISSUE TITLE
GA event builder - This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

### ISSUE THREAD

**Issue by Vinestou** [googleanalytics/ga-dev-tools#1131]
**What page is this happening on**
https://ga-dev-tools.web.app/ga4/event-builder/

**Describe the bug**
When I try to login I get the message:
```
This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.
```

**To Reproduce**
1. Go to 'https://ga-dev-tools.web.app/ga4/event-builder/'
2. Click on 'LOGIN'
3. Pop up window opens
4. Select account to continue
5. See error

**Expected behavior**
I Expect to get a Login confirmation or the popup closing and getting me in to the Event builder. OR a solution for the problem why I cant login.

**Screenshots**
![event builder login](https://user-images.githubusercontent.com/52471580/215493776-9b8e3660-53b1-4cd0-ad8e-414787067fe1.JPG)

**Desktop (please complete the following information):**
 - OS: W10
 - Browser: Chrome
 - Version: 109.0.5414.120 (Officiële build) (64-bits)

**Comment by Luxato** [comment]
@diminishedprime Can someone please fix this? Universal analytics is turning of by July 1st, and basic tools for building GA4 are not working :(

**Comment by denysgul** [comment]
the same problem:(

**Comment by claireebilski** [comment]
same :(

**Comment by frelena13** [comment]
same :(

**Comment by frelena13** [comment]
same :(

**Comment by jbaum02s** [comment]
Same issue, I am unable to login to GA Dev tools at all. I get an error that 'This app is blocked'.

**Comment by TheRealVincentVanGogh** [comment]
Hey everyone, I had the same problem and managed to create a workaround if you have access to Google Admin Workspace.

Client ID for me and probably you too: `793177639245-olst43lspv93vkoql0b9l26hmpf9kfmv.apps.googleusercontent.com`
^ You'll see why you need this soon

1. Head to the OAuth signin page for the GA4 demos + tools you're using.

![Screenshot 2023-02-01 115633](https://user-images.githubusercontent.com/19521118/216149929-1c9f345a-6f21-49d0-956b-5bf681242326.png)

2. Extract the `client_id` from the URL of the OAuth login portal. (Hint: you'll find a URL parameter called client_id=XXXXXXXX)

![image](https://user-images.githubusercontent.com/19521118/216149583-14d6dfea-e1f5-4567-a61e-2b40e6ce4e24.png)
3. Search for "API Controls" in Google Admin
![image](https://user-images.githubusercontent.com/19521118/216150037-dbf1d0ab-b062-4836-9de0-e376b1081b0d.png)

4. Hit "Manage Third-Party App Access"
5. Hit "Add app"
6. Hit "Oauth App Name or Client ID"
7. Paste in the Client ID you found from Step 2
![image](https://user-images.githubusercontent.com/19521118/216150146-8b249586-fb51-4f9b-a843-05a8d9877d13.png)

8. Hit "Google Analytics Demos & Tools"
9. Allow full access
10. Profit

For me the Client ID was `793177639245-olst43lspv93vkoql0b9l26hmpf9kfmv.apps.googleusercontent.com` but I'm not sure if that's the same for everyone hence leaving my client ID discovery steps in.

**Comment by YasmineCogniteev** [comment]
Hello the modification was done but I have since this morning another type of error "Login status could not be determined. Please ensure cookies are enables." I cleaned all cookies nothing happened
<img width="993" alt="Capture d’écran 2023-02-02 à 10 23 01" src="https://user-images.githubusercontent.com/109794564/216283946-cb2e2da3-4c56-4fd7-8189-6ee2495d4329.png">
