### ISSUE TITLE
Login status could not be determined

### ISSUE THREAD

**Issue by sweetsummerschild** [googleanalytics/ga-dev-tools#1138]
**What page is this happening on**
https://ga-dev-tools.web.app/query-explorer/

**Describe the bug**
Login status could not be determined when cookies are already enabled. Cannot use the query explorer.

**To Reproduce**
1. Go to https://ga-dev-tools.web.app/query-explorer/
2. Shows message: "Login status could not be determined. Please ensure cookies are enabled."

**Expected behavior**
The functional  Query Explorer

**Screenshots**
<img width="1135" alt="Screenshot 2023-02-02 at 16 16 32" src="https://user-images.githubusercontent.com/91051334/216284675-556ace35-cb7f-4f49-abe0-1d0313f590e8.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 109.0.5414.119

**Additional context**
Cookies are enabled:
<img width="783" alt="Screenshot 2023-02-02 at 16 24 37" src="https://user-images.githubusercontent.com/91051334/216284619-9386cd78-ab51-425d-9bfd-e86005b7f355.png">

**Comment by nerodante** [comment]
same problem

**Comment by uvwlab** [comment]
same problem

**Comment by YasmineCogniteev** [comment]
same problem

**Comment by ktanoooo** [comment]
same problem

**Comment by paskevich** [comment]
same problem

**Comment by nerodante** [comment]
Console Error ：

{
    "error": "idpiframe_initialization_failed",
    "details": "Not a valid origin for the client: https://ga-dev-tools.web.app has not been registered for client ID 793177639245-olst43lspv93vkoql0b9l26hmpf9kfmv.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and register this origin for your project's client ID."
}
