### ISSUE TITLE
Login status could not be determined. Please ensure cookies are enabled.

### ISSUE THREAD

**Issue by sixwillows** [googleanalytics/ga-dev-tools#1139]
**What page is this happening on**
https://ga-dev-tools.web.app/ga4/dimensions-metrics-explorer/

**Describe the bug**
It keeps showing "Login status could not be determined. Please ensure cookies are enabled."

**To Reproduce**
1. Go to 'https://ga-dev-tools.web.app/ga4/dimensions-metrics-explorer/'
2. Click on 'GA4'

**Expected behavior**
Using the explorer successfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 109.0.5414.120

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 
 - OS: Android 13
 - Browser: Chrome

**Comment by mmundyCLI** [comment]
Also happening for me in Windows 10 Pro using Firefox 109.0.1 (64-bit)

![ga4_queryexplorer](https://user-images.githubusercontent.com/28933039/216398429-d5725198-e9c0-4aaf-b70b-1094f67731fa.png)
