### ISSUE TITLE
Problem when using the date-range component

### ISSUE THREAD

**Issue by Signoo** [googleanalytics/ga-dev-tools#114]
I'm using the date-range component used also on the following example:
https://ga-dev-tools.appspot.com/embed-api/custom-components/

And I found an annoying behaviour that I was wondering if you could possibly fix. When I input the day from the keyboard if it's over 9 (so it's formed by 2 numbers) it doesn't input correctly, both the numbers gets written in the unit part of the number. For example:

If I write 28 the input day does this:

I write 2 the input shows 02
I write 8 the input shows 08

I found that If I write 2-2-8 then the bug doesn't show up and the day gets written correctly.
Is this an intentional behaviour or not?

**Comment by philipwalton** [comment]
This component uses the native `<input type=date>` form control that ships with the browser, so there's really nothing I can do about its behavior.

If you think the behavior should be different, you can file a bug with the maker of whatever browser you're using.

**Comment by Signoo** [comment]
@philipwalton I already tried with the native <input type=date> but the behaviour isn't the same, the date on the native one gets written correctly while on the date-range-selector provided by the api the behaviour is different

**Comment by philipwalton** [comment]
The `DateRangeSelector` component does use native `<input type=date>` controls. You can see be looking at [the source](https://github.com/googleanalytics/ga-dev-tools/blob/master/src/javascript/embed-api/components/date-range-selector.js#L132-L141).
