### ISSUE TITLE
 Login status could not be determined. Please ensure cookies are enabled.

### ISSUE THREAD

**Issue by arnold-overby-SIM** [googleanalytics/ga-dev-tools#1149]
**What page is this happening on**
https://ga-dev-tools.web.app/query-explorer/

**Describe the bug**
Error Message: Login status could not be determined. Please ensure cookies are enabled.

**To Reproduce**
1. Go to https://ga-dev-tools.web.app/query-explorer/
2. Make sure cookies are enabled.
3. Page still has the error message.

**Expected behavior**
The page should work as it normally does

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 109.0.5414.120

**Comment by dan2408** [comment]
Same issue for me and my coworker! Yesterday it worked as expected. Browser or Cookie-Settings don't change the fact of the site not working as expected.
