### ISSUE TITLE
Data inccorect

### ISSUE THREAD

**Issue by paulpatrick** [googleanalytics/ga-dev-tools#115]
If I have ga:pageviews returned by month, I get one value. If select ga:pageviews and ga:sessions then pageviews number is different which doesn't make any sense

**Comment by philipwalton** [comment]
I can't reproduce this issue, can you provide more details or double check your query?

**Comment by paulpatrick** [comment]
Will send later tonight with screenshots from google query explorer showing the different data.

**Comment by philipwalton** [comment]
I'm going to close this due to lack of activity. Please feel free to reopen if you think it's still an issue.
