### ISSUE TITLE
Cant see Query explorer

### ISSUE THREAD

**Issue by GibinJacob** [googleanalytics/ga-dev-tools#1150]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 
https://ga-dev-tools.web.app/ga4/query-explorer/
**Describe the bug**
Login status could not be determined. Please ensure cookies are enabled.
**To Reproduce**

**Expected behavior**
There is no login button, or any means to relogin.

**Screenshots**
![image](https://user-images.githubusercontent.com/6566892/216376658-9e32a76f-a31d-4956-8142-a99ccc9b96a9.png)

**Desktop (please complete the following information):**
Windows 11 /Chrome Version 109.0.5414.120 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
Tried everything possible and enabled all cookies still I cant get to see the query builder

**Comment by PeterVermeulen** [comment]
![Screenshot 2023-02-03 091708](https://user-images.githubusercontent.com/6651230/216547885-a6718582-7de7-4be1-95b9-bb71f23e75ad.jpg)

Looks like something needs to be updated.

**Comment by GibinJacob** [comment]
The site is working today.
