### ISSUE TITLE
Login status could not be determined. Please ensure cookies are enabled.

### ISSUE THREAD

**Issue by olegrasskazovpro** [googleanalytics/ga-dev-tools#1151]
**What page is this happening on**
[https://ga-dev-tools.web.app/ga4/query-explorer/](https://ga-dev-tools.web.app/ga4/query-explorer/)

**Describe the bug**
> Login status could not be determined. Please ensure cookies are enabled.

**To Reproduce**
1. Go to [https://ga-dev-tools.web.app/ga4/query-explorer/](https://ga-dev-tools.web.app/ga4/query-explorer/)
2. See error

**Expected behavior**
My cookies are enabled  and normal interface should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/40406005/216383442-ed017d58-0cb0-4a48-a0a5-90fd1d851709.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.2
 - Browser chrome
 - Version 109.0.5414.87 (Official Build) (arm64)

**Comment by stangwm** [comment]
Same thing happening here -- across all my devices and browsers.
