### ISSUE TITLE
SSL Certificate error - ERR_BAD_SSL_CLIENT_AUTH_CERT

### ISSUE THREAD

**Issue by dougsymes** [googleanalytics/ga-dev-tools#116]
One of our computers gets: "Certificate-based authentication failed" whenever it goes to https://ga-dev-tools.appspot.com 

Complete text:  

     This server requires a certificate for authentication, and didn't accept the one sent by the browser.      Your certificate may have expired, or the server may not trust its issuer. You can try again with a different certificate, if you have one, or you may have to obtain a valid certificate from elsewhere.

     Your connection to ga-dev-tools.appspot.com is not encrypted.

We are baffled by this issue.  We have reinstalled the certificates from your cert chain...to no avail.

Has this issue been reported by some users and resolved?

**Comment by philipwalton** [comment]
You're going to have to be more specific. What browser are you using when getting this error?

**Comment by dougsymes** [comment]
Same error using Firefox, Chrome and IE10.  Its limited to this one
Windows7 computer.
This same user logging into another computer - does not get this error.
Other users logging into this same computer - get this same error.

We've tried deleting the certs (each in chain) and importing them from
another computer....same result.

________________________________
*Doug Symes*
*Manager, **Technology Services*
o) 682-730-2022
c) 817-269-2145
www.qualbe.com

**Comment by philipwalton** [comment]
Okay, well then that sounds like it has nothing to do with the Demos & Tools site, and is a problem with that specific computer. I don't think there's anything I can do on my end to help.

**Comment by dougsymes** [comment]
Its the computer trying to read the SSL cert.

we're going to wipe the computer...very weird though.  thanks anyway.

________________________________
*Doug Symes*
*Manager, **Technology Services*
o) 682-730-2022
c) 817-269-2145
www.qualbe.com
