### ISSUE TITLE
Login status could not be determined. Please ensure cookies are enabled.

### ISSUE THREAD

**Issue by RottenJoe** [googleanalytics/ga-dev-tools#1160]
**What page is this happening on**
https://ga-dev-tools.web.app/query-explorer/

**Describe the bug**
_Login status could not be determined. Please ensure cookies are enabled._
Cookies are enabled and I am recognized on all other Google tools (e.g. GA, GTM, Drive etc.)

**To Reproduce**
1. Try to use Query Explorer

**Expected behavior**
I'm detected as logged in and can use Query Explorer

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser: Chrome
 - Version: Version 109.0.5414.119 (Official Build) (arm64)

**Additional context**
![Screenshot 2023-02-03 at 09 30 51](https://user-images.githubusercontent.com/25005673/216550812-9f1cd6b9-2dbd-49fb-9cd0-ee7d9b1dee7e.png)

**Comment by GeorgeManukyan** [comment]
Same here  
Windows, Chrome is up to date
Version 109.0.5414.120 (Official Build) (64-bit)

Same in OS X and Safari Version 16.1 (17614.2.9.1.13, 17614)

**Comment by KaraMichael** [comment]
Same issue with the Hit Builder:
https://ga-dev-tools.web.app/hit-builder/

OS: MacOS Ventura 13.2
Browser: Chrome
Version: Version 109.0.5414.119 (Official Build) (x86_64)

**Comment by ruttan2** [comment]
Same problem

**Comment by Nodesktophero** [comment]
same problem

**Comment by jimses** [comment]
same problem.

**Comment by julienbou** [comment]
same problem

**Comment by UncleJey** [comment]
same

**Comment by UncleJey** [comment]
@ikuleshov  do you hear us?

**Comment by UncleJey** [comment]
@philipwalton  @tiembo @diminishedprime  @Lucretiel 
all gone

**Comment by SWannell** [comment]
Same problem as everyone else! Sounds very wide-spread judging by the volume of issues being raised on it!
