### ISSUE TITLE
Event Builder Login status could not be determined. Please ensure cookies are enabled.

### ISSUE THREAD

**Issue by DmytroKandala** [googleanalytics/ga-dev-tools#1163]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DmytroKandala** [comment]
Windows 10, Crome

**Comment by eddychilakiller** [comment]
same error
<img width="1768" alt="Captura de Pantalla 2023-02-03 a la(s) 11 14 40" src="https://user-images.githubusercontent.com/12708239/216665812-133def80-a5bc-4817-ae4c-f655d0cf47f3.png">

MacOS Monterey
Chrome 109.0.5414.119
