### ISSUE TITLE
Login status could not be determined

### ISSUE THREAD

**Issue by arjanpan01** [googleanalytics/ga-dev-tools#1169]
**What page is this happening on**
https://ga-dev-tools.web.app/ga4/event-builder/
https://ga-dev-tools.web.app/ga4/dimensions-metrics-explorer/
https://ga-dev-tools.web.app/ga4/query-explorer/

**Describe the bug**
When go onto website, the message "Login status could not be determined. Please ensure cookies are enabled." appears before logging in. Can't use tools on the web pages. 
I've tried to delete the cache, use a different browser (incognito and firefox), and deleting the cookies. Even tried using a different device linked to a different google account and saw the same message.
When I inspect the console I see the error:
Not a valid origin for the client: https://ga-dev-tools.web.app has not been registered for client ID {client id}. Please go to https://console.developers.google.com/ and register this origin for your project's client ID.
I tried creating credentials of oauth, and change the client id but without success.

**To Reproduce**
1. Go to '(https://ga-dev-tools.web.app/ga4/event-builder/)'
2. See error message

**Expected behavior**
The message "Login status could not be determined. Please ensure cookies are enabled." should appear and an error "error": "idpiframe_initialization_failed" in the console

**Screenshots**
![image](https://user-images.githubusercontent.com/56485905/216770307-97ee8946-c82d-4b29-83b0-335b600698b1.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 109.0.5414.120

**Smartphone (please complete the following information):**

**Additional context**

**Comment by juan-carvajal** [comment]
Same here

**Comment by owboateng** [comment]
Getting the same issue too.

**Comment by UncleJey** [comment]
same issue
