### ISSUE TITLE
When trying to use the Google Analytics Query Explorer Started getting the error since yesterday "Login status could not be determined. Please ensure cookies are enabled."

### ISSUE THREAD

**Issue by biconsultanttvt** [googleanalytics/ga-dev-tools#1170]
**What page is this happening on**
[GA Query Explorer ](https://ga-dev-tools.web.app/query-explorer/)

**Describe the bug**
When trying to use the Google Analytics Query Explorer Started getting the below error since yesterday 
"Login status could not be determined. Please ensure cookies are enabled."

**Screenshots**
![image](https://user-images.githubusercontent.com/124481680/216801274-e1251c8b-4abb-4c92-8ab4-5c578f243234.png)

**Desktop (please complete the following information):**
 - Browser [chrome,edge]

**Comment by biconsultanttvt** [comment]
Its a duplicate issue that many have already reported.

**Comment by UncleJey** [comment]
same problem

**Comment by ktanoooo** [comment]
@sanbeiji @philipwalton @pfrisella 
Do you have a solution to this problem?
