### ISSUE TITLE
Hit Builder - Login status could not be determined. Please ensure cookies are enabled.

### ISSUE THREAD

**Issue by OnlionSander** [googleanalytics/ga-dev-tools#1180]
**What page is this happening on**
[Copy the URL of the page this issue is happening on. ](https://ga-dev-tools.web.app/hit-builder/)

**Describe the bug**
I want to remove a transaction in Analytics, so I found this URL on the internet (https://www.optimizesmart.com/how-to-remove-modify-google-analytics-ecommerce-transaction-in-one-click/).
I can't reach the hit builder. Have already looked in cookies and also deleted everything there and tried again. Nothing works. Who can help?

**To Reproduce**
1. Go to '[...](https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#ecom)'
2. Click on 'Measurement Protocol Hit Builder'

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by UncleJey** [comment]
dublicate

**Comment by OnlionSander** [comment]
@UncleJey , link to the thread? Thank you!

**Comment by UncleJey** [comment]
20 last messages
https://github.com/googleanalytics/ga-dev-tools/issues
