### ISSUE TITLE
Query Explorer is not working - Login Issue

### ISSUE THREAD

**Issue by vijayaganesh-s** [googleanalytics/ga-dev-tools#1181]
**Query Explorer is not working - Login Issue**
https://ga-dev-tools.web.app/query-explorer/

**Bug Description**
I am using this tool to get the Google Analytics queries for my desired dimensions and metrics since 20 months, when I tried to generate a similar kind of query using the **Query Explorer**, it is showing me a error message _**Login status could not be determined. Please ensure cookies are enabled.**_, So, I have cleared the browser cache, cookies and other data and logged into my google account and then tried to access the Query Explorer, even after doing this I got the same issue/error message, could someone please help me on this?

**To Reproduce**
1. Go to https://ga-dev-tools.web.app/query-explorer/
2. See error

**Expected behavior**
When entering into this url https://ga-dev-tools.web.app/query-explorer/, it allows us to select the GA account and then dimensions and metrics, then by clicking the run query will generate a Query along with sample data set.

**Screenshots**
![image](https://user-images.githubusercontent.com/25371808/216965134-250196b0-e643-4c63-80f5-bb82eb43ccad.png)

**Desktop:**
 - Chrome
 - Version 109.0.5414.120

**Comment by UncleJey** [comment]
dublicate

**Comment by Anamont23** [comment]
+1

**Comment by pcourt-asmtech** [comment]
+1

**Comment by vijayaganesh-s** [comment]
Thank you so much for the resolution :)
