### ISSUE TITLE
Builder not working

### ISSUE THREAD

**Issue by SergeyLysenko** [googleanalytics/ga-dev-tools#1182]
**What page is this happening on**
[Copy the URL of the page this issue is happening on. ](https://ga-dev-tools.web.app/hit-builder/)

**Describe the bug**
Hit builder not working. Gives an error: "Login status could not be determined. Please ensure cookies are enabled."  https://prnt.sc/fyWGS-S0R0Un

**To Reproduce**
1. Go to ['...'](https://ga-dev-tools.web.app/hit-builder/)
2. See error

**Expected behavior**
Builder not working

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://prnt.sc/fyWGS-S0R0Un)

**Desktop (please complete the following information):**
 - OS: Ios
 - Browser Chrome
 - Version 109.0.5414.87

**Comment by UncleJey** [comment]
dublicate last 30 messages
