### ISSUE TITLE
GA4 Query Explorer: Login status could not be determined

### ISSUE THREAD

**Issue by michp** [googleanalytics/ga-dev-tools#1183]
**What page is this happening on**
(https://ga-dev-tools.web.app/ga4/query-explorer/)

**Describe the bug**
Go to https://ga-dev-tools.web.app/ga4/query-explorer/ the page no longer logs in to enable me to use the UI to explore dimensions and results of GA analytics.  The issue started for me on Thursday EST.

**To Reproduce**
1. Go to https://ga-dev-tools.web.app/ga4/query-explorer/ using a logged in Chrome window
2. You will receive the error "Login status could not be determined. Please ensure cookies are enabled."
I have verified that cookies are enabled and I am logged in.  
3. View developer tools on this page and you will see the error:
onInitialClientRender.js:57 
Object
details
: 
"Not a valid origin for the client: https://ga-dev-tools.web.app has not been registered for client ID 793177639245-olst43lspv93vkoql0b9l26hmpf9kfmv.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and register this origin for your project's client ID."
error
: 
"idpiframe_initialization_failed"
[[Prototype]]
: 
Object

**Expected behavior**
I expected the page to login and show me my Google Analytic Account and properties so I could run test out the new GA4 analytics.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version:09.0.5414.119 (Official Build) (x86_64)

**Comment by timsco** [comment]
I'm seeing the same issue on Safari, Chrome, Firefox, Firefox Developer Edition and Chrome Canary.
