### ISSUE TITLE
AttributeError: 'SignedJwtAssertionCredentials' object has no attribute 'get_access_token'

### ISSUE THREAD

**Issue by mnaglee** [googleanalytics/ga-dev-tools#119]
I attempted to use the instructions on this page: https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/

Attempting to get/refresh an access token using the code supplied fails with the following error:

```python
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "//scripts/service-account.py", line 24, in get_access_token
    return _credentials.get_access_token().access_token
AttributeError: 'SignedJwtAssertionCredentials' object has no attribute 'get_access_token'
```

Info on that object class: http://google-api-python-client.googlecode.com/hg-history/59a3057af225884cd9b483e9d166aefbb92b401c/docs/epy/oauth2client.client.SignedJwtAssertionCredentials-class.html

Looking forward to the update on the docs, as I've been digging for a while and haven't found a good way to get an access token via python/django. :)

**Comment by philipwalton** [comment]
That documentation appears to be wrong. The `OAuth2Credentials` object has a `get_access_token` method, and `SignedJwtAssertionCredentials` inherits from `OAuth2Credentials`.

You can find the method in `oauth2client/client.py` on line 673.

**Comment by mnaglee** [comment]
Ah, I'm running an old version of oauth2client.  I think that's the problem.  Thanks!
