### ISSUE TITLE
DATA WRONG?

### ISSUE THREAD

**Issue by paulpatrick** [googleanalytics/ga-dev-tools#120]
Query explorer returns different data for a given month depending on what my start date and end date are which doesn't make sense:  look at 201509 row and pageviews  - one shows 27949 but other results shows something else? How do i know what is right?

![ga_qe_view1](https://cloud.githubusercontent.com/assets/242407/10676317/f92c7274-78ca-11e5-9451-2054e84f0bda.PNG)
![ga_qe_view2](https://cloud.githubusercontent.com/assets/242407/10676319/fbc9afec-78ca-11e5-8279-f67288743661.PNG)

**Comment by philipwalton** [comment]
Your first screenshot shows that it contains sampled data; that should explain the difference.
