### ISSUE TITLE
The demos are not working

### ISSUE THREAD

**Issue by inavz** [googleanalytics/ga-dev-tools#121]
The demo's on this link is not working https://ga-dev-tools.appspot.com/embed-api/. It is stuck on 'Waiting for authorization' I can also see few errors on the Console.'Uncaught [object Object]'

**Comment by gmcoh** [comment]
Have you clicked the orange banner at the top that says "Click here to
authorize"?

**Comment by inavz** [comment]
Awesome it works for me now. I had to disable all the Chrome extensions. Cheers!
