### ISSUE TITLE
Login status could not be determined. Please ensure cookies are enabled.

### ISSUE THREAD

**Issue by nmarconato** [googleanalytics/ga-dev-tools#1210]
**What page is this happening on**
https://ga-dev-tools.web.app/query-explorer/

**Describe the bug**
Can't run the queries. I get the message: Login status could not be determined. Please ensure cookies are enabled.

**To Reproduce**
1. Go to https://ga-dev-tools.web.app/query-explorer/

**Expected behavior**
The metrics and dimensions available are not being shown.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome - Version 109.0.5414.120 (Versão oficial) 64 bits

**Comment by lamhizz** [comment]
Same for me, only Mac, iOS 12.3

**Comment by martinix06** [comment]
Same issue

**Comment by APBatten** [comment]
same

**Comment by Shkvo** [comment]
Same issue.
