### ISSUE TITLE
Login status could not be determined. Please ensure cookies are enabled.

### ISSUE THREAD

**Issue by sandinof** [googleanalytics/ga-dev-tools#1217]
I cannot access the query explorer for https://ga-dev-tools.web.app/ga4

When going to https://ga-dev-tools.web.app/ga4/query-explorer/ I recive '_Login status could not be determined. Please ensure cookies are enabled_.'

**To Reproduce**
1. Go to '[..](https://ga-dev-tools.web.app/ga4/query-explorer/).'
2. See error

**Expected behavior**
A few days ago I was able to see all the accounts

![image](https://user-images.githubusercontent.com/7718947/217353054-4a4b6440-8037-4b7c-8ebe-399052b368b2.png)

 - OS: [Windows 11]
 - Browser [chrome, edge]
 - Version [110.0.5481.78, 109.0.5414.120]

**Comment by Shkvo** [comment]
I faced with the same issue.
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/20351394/217355676-b99d5b0b-1285-40bf-b3c8-6897ee89b76c.png">
