### ISSUE TITLE
Login not recognized GA Query Tool

### ISSUE THREAD

**Issue by magnusrubin** [googleanalytics/ga-dev-tools#1219]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 
https://ga-dev-tools.web.app/ga4/query-explorer/

**Describe the bug**
Verified I am logged into Google Analytics on same browser and cookies are not blocked, but the Query Explorer page is not recognizing the login.  Receive notice "Login status could not be determined. Please ensure cookies are enabled."

**To Reproduce**
1. Go to https://ga-dev-tools.web.app/ga4/query-explorer/
2. Receive notice so unable to use the tool

**Expected behavior**
Login worked perfectly 2 weeks ago using exact same steps, but no longer is, and cannot determine why

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 12.6
 - Browser Chrome 
 - Version 110.0.5481.77 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MCristofalo** [comment]
Hey Magnus! 
Having the same problem on my end. Noticed the console is throwing what looks like a possible permissions issue?
![image](https://user-images.githubusercontent.com/81421302/217402265-eeb70885-7c5e-4503-8fc8-602f5357545b.png)
