### ISSUE TITLE
Google Analytics embed Api

### ISSUE THREAD

**Issue by RobinHossain** [googleanalytics/ga-dev-tools#123]
How to get geo language data like google analytics full report view.

thanks

**Comment by mcohoon** [comment]
The complete list of dimensions and metrics can be found in the [documentation](https://developers.google.com/analytics/devguides/reporting/core/dimsmets)
The exact dimension you are looking for is probably [ga:language](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=system&jump=ga_language)

Please only report issues with the ga-dev-tools repository here. You can always ask technical questions on stackoverflow with the [google-analytics tag](http://stackoverflow.com/questions/tagged/google-analytics) or the [google-analytics-api tag](http://stackoverflow.com/questions/tagged/google-analytics-api).

**Comment by RobinHossain** [comment]
thanks Matt !
