### ISSUE TITLE
Login Error...

### ISSUE THREAD

**Issue by AndersonBasico** [googleanalytics/ga-dev-tools#1232]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ikuleshov** [comment]
Hello,

Thank you for reporting this issue. The team is aware of the problem and we expect the full functionality of the Demos and Tools site to be restored asap.

Thanks,
Ilya
