### ISSUE TITLE
Error on https://ga-dev-tools.web.app When Trying to Visit GA4 Dimensions & Metrics Explorer

### ISSUE THREAD

**Issue by navneetsingh-abacasys** [googleanalytics/ga-dev-tools#1237]
**What page is this happening on**
https://ga-dev-tools.web.app/ga4/dimensions-metrics-explorer/

**Describe the bug**
Getting following error, even though I am logged into Google Analytics & cookies on my system are enabled:
`Login status could not be determined. Please ensure cookies are enabled.`

**To Reproduce**
1. Go to https://ga-dev-tools.web.app/
2. Select "GA4"
3. Select the "Dimensions & Metrics Explorer"
4. Then This error will be visible 

**Screenshots**
<img width="1440" alt="Screenshot 2023-02-09 at 10 09 34 AM" src="https://user-images.githubusercontent.com/100752092/217719598-7e3ad044-e311-4f25-bfe5-40229f91dec6.png">

**Desktop (please complete the following information):**
 - OS: MacOS 13.1
 - Browser: Chrome
 - Version: 109.0.5414.119 (Official Build) (arm64)

**Comment by ikuleshov** [comment]
Hello,

Thank you for reporting this issue. The team is aware of the problem and we expect the full functionality of the Demos and Tools site to be restored asap.

Thanks,
Ilya
