### ISSUE TITLE
GA4 Query Explorer Login status could not be determined. Please ensure cookies are enabled.

### ISSUE THREAD

**Issue by stefanoallima** [googleanalytics/ga-dev-tools#1244]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 
https://ga-dev-tools.web.app/ga4/query-explorer/

**Describe the bug**
error message

GA4 Query Explorer
Login status could not be determined. Please ensure cookies are enabled.

**To Reproduce**

**Expected behavior**
see the website page

**Screenshots**
![image](https://user-images.githubusercontent.com/7222014/217822446-3bce779e-4570-4e36-b7af-7e5d63ef599e.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stefanoallima** [comment]
i tried multiple times with multiple browsers without any cookie restrictions

i also tried deleting all cookies and reload the page but is still get the error

on the uniiversal analytics i can navigate without issues

**Comment by aa-ardanirahman** [comment]
i got same issue

**Comment by skartopawiro** [comment]
I got the same issue

**Comment by adrianoaraujocoelho** [comment]
Estou tendo o mesmo problema.
