### ISSUE TITLE
Google Query Explorer Access Token Issue

### ISSUE THREAD

**Issue by jzzhang123** [googleanalytics/ga-dev-tools#125]
Is there an issue with the Query Explorer? We are getting: Ack! There was an error ()Cannot read property 'access_token' of null.

Thanks

Jason

**Comment by philipwalton** [comment]
Yes, this is mentioned in https://github.com/googleanalytics/ga-dev-tools/issues/57 and will be fixed soon when the changes to the Embed API go live (which support automatically refreshing the access token).

For now, refreshing the page should fix the issue.

**Comment by mikekaminsky** [comment]
FWIW I'm having this same issue and refreshing *does not* fix the issue.

**Comment by eltharionx** [comment]
@mikekaminsky I am having the exact same issue as you.  Clearing cookies/cache, closing browser still result in the same error.  It allows me to authorize then once I hit "Run Query" it gives the following error:
Ack! There was an error ()Cannot read property 'access_token' of null

@philipwalton Please advise.

**Comment by philipwalton** [comment]
Yeah, sorry, it looks like the new Embed API changes went live last night and there was one place in the code where I hadn't made the needed changes.

It should be fixed now though. Let me know if you're still having issues.

**Comment by eltharionx** [comment]
Yes! That worked, thank you!
