### ISSUE TITLE
Hit Builder GA4 and GA3 https://ga-dev-tools.web.app/hit-builder/ does not work under any of my accounts. 

### ISSUE THREAD

**Issue by bykovmykhail** [googleanalytics/ga-dev-tools#1252]
Hit Builder GA4 and GA3 https://ga-dev-tools.web.app/hit-builder/ does not work under any of my accounts. 
Writes the following error: 
"Login status could not be determined. Please ensure cookies are enabled."

**To Reproduce**
1. Go to https://ga-dev-tools.web.app/hit-builder/
2. Click on Hit Builder menu item
See error - "Login status could not be determined. Please ensure cookies are enabled."

  All cookies are enabled. I cleared them again logged into my account, but still see this error.
  I can't log in with any of my work and home accounts.  I am a web analyst, I am very uncomfortable to work without this tool. ((

**Comment by flexsibel** [comment]
Argh everyone has this issue! So annoying
