### ISSUE TITLE
GA Dev Tools Error: Login status could not be determined. 

### ISSUE THREAD

**Issue by catmblake** [googleanalytics/ga-dev-tools#1256]
**What page is this happening on**
https://ga-dev-tools.web.app/query-explorer/

**Describe the bug**
Login status could not be determined. Please ensure cookies are enabled.

**To Reproduce**
1. Go to https://ga-dev-tools.web.app/query-explorer/

**Expected behavior**
Recognize login credentials and access GA hit builder, query explorer tools etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/44444346/218222120-8030fbe5-60fc-424d-97cd-81cae7397503.png)

**Desktop (please complete the following information):**
 - OS: Mac and Windows
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by toinbis** [comment]
Same here!

**Comment by RogierWijsman** [comment]
same here

**Comment by ceaksan** [comment]
The problem may not be directly with the cookie, but with the Client ID definition.

`{error: 'idpiframe_initialization_failed', details: "Not a valid origin for the client: https://ga-dev-…egister this origin for your project's client ID."}
details
: 
"Not a valid origin for the client: https://ga-dev-tools.web.app has not been registered for client ID 793177......-olst43lspv93vkoql0b9l26hmp.......apps.googleusercontent.com. Please go to https://console.developers.google.com/ and register this origin for your project's client ID."
error
: 
"idpiframe_initialization_failed"`
