### ISSUE TITLE
I can't pull my data

### ISSUE THREAD

**Issue by IslamMuhammad** [googleanalytics/ga-dev-tools#126]
Everytime I try to pull data through Query explorer I get that Error, Ack! There was an error ()Cannot read property 'access_token' of null, How can I solve this problem.

![fireshot capture 50 - query explorer google an_ - https___ga-dev-tools appspot com_query-explorer_](https://cloud.githubusercontent.com/assets/15625215/10902305/323e0c64-8215-11e5-82cf-c551251e250d.png)

**Comment by philipwalton** [comment]
Thanks, this is fixed now. See #125 for more details.
