### ISSUE TITLE
Login status could not be determined - GA4 Dimensions & Metrics Explorer

### ISSUE THREAD

**Issue by rachelywong** [googleanalytics/ga-dev-tools#1269]
What page is this happening on
https://ga-dev-tools.web.app/query-explorer/

Describe the bug
Login status could not be determined. Please ensure cookies are enabled.

To Reproduce

Go to https://ga-dev-tools.web.app/query-explorer/
See error
Expected behavior
Recognize login credentials and access GA hit builder, query explorer tools etc.

Screenshots
image

Desktop (please complete the following information):

OS: Mac and Windows
Browser: Chrome
Smartphone (please complete the following information):

Additional context

**Comment by QuentinAdt** [comment]
The solution involves accessing the locker icon located beside the URL field in Google Chrome. From there, select the option for "Cookies" and uncheck the box next to "Block Cookies" or a similar setting, which may be labeled as "Bloquer les cookies tiers" in French.
