### ISSUE TITLE
Cannot read property 'access_token' of nul

### ISSUE THREAD

**Issue by jmeiling** [googleanalytics/ga-dev-tools#127]
Starting today I get this issue: "Cannot read property 'access_token' of nul" when I want to run a query using the Query Explorer. All parameter settings haven't been changed and all seem okay. 

I hope somebody can help me with this.

**Comment by blockb** [comment]
I have the same problem...

**Comment by philipwalton** [comment]
Thanks for reporting, this should be fixed now. Feel free to reopen if you're still having issues.
