### ISSUE TITLE
OAuth error

### ISSUE THREAD

**Issue by rutiger** [googleanalytics/ga-dev-tools#128]
Every time I try to submit a query I get the following error: 'Ack! There was an error ()Cannot read property 'access_token' of null'. My authentication is correct and the query is well formed.

<aside class="Error" data-reactid=".1.4.1"><h3 class="Error-title" data-reactid=".1.4.1.0"><span data-reactid=".1.4.1.0.0">Ack! There was an error (</span><span data-reactid=".1.4.1.0.2">)</span></h3><p class="Error-message" data-reactid=".1.4.1.1">Cannot read property 'access_token' of null</p></aside>

**Comment by philipwalton** [comment]
Thanks, this is fixed now. See #125 for more details.
