### ISSUE TITLE
Query Explorer Error: Token Errors

### ISSUE THREAD

**Issue by adamjgb** [googleanalytics/ga-dev-tools#129]
I've today started getting an errors when using the query explorer where it will not return results and just gives one of two errors:

Chrome (Latest Version)
Ack! There was an error () Cannot read property 'access_token' of null

I have tried:
Refreshing the page - no effect error persists
Logging out of and back into my Google account - no effect error persists

Firefox (Latest Version)
Ack! There was an error () gapi.auth.getToken(...) is null

I have tried:
Refreshing the page - no effect error persists
Logging out of and back into my Google account - no effect error persists

Please could I have some help resolving this as I use the query explorer many times a day, every day and it is a key part of getting my job done.

**Comment by benjamingrobertson** [comment]
We are experiencing the same issue, in Chrome and Safari. Please help :)

**Comment by AuthenticOtter** [comment]
I am experiencing the same issue. There is a new "Click here to authorize -->" bar at the top. Then get the typical authorize window (https://accounts.google.com/ServiceLogin...). That seems to work. When running a query I get the message:

"Ack! There was an error ()Cannot read property 'access_token' of null"

**Comment by adamjgb** [comment]
I also had the "Click here to authorize -->" bar at the top and went through the usual Google OAuth window without any incident before I started getting the token errors.

**Comment by ana-mariamocanu** [comment]
Hi,

I am having the same issue with the google analyzer and the query URI.
I get the 'Ack! There was an error ()Cannot read property 'access_token' of null' - tried to restart the browser, and used different accounts.
Has anyone found a solution around it?

Thanks

**Comment by philipwalton** [comment]
Thanks, this is fixed now. See #125 for more details.
