### ISSUE TITLE
Query Explorer Broken Access Token

### ISSUE THREAD

**Issue by neilfunk** [googleanalytics/ga-dev-tools#130]
I use GA Query Explorer very regularly - when I logged in today I was asked to re-authenticate my account. After I did so, I have been given this error repeatedly:

Ack! There was an error ()Cannot read property 'access_token' of null

I have confirmed that this is happening to others within my domain. Does anyone know what could be causing this?

**Comment by philipwalton** [comment]
Thanks, this is fixed now. See #125 for more details.
