### ISSUE TITLE
Authentication with Bitly not loading.

### ISSUE THREAD

**Issue by dorisradicevic** [googleanalytics/ga-dev-tools#1314]
**What page is this happening on**
1) https://ga-dev-tools.google/campaign-url-builder/
2) https://ga-dev-tools.google/bitly-auth/?code=80724b948b151ac7a81c4bef4048230ee04c8d95

**Describe the bug**
Authentication with Bitly not loading.

**To Reproduce**
1. Go to 'Campaign URL Builder'
2. Click on 'Shorten Link'
3. See error

**Expected behavior**
Link to be shortened.

**Screenshots**
<img width="638" alt="image" src="https://user-images.githubusercontent.com/125530119/219264714-e5c083df-60ea-4cab-9bf2-e59f011c8fa8.png">

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser Chrome

**Comment by SupriyaNZ** [comment]
SAME ISSUE i AM FACING
