### ISSUE TITLE
Bitly Authentication 

### ISSUE THREAD

**Issue by SupriyaNZ** [googleanalytics/ga-dev-tools#1316]
![Screenshot (187)](https://user-images.githubusercontent.com/125530443/219272537-d597f6e6-2701-40e6-ab9e-2ecc711e90bb.png)
What page is this happening on

https://ga-dev-tools.google/campaign-url-builder/
https://ga-dev-tools.google/bitly-auth/?code=80724b948b151ac7a81c4bef4048230ee04c8d95

Describe the bug
Authentication with Bitly not loading.

To Reproduce

Go to 'Campaign URL Builder'
Click on 'Shorten Link'
See error
Expected behavior
Link to be shortened.

**Comment by barnettwaddingham** [comment]
We've got the same issue this morning and still ongoing

**Comment by petyadh** [comment]
Same issue here. Thought it's a temporary bug as I bumped into it yesterday but still occurring today.
