### ISSUE TITLE
Issue with page views and events

### ISSUE THREAD

**Issue by ana-mariamocanu** [googleanalytics/ga-dev-tools#134]
Hey there,

I am trying to analyse the traffic on one of our website using pageviews and 2 events (follow and downloads - these are triggered by buttons on the page). I am then importing the data into Qlikview, in order to create dashboards for the business (I am using qv source for that and test the GA stats using the query analyser) 
I assumed that users cannot download or follow without leaving impressions on the page, therefore I modelled the data based on an ID (extracted from the URL), loading the page views first. However, I can see that users downloaded documents without being tracked as page views - can you please tell me why this is the case, and whether it is possible to change it?
I am trying to understand how to best model the data, and still get the right downloads from GA.

Thanks a lot!
Ana

**Comment by philipwalton** [comment]
Hello, these issues are for problems with the Demos & Tools site in particular, not Google Analytics questions in general.

Please see http://developers.google.com/analytics/help to find the best forum to get your questions answered.

**Comment by ana-mariamocanu** [comment]
Hi Philp,

Thank you for coming back to me - I dont know where to post this question, as I think it is generally GA related.
My question is why total events are shown in the query analyzer and page impressions are not, for the same URL?

Thanks,
Ana

**Comment by philipwalton** [comment]
The link I posted will tell you where to ask your Google Analytics questions.

By the way, page impressions are related to Google search and webmaster tools, not Google Analytics.
