### ISSUE TITLE
bit.ly will not authenticate

### ISSUE THREAD

**Issue by amy-emeraldscientific** [googleanalytics/ga-dev-tools#1365]
**What page is this happening on**
https://bitly.com/oauth/authorize?client_id=70e3a2804f36daeec48079ca7213aee795c7e76b&redirect_uri=https://ga-dev-tools.google/bitly-auth

**Describe the bug**
Click the "shorten Link" button, pop-up opens asking for permission to access my bit.ly, I click "Allow", screen says "Authenticating" but it never actually does.

**To Reproduce**
1. Click the "shorten Link" button
2. pop-up opens asking for permission to access my bit.ly
3. I click "Allow"
4. screen says "Authenticating" but it never actually does.

**Expected behavior**
It should authenticate!

**Screenshots**
![image](https://user-images.githubusercontent.com/125645227/219594262-23c2a53e-2816-4a11-aa31-e20ee8f3151f.png)

![image](https://user-images.githubusercontent.com/125645227/219594200-224af414-9343-428d-a704-7a4543d49276.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Version 110.0.5481.104

**Comment by cvetkovicmiona** [comment]
Same problem here!
