### ISSUE TITLE
Campaign URL Builder is stuck at Bit.ly authentication

### ISSUE THREAD

**Issue by fcmarketingteam** [googleanalytics/ga-dev-tools#1366]
**What page is this happening on**

- https://ga-dev-tools.google/ga4/campaign-url-builder/
- https://ga-dev-tools.google/bitly-auth/?code=ba419a322cbdb0f9d458100d423e4b432d488525

**Describe the bug**
On the Campaign URL builder page, whenever I click "shorten link", bitly.com's pop-up screen gets stuck at the authentication process. This happens even when I am already logged in on Bitly.

**To Reproduce**
1. Go to https://ga-dev-tools.google/ga4/campaign-url-builder/ and fill out all the fields
2. Click on 'Shorten link'
3. On the pop-up that appears, click 'Sign in with bitly account' and log in with Bitly credentials
4. On the next popup (Authorize Google Analytics Demos & Tools to use your account?) click 'Allow'
5. See error: Bitly Auth page stuck without authenticating

**Expected behavior**
I expect the Bitly auth page to complete loading and allow me to shorten campaign urls in https://ga-dev-tools.google/ga4/campaign-url-builder/ to bit.ly format.

**Screenshots**
![bitly stuck screen](https://user-images.githubusercontent.com/125552587/219598759-f563af17-d2b0-4e47-b2cd-37f2e6f11259.png)
![bitly account with no integrations connected](https://user-images.githubusercontent.com/125552587/219598789-2862d702-e4d4-40b3-b3b2-bd45cb7579e7.png)

**Desktop (please complete the following information):**
OS: iOS
Browser Chrome
Version 109.0.5414.119

**Comment by taylor-dot-exe** [comment]
I am having this exact same issue and have not found a solution.

**Comment by saramq** [comment]
I've reported this daily for the past week. Still no update...

**Comment by JillatNHS** [comment]
I'm having the exact same problem - can I shorten the generated long link in Bitly and still track the engagement via campaign builder?

**Comment by JBach85** [comment]
same problem! :(

**Comment by shuttlenaut** [comment]
same issue!

**Comment by SlideUpLift123** [comment]
Even i am facing the same issue with no solution yet! :(

**Comment by JillatNHS** [comment]
Good news!  This now looks to be resolved :)
