### ISSUE TITLE
Authorization with Bitly Timing Out 

### ISSUE THREAD

**Issue by mayeskey** [googleanalytics/ga-dev-tools#1372]
**What page is this happening on**
[Copy the URL of the page this issue is happening on. 
](https://ga-dev-tools.google/campaign-url-builder/)

**Describe the bug**
Trying to create campaign URL it asks to authenitcate, and when it tries to authorize with Bitly, it times out. Nothing happens. 

**To Reproduce**

**Expected behavior**
I have never had an issue authorizing GA or bitly, it has been seamless for me for 3 years of daily use. 

**Screenshots**

**Desktop (please complete the 
![Screenshot 2023-02-17 at 9 17 21 AM](https://user-images.githubusercontent.com/125577046/219680065-62ab4e23-d5dd-475b-bb45-d8886e38d49e.png)
![Screenshot 2023-02-17 at 9 17 28 AM](https://user-images.githubusercontent.com/125577046/219680068-1e0f3b7e-51fb-4bcc-b799-684700faa4c2.png)
following information):**
Chrome, Version 110.0.5481.100 (Official Build) (arm64)
Macbook Pro 

**Additional context**

**Comment by ankyann** [comment]
@mayeskey did you manage to sort this out? Struggling with the same thing.

**Comment by mayeskey** [comment]
No. Bitly says it’s a Google issue. It’s really impacting my workflow and the only answer I have received is that it’s a known bug and they are working on it.


Mary Alice Fallon Yeskey | Journals Publicity Manager
Johns Hopkins University Press<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.proofpoint.com%2Fv2%2Furl%3Fu%3Dhttps-3A__www.press.jhu.edu_%26d%3DDwMF-g%26c%3DmRWFL96tuqj9V0Jjj4h40ddo0XsmttALwKjAEOCyUjY%26r%3DKe-QVxcJUOV516LfYAQVYTfZIfzCeBPI4Zmjlsd7mfo%26m%3DNqRhbxH6Nx4NKS-Aziap4JRyFjW9OTr9y2L97VBoiY8%26s%3DH7i1QTn2W_N-WI5kRxD0T0eMGmUDb2awrMi4GO2-zMg%26e%3D&data=04%7C01%7Cmyeskey1%40jhu.edu%7C59d245781480414308a308d97e9ad479%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637680025728724913%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oVh3TIaFijbPOz2C2jMzttJr54dkvZowCN4GfG%2FBHZ4%3D&reserved=0>

c: 443.996.8050 | @maryaliceyeskey<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.proofpoint.com%2Fv2%2Furl%3Fu%3Dhttps-3A__nam02.safelinks.protection.outlook.com_-3Furl-3Dhttp-253A-252F-252Fwww.twitter.com-252Fmaryaliceyeskey-26data-3D04-257C01-257Cmyeskey1-2540jhu.edu-257C32b64cbcb26444022e4a08d8d1aaf5eb-257C9fa4f438b1e6473b803f86f8aedf0dec-257C0-257C0-257C637489879487272431-257CUnknown-257CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0-253D-257C1000-26sdata-3DiwiBce-252FtW4X1A9BVI-252FaPGr2KDNwBiDLg25zmCw-252BXKfU-253D-26reserved-3D0%26d%3DDwMF-g%26c%3DmRWFL96tuqj9V0Jjj4h40ddo0XsmttALwKjAEOCyUjY%26r%3DKe-QVxcJUOV516LfYAQVYTfZIfzCeBPI4Zmjlsd7mfo%26m%3DNqRhbxH6Nx4NKS-Aziap4JRyFjW9OTr9y2L97VBoiY8%26s%3D8Ezte98h8J7e7fZOjOWJ6LOHFT04AmXEwOc9hvyJOpc%26e%3D&data=04%7C01%7Cmyeskey1%40jhu.edu%7C59d245781480414308a308d97e9ad479%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637680025728734906%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1wqxev8po2eUbFua7v3c8i6%2Bsmp9faY%2FE%2FKGfoSiK9s%3D&reserved=0> | she/her

________________________________
