### ISSUE TITLE
Bitly not authentication with Google Analytics

### ISSUE THREAD

**Issue by WorkplaceFuturesGroup** [googleanalytics/ga-dev-tools#1373]
**What page is this happening on**
https://ga-dev-tools.google/campaign-url-builder/

**Describe the bug**
We are trying to shorten links with campaign builder, which is what we always do as it's connected to our Bitly account. However, it is no longer working and requests us to authenticate with Bitly. When we do, it stays on the authentication page forever and doesn't move forward, meaning we are no longer able to create links with campaign builder. See screenshot attached: https://ibb.co/tXJVSXt

**Expected behavior**
Bitly should have been able to authenticate with Campaign builder and let us create shortened bitly links created to our account.

**Comment by Cadeau-Design** [comment]
The same is actually happening to me and I can't get any answers

**Comment by Sandman36** [comment]
I'm having the same issue.

**Comment by petronegin** [comment]
Same issue with me

**Comment by cvetkovicmiona** [comment]
Same problem here!

**Comment by jdross899** [comment]
I am having the same issue. I tried to delete the integration and retry and that failed as well.

**Comment by ShellyAufray** [comment]
I am having the same issue and reached out to Bitly support, this morning - no news yet. Glad that it appears it is a known issue. This is wreaking havoc for our campaigns.

**Comment by ShellyAufray** [comment]
Here's the screenshot - the screen stays stuck on this screen - and NEVER authenticates. Hoping that Bitly Support will jump on this thread soon with a resolve.
![Screenshot 2](https://user-images.githubusercontent.com/126295327/221607774-bb488a1b-c5d6-4587-8023-c3807ad9999c.JPG)

**Comment by ShellyAufray** [comment]
Bitly Support responded today that this is a known issue that they are working to remedy.
![Bitly Message](https://user-images.githubusercontent.com/126295327/221609789-da22da2e-4876-43ec-a02c-563b2b4eecea.JPG)

**Comment by ShellyAufray** [comment]
I heard back from Bitly support this morning and this is a known issue that they are working to remedy.
![bitly message 2](https://user-images.githubusercontent.com/126295327/221610073-60d300a8-0efc-4b3a-ad1d-05e641db9474.JPG)
