### ISSUE TITLE
Authenticating Bitly in Google Campaign Builder

### ISSUE THREAD

**Issue by Rogue161** [googleanalytics/ga-dev-tools#1375]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 

https://ga-dev-tools.google/bitly-auth/?code=279cdba8a4be050044908154247859e647120778

**Describe the bug**

Claims to be "authenticating Bitly" but never moves beyond the initial screen.

**To Reproduce**
1. Go to 'Campaign URL Builder'
2. Click on 'Shorten Link'
3. Log into Bitly Account

**Expected behavior**

It connects to my Bitly account

**Screenshots**

I don't have any

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version No Idea

**Additional context**

**Comment by caitlin5253** [comment]
I am also having the same issue
