### ISSUE TITLE
URL Builder no longer links to Bitly

### ISSUE THREAD

**Issue by jslepski** [googleanalytics/ga-dev-tools#1379]
**What page is this happening on**
[Copy the URL of the page this issue is happening on.](https://ga-dev-tools.google/ga4/campaign-url-builder/) 

**Describe the bug**
I'm trying to create a short link, using your bitly connection, and the verification will not work.

**To Reproduce**
1. Click on Shorten Link
2. It pops up and says Link your Bitly account
3. I follow those steps
4. It then hangs up on a page that says... Authenticating with bitly...

**Expected behavior**
Should link to Bitly, then close the window. I then should be able to make short links.

**Screenshots**
![image](https://user-images.githubusercontent.com/125696279/219773132-8e9db6ce-387b-4a97-96d0-a0bd41345cb8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser both chrome and Edge
 - Version both updated to most recent

**Additional context**
This has worked fine for me for years.

**Comment by ferrrjimenez** [comment]
Me too!

**Comment by CombiTaiwan** [comment]
Me too. :(
