### ISSUE TITLE
Historical data mismatch

### ISSUE THREAD

**Issue by ana-mariamocanu** [googleanalytics/ga-dev-tools#138]
Hi there,

I am using google analytics to track website and app traffic data every week.
I have the case of 3 user ID dimensions appearing in the stats for 11 November, but I am not able to see those users when I currently run the reports.
Can you please advise?

Thanks a lot,
Ana

**Comment by philipwalton** [comment]
Hi Ana, as stated in the [README](https://github.com/googleanalytics/ga-dev-tools), this repo is not for ask general Google Analytics questions. Please see [developers.google.com/analytics/help](https://developers.google.com/analytics/help/) to find the best place to ask that question.
