### ISSUE TITLE
bit.ly will not authenticate

### ISSUE THREAD

**Issue by joostnaardeyoga** [googleanalytics/ga-dev-tools#1398]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 
https://ga-dev-tools.google/bitly-auth/?code=cb7acf538cea441e8c3d3056e5e398bf066b0800

**Describe the bug**
Bitly will not connect with ga dev tools, i have already tried to activate 2f, but is still does not autenticate. 

**To Reproduce**
1. Go to '...' https://ga-dev-tools.google/campaign-url-builder/
2. Click on '....' Shorten link
3. Allow

**Expected behavior**
That bitly would autenticate with ga dev tools

**Screenshots**
![image](https://user-images.githubusercontent.com/125867947/220060701-3f5d6b70-6229-4521-9875-ada2e6798504.png)

**Desktop (please complete the following information):**
 - Windows
 - Browser chrome, and edge and opera
 - Version ?

**Comment by kabkstudio** [comment]
same issue

On macOS Big Sur version 11.7.2
using Chrome Version 109.0.5414.119 (Official Build) (x86_64)

**Comment by NewsThump** [comment]
Same issue, been the case for about a week now.
