### ISSUE TITLE
App engine code for  Enhanced Ecommerce Demo Store

### ISSUE THREAD

**Issue by StephenBrown** [googleanalytics/ga-dev-tools#140]
Being able to use the actual demo store with a GTM container would be powerful. Then we can use the GTM Preview to see the tags firing, or not firing, and send the data to a Google Analytics account, or fire other tags using the datalayer from the ecommerce interactions.

**Comment by philipwalton** [comment]
The Enhanced Ecommerce demo was built on using a few internal Google tools, so unfortunately it cannot be open-sourced in its current form.

In the future we'll try to ensure that all demos/tools are built entirely with open-source software so they can be released on Github.
