### ISSUE TITLE
Less results when expanding the date

### ISSUE THREAD

**Issue by Mascha89** [googleanalytics/ga-dev-tools#141]
True the Query Explorer I'm trying to export data to Excel. I use different metrics, dimensions and filters. The strange thing is when I adjust the date to a longer period of time the number of results are decreased instead of increased. 
Do you have any idea how this is possible?
Below an example.
Thanks!

![bb-example-long-period](https://cloud.githubusercontent.com/assets/16081776/11470815/182b308e-9761-11e5-9915-dab0a461421e.JPG)
![bb-example-short-period](https://cloud.githubusercontent.com/assets/16081776/11470816/18300e42-9761-11e5-9f0a-68a1986e5dba.JPG)

**Comment by mcohoon** [comment]
If you look at the images you provided both results say "Contains sampled data: yes" In all likelihood this is the cause of the issue.  You could provide a value for [samplingLevel](https://developers.google.com/analytics/devguides/reporting/core/v3/reference#samplingLevel). In addition this forum is for reporting issues with the Demos and tools site. to actually get help with google analytics please see the [Support page](https://developers.google.com/analytics/devguides/reporting/core/v3/help)
