### ISSUE TITLE
Bitly Auth

### ISSUE THREAD

**Issue by esims22** [googleanalytics/ga-dev-tools#1419]
**What page is this happening on**
[Copy the URL of the page this issue is happening on.]
(https://ga-dev-tools.google/campaign-url-builder/)

**Describe the bug**
When I try to shorten link, I click ALLOW, and the screen just says:
Bitly Auth
Authenticating with bitly...
but it never finishes.

**Comment by Snoopy870** [comment]
I’m so lost

**Comment by esims22** [comment]
@Snoopy870 the workaround, thankfully, is just creating your short links directly in the Bitly dashboard.

**Comment by esims22** [comment]
It takes so much longer though because you have to enter in the parameters every. single. time.

**Comment by Snoopy870** [comment]
Look it's not me. My account was linked to it. I'm still lost how to
Open. Please help

**Comment by esims22** [comment]
@Snoopy870 you just need to log in directly to your Bitly account. https://app.bitly.com/ From there, you can still make shortened links.

**Comment by esims22** [comment]
Totally agree. Hopefully someone will respond and fix the authentication issue ASAP.
