### ISSUE TITLE
Campaign URL Builder is stuck at Bit.ly authentication

### ISSUE THREAD

**Issue by willtworkman** [googleanalytics/ga-dev-tools#1425]
What page is this happening on

https://ga-dev-tools.google/ga4/campaign-url-builder/
https://ga-dev-tools.google/bitly-auth/?code=ba419a322cbdb0f9d458100d423e4b432d488525
Describe the bug
On the Campaign URL builder page, whenever I click "shorten link", bitly.com's pop-up screen gets stuck at the authentication process. This happens even when I am already logged in on Bitly.

To Reproduce

Go to https://ga-dev-tools.google/ga4/campaign-url-builder/ and fill out all the fields
Click on 'Shorten link'
On the pop-up that appears, click 'Sign in with bitly account' and log in with Bitly credentials
On the next popup (Authorize Google Analytics Demos & Tools to use your account?) click 'Allow'
See error: Bitly Auth page stuck without authenticating
Expected behavior
I expect the Bitly auth page to complete loading and allow me to shorten campaign urls in https://ga-dev-tools.google/ga4/campaign-url-builder/ to bit.ly format.

![image](https://user-images.githubusercontent.com/125908897/220167177-d81a7d0b-cf67-4b9b-b742-fcdbe8c10708.png)

**Comment by JorisHulstaert** [comment]
Following - we're having the exact same issue.

**Comment by chadwallington** [comment]
following, same issue

**Comment by CombiTaiwan** [comment]
following, same issue :(

**Comment by LouCameron** [comment]
We're have the same issue. 
Using Google Chrome on mac - latest version of Google: Version 110.0.5481.100 (Official Build) (x86_64)
I've cleared all cache / cookies etc. but that didn't help either. 

Following to see if there is an answer! Has anyone tried revoking the access in Bitly and then re-integrating?

**Comment by NewsThump** [comment]
Following, same issue
