### ISSUE TITLE
Bitly Authentication

### ISSUE THREAD

**Issue by radiojunk** [googleanalytics/ga-dev-tools#1429]
[**What page is this happening on**](https://ga-dev-tools.google/campaign-url-builder/)
Copy the URL of the page this issue is happening on. 

Unable to shorten UTM link as I am stuck in the Bitly Authentication process

**To Reproduce**
1. Create the UTM Link
2. Click on "Shorten Link"
3. Pop Up screen to authorise Google Analytics Demos & Tools to use your account.
4. Click Allow
5. Stuck at the pop up screen
![Bitly Auth Error](https://user-images.githubusercontent.com/125944698/220247553-9f3c4756-3409-4410-a7b2-76756e1eea5d.jpg)

**Expected behavior**
Pop up screen will disappear after authorisation and shorten link will appear.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome]
 - Version 110.0.5481.104 (Official Build) (64-bit)

**Additional context**
Happened after the Microsoft surge where my company was also affected.

**Comment by cnelsonATR** [comment]
Also having the same issue here
