### ISSUE TITLE
Final token for access to the Analytics API, which does not expire

### ISSUE THREAD

**Issue by fillipesouzaaraujo** [googleanalytics/ga-dev-tools#144]
how to create a token that does not expire for use in the function "gapi.analytics.auth.authorize ({
                 serverAuth: {
                     access_token: XXXX
                 }
             }); "

I am using the javascript language.

thank you

**Comment by philipwalton** [comment]
It's impossible to create a token that does not expire. You can read the [OAuth documentation](https://developers.google.com/identity/protocols/OAuth2) for more details.

**Comment by fillipesouzaaraujo** [comment]
Thank You!
