### ISSUE TITLE
Can't create shortlinks with the URL campaign builder

### ISSUE THREAD

**Issue by laineyescarcega** [googleanalytics/ga-dev-tools#1455]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 
https://ga-dev-tools.web.app/campaign-url-builder/

**Describe the bug**
When I try to create a shortlink, it prompts me to login to my bit.ly account. When I attempt to do this, the page never loads after I login. It says "Authenticating bit.ly" and never loads. 

**To Reproduce**
1. Go to 'link'
2. create a campaign
3. click "shorten link"
4. page pops up prompting to login to bit.ly, try logging in and page never loads. 

**Expected behavior**
If the page were to load, I assume I'd be able to complete my action and go back to creating shortlinks. For now, I can't create any because it won't let me login to bit.ly.

**Screenshots**
Prompted to login after clicking "shorten link" - https://drive.google.com/file/d/1f1HWNL0lCh72piTMSZAidrfSmmMImM00/view?usp=share_link

logged in, prompted to click "allow" - https://drive.google.com/file/d/1lPU_eVAF8MrRD4AI-zr_qY820LCxJnIJ/view?usp=share_link

After clicking "allow", I'm brought to this page that never loads - https://drive.google.com/file/d/1mrdi8nN5OzFj-nOdy1AVMvTd3cjpgSMm/view?usp=share_link

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Mojave
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] MacOS Mojave Version 10.14.6

**Additional context**

**Comment by emilyasaro448** [comment]
I am having the same issue.

**Comment by emilyasaro448** [comment]
How was this issue resolved?

**Comment by laineyescarcega** [comment]
This is still not working for me
