### ISSUE TITLE
Authenticating with Bitly doesn't work

### ISSUE THREAD

**Issue by BarSecur** [googleanalytics/ga-dev-tools#1469]
**What page is this happening on**
[Copy the URL of the page this issue is happening on. ](https://ga-dev-tools.google/campaign-url-builder/)

**Describe the bug**
When klicking on "Shorten Link" and allowing Google Analytics Demos & Tools to access my Bitly account, a loading screen appears but nothuing happens.

**To Reproduce**
1. Go to ['...'](https://ga-dev-tools.google/campaign-url-builder/)
2. Click on 'Shorten Link'

**Expected behavior**
Normally (before Feb 17th), the link would be shortened in a second and no loading problem. If I remember it correctly, there also wouldn't be the "Allow Google Analytics Demos& Tools to access..." window.

**Screenshots**
![Bitly_error](https://user-images.githubusercontent.com/126059323/220605138-0bf1e1b1-6b59-4829-b641-f7e672485409.PNG)
![Bitly_error2](https://user-images.githubusercontent.com/126059323/220605150-7f889afc-bb0d-4185-bf9a-eb434920358f.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome, Firefox, Edge (tried all three)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by farahcoppola1987** [comment]
I have the same problem. How can you solve this?
