### ISSUE TITLE
Google UTM builder not connecting/authenticating with Bitly 

### ISSUE THREAD

**Issue by ChloeBeale** [googleanalytics/ga-dev-tools#1500]
**What page is this happening on**
https://ga-dev-tools.google/ga4/campaign-url-builder/

**Describe the bug**
When trying to shorten the link google analytics won't authenticate the connection with Bitly 

**To Reproduce**
1. Go to https://ga-dev-tools.google/ga4/campaign-url-builder/
2. Enter a URL in the top box, plus your UTM parameters,
3. Click 'SHORTEN URL' 
4. Authenticate via the Bitly pop-up - sign in to Bitly account required
5. See error

**Expected behavior**
It should authentic the connection with Bitly after entering Bitly account details, establishing a connection between Google Analytics and bitly 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**

**Comment by allstarzchrissy** [comment]
I'm experiencing exactly the same issue. It gets stuck on the 'Authenticating with bitly..." screen forever.

**Comment by allstarzchrissy** [comment]
(I am experiencing this issue with both Chrome & Edge browsers. I'm working on a laptop with Windows 10).

**Comment by JenRubin** [comment]
Same. I can't get any bity's created through the campaign URL builder. First I get a pop up asking me to authorize Google Analytics Demos & Tools for my account. When I click allow I think get the same message about authenticating with bitly - but it never does anything. I tried this on chrome and edge browsers for the last 6 days.

**Comment by Diniagaj** [comment]
Same issue here!
