### ISSUE TITLE
Bitly Authentication not working - impossible to shorten URL in Campaign URL Builder

### ISSUE THREAD

**Issue by exinmarketing** [googleanalytics/ga-dev-tools#1515]
**What page is this happening on**
https://ga-dev-tools.google/bitly-auth/

**Describe the bug**
Unable to connect the Bitly account with Google Campaign URL Builder. Therefore unable to shorten the URL. It says 'Bitly Auth
Authenticating with bitly...' and doesn't move on with the authentication.

**To Reproduce**
1. Go to 'https://ga-dev-tools.google/campaign-url-builder/'
2. Scroll down to 'Share the generated campaign URL'
3. Click on 'SHORTEN LINK'
4. Authenticate with Bitly
5. Get redirected to 'https://ga-dev-tools.google/bitly-auth/'
6. 'Bitly Auth' not working

**Expected behavior**
I should be able to connect my Bitly account (as always did in the past) and shorten the URL.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 110.0.5481.96 (Official Build) (arm64)

**Additional context**
<img width="1044" alt="Screenshot 2023-02-24 at 10 25 59" src="https://user-images.githubusercontent.com/124274975/221141870-ddb7600b-0043-42b4-b37c-d8024019360d.png">

**Comment by jkurzner** [comment]
Same issue.  No matter what I try I can't shorten my link by authenticating

**Comment by exinmarketing** [comment]
Working now. Thank!
