### ISSUE TITLE
Feature: I want to send my Google Analytics Property for test in Enhanced Ecommerce Demos

### ISSUE THREAD

**Issue by 1987yama3** [googleanalytics/ga-dev-tools#152]
I want to check enhanced ecommerce report of google analytics for test. Because I think that people are not know a report that can be see in enhanced ecommerce features. And me too.

So, I use Fiddler and rewrite the value of send property id in my computer, because I wanted to see the report in the actual screen. But it is very defficult for ordinary person. 

So I suggest this feature that we can send my Google Analytics Property for test in Enhanced Ecommerce Demo and Tools.

Thanks.

**Comment by 1987yama3** [comment]
Hello @philipwalton 
I have heard that Google has published a demo account of Google Analytics, https://support.google.com/analytics/answer/6367342?hl=en.

The demo account is very good! It has many of the features are setting such as Enhanced E-Commerce, AdWords Linking, Search Console Linking, Custom Dimension/Metrics, Data Import, Calculated Metrics and other features.

So, my demand has satisfied by this demo account. Is this issue may be closed?

**Comment by philipwalton** [comment]
Great to hear!
