### ISSUE TITLE
Bitly Account not Syncing with GA Dev Tools

### ISSUE THREAD

**Issue by sdavidsonn** [googleanalytics/ga-dev-tools#1545]
**What page is this happening on**
(https://ga-dev-tools.google/bitly-auth/?code=9589bc967ac90dad387eb05c72a7b69ce95142c7)

**Describe the bug**
When the window opens & says that it is authenticating with Bitly. It's frozen and does not connect with Bitly

**To Reproduce**
1. Go to (https://ga-dev-tools.google/campaign-url-builder/)
2. Click on "Shorten Link"
3. A window will pop up, click "Allow"

**Expected behavior**
I expected to either see a screen that says successful or for my connection to work so I can shorten my link

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Version 110.0.5481.105 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nqledford** [comment]
This still has not been corrected!!!
