### ISSUE TITLE
Cannot shorten link

### ISSUE THREAD

**Issue by Dorotea55** [googleanalytics/ga-dev-tools#1551]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 
https://bitly.com/oauth/authorize?client_id=70e3a2804f36daeec48079ca7213aee795c7e76b&redirect_uri=https://ga-dev-tools.google/bitly-auth 

**Describe the bug**
Trying to shorten the link, keeps sending me to 
Authorize Google Analytics Demos & Tools to use your account?
The application Google Analytics Demos & Tools is requesting permission to create links
and access your link history and data on your behalf.

Allow Google Analytics Demos & Tools to access your account?

and then it just loads and doesnt to anything

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ResMet** [comment]
I am having exactly the same problems.
After pressing the Allow button, nothin happens.

Will appreciate any advice on how to fix the problem.
