### ISSUE TITLE
Calculated Metrics

### ISSUE THREAD

**Issue by cemo** [googleanalytics/ga-dev-tools#157]
Please support calculated metrics as well.

**Comment by philipwalton** [comment]
Thanks for the suggestion. Calculated metrics need to be added to both the Core Reporting API and the Management API (so we can look up the current user's calculated metrics). When they are, we'll add them to the Query Explorer.

**Comment by jipiboily** [comment]
@philipwalton any plan on adding calculated metrics to the management API? It works for the core reporting API, even though it's not documented. A customer asked us that at Metrics Watch, and not being able to list them is a bit of a bummer :(

It might not the be the right place to ask, let me know if that is the case. Thanks!

**Comment by philipwalton** [comment]
@jipiboily I believe it's on the roadmap, but I'm not sure what the status is. I'll follow up with my coworker who works more closely with that team.

**Comment by jipiboily** [comment]
@philipwalton that would be great, thanks!

**Comment by tantalic** [comment]
@jipiboily Any update on this? Not having access to this via the management API really makes it difficult to use for large enterprise deployments.

**Comment by jipiboily** [comment]
No idea. Not a developer on this projet, was waiting for that too :)

JP Boily

Founder @ *Metrics Watch
<https://metricswatch.com/?utm_source=email&utm_medium=gmail-signature>* -
Reports & Alerts for Google Analytics

*PS*: *can you **trust your Google Analytics data*❓ Chances are, probably
not. We built a *free tool, the Metrics Watch Doctor
<https://metricswatch.com/doctor/?utm_source=email&utm_medium=gmail-signature>,*
to analyze your Google Analytics account and help you make it trustworthy
and useful.

*PPS*: Want to get the most out of Google Analytics? Get our *free* email
course <http://metricswatch.com/free-5-part-email-course/>.

**Comment by philipwalton** [comment]
I'm not sure what the status of calculated metrics in the Management API is, @mcohoon may be able to give an update.

**Comment by tantalic** [comment]
Is there an official means to request features for the Management API? As another example content grouping dimensions are not available via the Management API.

**Comment by philipwalton** [comment]
https://developers.google.com/analytics/help/

**Comment by Lucretiel** [comment]
https://issuetracker.google.com/35354190
