### ISSUE TITLE
Querying the GA data for more than 30 days returns incorrect session results ...

### ISSUE THREAD

**Issue by gauravzepo** [googleanalytics/ga-dev-tools#160]
I have an active GA account through which I use to query data for my users in dashboard. I have data in folowwing criteria:
Today,
Yesterday,
Last7 Days
Last 30 Days 

The first three are giving teh correct data whereas the last one gives incorrect data , Say as in Today's visitors are  10, Yesterday visitors are 7, Last 7 days visitors  are 25 . But last 30 day's visitors come up to 6 only . How is this happening , Is there a period limit on the time where I can query GA for data .

**Comment by philipwalton** [comment]
How do you know what the correct data is? Are you comparing this to the Google Analytics website?

**Comment by gauravzepo** [comment]
Hi Philip,
If I have 5 customers today and 10 customers yesterday , The last 30 days
data should be anyhow greater than 15 , but it is coming as 6..

On Fri, Jan 22, 2016 at 12:11 AM, Philip Walton <notifications@github.com>
wrote:

> How do you know what the correct data is? Are you comparing this to the
> Google Analytics website?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googleanalytics/ga-dev-tools/issues/160#issuecomment-173669264>
> .
>



-- 
-- 
Regards,

*Gaurav Chaudhary*
Java Developer

Good things should go online!

Mobile: +91-994-059-4767  | Email: gaurav@zepo.in  | Web: www.zepo.in

-- 
 -- --

**Comment by philipwalton** [comment]
I'm not sure what to tell you. It's possible you've entered in the wrong dates somehow. Either way, this is probably not an issue with the Demos & Tools site. If you think it's an issue witg the underlying API, you can report it here:
https://code.google.com/p/analytics-issues/issues/entry
