### ISSUE TITLE
Can't Interact with Google Analytics Query Explorer

### ISSUE THREAD

**Issue by swjacksonma** [googleanalytics/ga-dev-tools#164]
I used to use GA Query Explorer regularly. But, when I attempted to use it yesterday, all I was able to get was a "scrolling" blue horizontal line under the heading of the web page. The fill-in fields are all grayed out and show in the background, but are inaccessible. I tried logging in to Google before going to the page, and still cannot access the functionality on the Query Explorer. I have tried in Internet Explorer 9 as well as in Firefox 43.0.4. I was able to find a machine that has IE 11, and it worked there. But, I cannot upgrade to IE 11 on my primary machine, due to other application needs.

**Comment by philipwalton** [comment]
The Query Explorer should work fine in Firefox 43. I just ran it on my machine to confirm, and there were also 14,608  successful queries made from Firefox 43 in the last 30 days (according to our Google Analytics stats). If it's not working for you, that may be a different issue (feel free to reopen if you can reproduce it).

IE9 is not a browser we support. Note that [Microsoft doesn't even support IE9](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support), so you should strongly consider upgrading as IE9 is no longer getting security updates.

Chrome and Firefox are available on every platform and the Query Explorer works in the latest versions of both browsers.
