### ISSUE TITLE
After adding more than 5  column in headers, only able to view 5 though 6 are in results.

### ISSUE THREAD

**Issue by vmdhoke** [googleanalytics/ga-dev-tools#169]
If there are more than 3 metric and 3 dimentions making a total of more than 5 column in headers only 5 headers are visible 
here is a screenshot trying to correctly explain the issue
![query explorer google analytics demos tools](https://cloud.githubusercontent.com/assets/5667039/13026281/466e7cfe-d248-11e5-96b6-d976cf723dc5.png)

**Comment by philipwalton** [comment]
The other column is there, it's just scrolled out of view. You should see a scroll bar at the bottom of the table that will allow you to scroll to the right.
