### ISSUE TITLE
Query explorer not loading

### ISSUE THREAD

**Issue by repinfaust** [googleanalytics/ga-dev-tools#170]
Hi - The query explorer doesn't load. I just get the blue bar animation with all the fields below greyed out. I'm logged into my GA acc, have enabled the GA API and am using it through sheets so not sure why it won't load? (Chrome).

Thanks

**Comment by philipwalton** [comment]
Hmmm, it loads for me, so I'm not sure why it's not loading for you. Do you see any errors in the JavaScript console? Does it work for you on other browsers? Does it work for you on other demos/tools?

**Comment by repinfaust** [comment]
Sorry forgot to comment - I was blocking 3rd party cookies - this stops it from loading from the looks of things.
