### ISSUE TITLE
YearIsoWeek

### ISSUE THREAD

**Issue by paulstegmann** [googleanalytics/ga-dev-tools#171]
I get an error "Ack! There was an error (400)
Selected dimensions and metrics cannot be queried together."

I just want to group time filter by week: 
dimension:   ga:isoYearIsoWeek
metric: ga:adClicks

**Comment by philipwalton** [comment]
You can use the dimensions and metrics explorer to see which combinations work together:
https://developers.google.com/analytics/devguides/reporting/core/dimsmets#cats=adwords,time

It looks like most time dimensions can be queried with `ga:adClicks`, but the ISO ones cannot.
