### ISSUE TITLE
Typo in query-report.js: "paramter". Missing an "e", should be "parameter".

### ISSUE THREAD

**Issue by naltmann** [googleanalytics/ga-dev-tools#172]
https://github.com/googleanalytics/ga-dev-tools/blob/c766db7631065e6a4c44028b0d042a56176dbd9b/src/javascript/query-explorer/components/query-report.js

**Comment by philipwalton** [comment]
Thanks! Fixed via 4cc43b8eb6b6b9b0e7417d59e0bb828fd8d8ff7b.
