### ISSUE TITLE
How can I combine server side authorization with Third Party Visualizations.

### ISSUE THREAD

**Issue by ntantouris** [googleanalytics/ga-dev-tools#173]
Dear all, I want to have the module third party visualizations with server side authorization. The problem The error that I have is "Uncaught ReferenceError: accountSummaries is not defined". Probably because me service email has more than one accounts. Any suggestion?

**Comment by mcohoon** [comment]
It sounds like your authorized service object is not being properly built. You should probably post your code on [StackOverflow](http://stackoverflow.com/questions/tagged/google-analytics-api). But to answer your larger question [this demo](https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/) provides an example of server side auth.
