### ISSUE TITLE
'ids' unclear in Server-side Authorization example code

### ISSUE THREAD

**Issue by reblevins** [googleanalytics/ga-dev-tools#177]
First of all thanks for the great code examples. I have one small complaint, though. In the example code provided for "Server-side Authorization", in the query object, there is a key called 'ids'. You provided a sample id, but it was unclear from the tutorial that I should have replaced the id there with my own id. It took me about 2 hours to figure this out. Perhaps I'm just not very bright, but it might be helpful to make that more clear like you did with the access_token. So instead of `'ids': 'ga:100367422'` you could do something like: `'ids': 'YOUR_ACCOUNT_ID'`.

Thanks again.

**Comment by philipwalton** [comment]
Thanks. I clarified this in the most recent update. Hopefully it'll be more obvious now.
