### ISSUE TITLE
Reference to deprecated SignedJwtAssertionCredentials Object

### ISSUE THREAD

**Issue by mburke05** [googleanalytics/ga-dev-tools#178]
Hey guys,

I believe with the update to 2.0.0 the SignedJwtAssertionCredentials object is officially deprecated and no longer works with future upgrades. As such that section of this [probably](https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/) needs an update right?

Matt

**Comment by philipwalton** [comment]
Thanks! I didn't realize there was an upgrade. This should be fixed via #179.
