### ISSUE TITLE
Display the names given to custom definitions in results table

### ISSUE THREAD

**Issue by mikeh** [googleanalytics/ga-dev-tools#180]
<img width="1027" alt="query_explorer_ _google_analytics_demos___tools" src="https://cloud.githubusercontent.com/assets/48239/13843011/3334b1a8-ec29-11e5-950d-d33f2f00022f.png">
It would be great if the results table would show custom definition names for dimensions and metrics instead of just their index value. In the example above "Custom Metric 11 Value" means very little to my exec team.

**Comment by philipwalton** [comment]
Thanks for the suggestion. The Query Explorer here uses the Embed API to display this data, and that's the current behavior of the Embed API. I'll suggest it as a feature request for the Embed API, but it would have to be implemented there before it could be implemented here.
