### ISSUE TITLE
Google Analytics return corrupt data for after 19 march

### ISSUE THREAD

**Issue by mglrahul** [googleanalytics/ga-dev-tools#183]
I have an active GA account, i have fetch data from GA through the API and shows these data on dashboard page. But from past some days i have face a problem of getting the corrupted data from API. i got this corrupted data after 19 march 2016. I compare these data with [google dev tools](https://ga-dev-tools.appspot.com/query-explorer/) who also return the corrupted data for after 19 march, But when i check the data before the 19 march then both API and google dev tools return correct data. When i match this data with GA dashboard it return the correct data for all dates.

So the point is why the google dev tools and API return corrupt data when GA dashboard shows the correct data.in my API query I requested for goals data, instead it returns Session value. this happens In both google dev tools and API both.

**Comment by philipwalton** [comment]
If you're seeing an issue with the API then you should report it on the API's public issue tracker:
https://code.google.com/p/analytics-issues/issues/entry

The issues here are for the demos and tools on this site only.

**Comment by mglrahul** [comment]
Thanks
