### ISSUE TITLE
Query explorer will not load

### ISSUE THREAD

**Issue by csutera** [googleanalytics/ga-dev-tools#185]
Hello, 

I am signed into my google account which has a GA project. The query explorer will not load; I get the blue loading bar indefinitely. Also, seemingly related, when I try to query the Core Reporting API through R i get this error:
Error: lexical error: invalid char in json text.
                                       <HTML><HEAD>  <TITLE>Access Den
                     (right here) ------^

It has been a few weeks since I pulled any data. At that time everything was working properly. Are these issues related? Can you help me troubleshoot?

**Comment by philipwalton** [comment]
Those issues don't seem related.

Are you seeing any errors logged to the JavaScript console in your browser?

**Comment by csutera** [comment]
Thank you, Phillip Walton. Bringing up the JavaScript console revealed that my connection through our intranet prevented the query tool from loading. Being connected to the intranet was also creating the access denied error when querying the API. I disconnected and successfully queried the API and used the query explorer tool. 

It is surprising that after loading the query tool once while disconnected from our intranet I can access it again while connected.

Thanks for leading me to the JavaScript console.

**Comment by csutera** [comment]
Has Google recently changed its http requirements for connecting to the query tool? I did not have this same problem in the past while using the same connection.

**Comment by philipwalton** [comment]
Nothing has changed. This entire site has been `https:`-only since it was first launched.
