### ISSUE TITLE
Adding a filter to Google analytics Active users 

### ISSUE THREAD

**Issue by remyagss** [googleanalytics/ga-dev-tools#194]
Hi, I want to filter the active user based on the page type.I tried the following code, but it is not working, 

> <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>

<script src="https://ga-dev-tools.appspot.com/public/javascript/embed-api/components/view-selector2.js"></script>

<script src="https://ga-dev-tools.appspot.com/public/javascript/embed-api/components/date-range-selector.js"></script>

<script src='https://ga-dev-tools.appspot.com/public/javascript/embed-api/components/active-users.js'></script>

> var activeUsers =  new gapi.analytics.ext.ActiveUsers({
    'query': { 
  'filters': 'rt:pageTitle=@Contact' 
 },
     'container': 'active-users-container',
     pollingInterval: 10
  });

> viewSelector.on('viewChange', function(data) {
    var title = document.getElementById('view-name');
    title.innerHTML = data.property.name + ' (' + data.view.name + ')';
    // Start tracking active users for this view.
    activeUsers.set(data).execute();
  });

Can you please suggest me a method to do this?

**Comment by remyagss** [comment]
I am using the following js files

> <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>


<script src="https://ga-dev-tools.appspot.com/public/javascript/embed-api/components/view-selector2.js"></script>


<script src="https://ga-dev-tools.appspot.com/public/javascript/embed-api/components/date-range-selector.js"></script>


<script src='https://ga-dev-tools.appspot.com/public/javascript/embed-api/components/active-users.js'></script>

**Comment by philipwalton** [comment]
The [`ActiveUsers`](https://github.com/googleanalytics/ga-dev-tools/blob/16.2.1/src/javascript/embed-api/components/active-users.js) component used in the demo doesn't support query parameters. You could modify it, though, to support your use case.
