### ISSUE TITLE
platform.js no longer loading analytics?

### ISSUE THREAD

**Issue by bentiffany** [googleanalytics/ga-dev-tools#195]
The [Embed API snippet](https://github.com/googleanalytics/ga-dev-tools/blob/master/templates/embed-api/code/_snippet.js) that is used everywhere on this site and in the developer documentation, does not work for me in Chrome on my own site. I receive an error message in the console, `Uncaught TypeError: g.load is not a function`. If I inspect the `window.gapi` object, it identifies itself as `Object {plusone: Object}` and lacks a method called `load`.
However, if I change the url from:
https://apis.google.com/js/platform.js
to the url [found here](https://developers.google.com/analytics/devguides/reporting/core/v3/quickstart/web-js#setup) among other places:
https://apis.google.com/js/client.js
everything works as expected. Am I missing something? How come the ga-dev-tools site still works with the old url, even though mine only works with the new one?

**Comment by pjsg** [comment]
I needed to allow Google+ to load some javascript (in Ghostery) to overcome this problem....

**Comment by philipwalton** [comment]
@bentiffany is this still a problem? Can you confirm whether or not it's an extension blocking a request?

**Comment by bentiffany** [comment]
@philipwalton It is still a problem, but it's directly related to the Ghostery extension running in my browser. I think it's much cleaner to load the client.js rather than platform.js–because then you can load exactly which libraries you want without having the plusone sdk foisted upon you. I think it would also be advantageous to switch the documentation for the analytics library to load from client.js because users like myself who run Ghostery will have a degraded analytics sdk experience if platform.js is blocked.

**Comment by philipwalton** [comment]
Thanks @bentiffany, I'll follow-up internally and see if we can get the Embed API documentation updated or if there was a specific reason they chose platform over client.

Though, as you point out, using client seems to work just fine...

**Comment by diminishedprime** [comment]
This issue has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.
