### ISSUE TITLE
googleanalytics error for ga build and ga not found

### ISSUE THREAD

**Issue by venoodkhatuva12** [googleanalytics/ga-dev-tools#196]
I tried installing it with root user but its giving error
npm ERR! Linux 4.4.10-22.54.amzn1.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! ga-dev-tools@ build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ga-dev-tools@ build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ga-dev-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ga-dev-tools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ga-dev-tools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/ga-dev-tools-master/npm-debug.log

even not able to check graphicmagics with root.

**Comment by philipwalton** [comment]
Sorry, but it's not clear from that message what error you're having. What you've pasted above is just a generic npm error output.

**Comment by venoodkhatuva12** [comment]
Hi sir,
I have done with the installation but not able to locate dev_appserver.py
file and want to know how to start the demo services .
Rest all have been installed without error.

**Comment by philipwalton** [comment]
The `dev_appserver.py` command comes with the [Google App Engine Python SDK](https://cloud.google.com/appengine/docs/python/tools/using-local-server).
