### ISSUE TITLE
Is this google analytics v3 api error?

### ISSUE THREAD

**Issue by tn841** [googleanalytics/ga-dev-tools#197]
I try embed api demo at start date = 2016-04-12, end date = 2016-05-30.
Result is looks like below.
![image](https://cloud.githubusercontent.com/assets/8401638/15666275/e4983026-274a-11e6-86f5-cd7eb25ee38f.png)
March data is overlap May data.
It had worked well in last several days, but now has error.

Another Capture.
![image](https://cloud.githubusercontent.com/assets/8401638/15666494/033bcd48-274c-11e6-8a9a-a2a1e436106b.png)

why is this?

**Comment by philipwalton** [comment]
Since I believe this is the same issue as: 
https://code.google.com/p/analytics-issues/issues/detail?id=975

I'm going to close this and keep the discussion over there, as it's the proper place to report bugs with core GA products.

Feel free to reopen if this is a different issue.
