### ISSUE TITLE
Query Reporting tool gives wierd results as compared to my GAPI tool

### ISSUE THREAD

**Issue by taherali03** [googleanalytics/ga-dev-tools#198]
Hello,

I was testing some queries with query explorer tool, but when I applied ga:month, ga:day and ga:date to dimensions, I found out the "date field" and the "month of the year" were not matching. 

For example date was : Mar 10, 2016,
for this date corresponding month of the year should be 03.
But it is showing 02 i dont know why.

Check the screenshot
<img width="856" alt="screen shot 2016-05-31 at 8 31 23 pm" src="https://cloud.githubusercontent.com/assets/19668649/15679235/b90bb60c-276e-11e6-8a1d-e2cc6781adcd.png">

**Comment by philipwalton** [comment]
Interesting, however, I cannot reproduce this issue with my own data. Are you still seeing the problem?

**Comment by philipwalton** [comment]
Closing due to lack of response.
