### ISSUE TITLE
Inconsistent API result over longer time period

### ISSUE THREAD

**Issue by sammusk** [googleanalytics/ga-dev-tools#205]
When I query the GA API using day by day results over a 180 day period, I start getting some individual results that are incorrect when compared to a much shorter period, e.g. 30 days. 

For instance - 6 month query:-

![image](https://cloud.githubusercontent.com/assets/20419490/16767013/32b9aea0-4835-11e6-8b9a-1da5d46e9725.png)

On 9th June the Transaction amount is showing as 1,801.94

![image](https://cloud.githubusercontent.com/assets/20419490/16767032/4f5447b4-4835-11e6-91fc-60b5d3169bfa.png)

Whereas using a single day query:

![image](https://cloud.githubusercontent.com/assets/20419490/16771385/3c484568-4848-11e6-8a59-29ab363ce6ba.png)

On 9th June the Transaction amount is showing as 2452.59, which is actually correct. Note also the sessions number is different as well!

Is there something I am doing wrong or can this be fixed asap please?

Thanks
Sam sam@sammusk.com

**Comment by sammusk** [comment]
Single day query :
![image](https://cloud.githubusercontent.com/assets/20419490/16767355/e6b088ba-4836-11e6-9786-6963af50c0df.png)

**Comment by philipwalton** [comment]
Does the first chart you showed contain sampled data?

If so, then that probably explains it. If not then this is likely an issue with the Core Reporting API and not an issue with the Query Explorer, so you should probably file a bug on the API issue tracker: https://code.google.com/p/analytics-issues/issues/entry

**Comment by sammusk** [comment]
Thanks Philip,

No, does not contain sampled data. 

Bug reported then, thank you !

**Comment by philipwalton** [comment]
No problem!

For anyone else looking, the issue is here:
https://code.google.com/p/analytics-issues/issues/detail?id=1023
