### ISSUE TITLE
got an issue when run npm install

### ISSUE THREAD

**Issue by fuufuuf** [googleanalytics/ga-dev-tools#207]
i try to install this tool on Linux. But when I run npm install I got following error

npm http 404 https://registry.npmjs.org/javascript-api-utils
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/lib/node_modules/npm/lib/cache.js:708:24)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.10.0-123.9.3.el7.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /root/ga-dev-tools
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! type called_on_non_object
npm http 304 https://registry.npmjs.org/svg4everybody
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/ga-dev-tools/npm-debug.log
npm ERR! not ok code 0

**Comment by philipwalton** [comment]
I'm not sure there's enough here to go on. Can you give more details? What's in `npm-debug.log`?

**Comment by philipwalton** [comment]
Closing due to lack of response.
