### ISSUE TITLE
Founded an issue with ui

### ISSUE THREAD

**Issue by graffymichal** [googleanalytics/ga-dev-tools#209]
When you are on https://ga-dev-tools.appspot.com/query-explorer/ and in your request you have a long url. the metrics values are not displaying. 
![image](https://cloud.githubusercontent.com/assets/10302655/17207535/b6b4a8a6-54bd-11e6-8ed3-51858fe46370.png)

**Comment by philipwalton** [comment]
There is a horizontal scroll bar at the bottom, so you can scroll to the right to see the metrics in situations where you have long, unbreakable text (like in your example).

That being said, I'll look into updating the styles so reports with long strings of unbreakable text (like URLs) display better in the Query Explorer.

**Comment by philipwalton** [comment]
Fixed via 901fb2415a60d1a789540b23fc0bcf6615e21331.
