### ISSUE TITLE
Hit-Builder hit not registered at GA realtime view

### ISSUE THREAD

**Issue by MaartenW** [googleanalytics/ga-dev-tools#210]
After validating a hit in the Hit Builder it says:
`You can also send the hit to Google Analytics and watch it in action in the Real Time view.`
But when I try by clicking the **Send hit to Google Analytics** button, nothing happens in the real-time view of Google Analytics.

**Comment by philipwalton** [comment]
This is working for me. The most likely explanation is you're either:

* looking at the wrong view
* you have a view filter that's preventing the hit from showing up
* you're sending a hit type that the Real Time view doesn't display (like an exception, social, or timing hit).

**Comment by burhandodhy** [comment]
Facing same issue  :(

**Comment by philipwalton** [comment]
You're going to need to provide more information. I can't fix the problem if I can reproduce it.
