### ISSUE TITLE
what is the view ID that I need to replace?

### ISSUE THREAD

**Issue by kimkong** [googleanalytics/ga-dev-tools#212]
trying to follow https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/

and there is a reference to replacing the ids as follows but what ID is this referencing? Is this referencing the Googly Analytics GA-account-id?

      'ids': 'ga:100367422', // <-- Replace with the ids value for your view.

**Comment by philipwalton** [comment]
You can use the [account explorer](https://ga-dev-tools.appspot.com/account-explorer/) to find your view ID.
