### ISSUE TITLE
How to send report automatic to Email

### ISSUE THREAD

**Issue by thanhansoft** [googleanalytics/ga-dev-tools#217]
Hi,
I want to send report to Email automatic

**Comment by 1987yama3** [comment]
Hi @thanhansoft 

These issues are not for asking questions. 
Questions about how to use Google Analytics, please see official support site
or use the Google Analytics Community.

**Google Analytics Community**
https://www.en.advertisercommunity.com/t5/Google-Analytics/ct-p/Google_Analytics

**Official support site**
https://support.google.com/analytics/
