### ISSUE TITLE
Feature request: Filter dimensions and metrics as you type

### ISSUE THREAD

**Issue by proletm** [googleanalytics/ga-dev-tools#22]
It will be great to be able to start typing a dimension or metric in the input fields in the query explorer and the list to be filtered to the items in the list that match the typed string. 

For example if I type "product" i should be able to see:
ga:productName
ga:productSku
etc.

Right now if you do not remember exactly what the dimension/metric you are looking for is you have to look through all the entries. 

It will be a great enhancement to an already awesome tool :)

**Comment by philipwalton** [comment]
This will be added in #35.
