### ISSUE TITLE
`npm install` resulted in error

### ISSUE THREAD

**Issue by abhishekkunnath** [googleanalytics/ga-dev-tools#220]
> Ubuntu 16.04 LTS
> Node version 4.2.6
> Python version 2.7.12
> pip version 8.1.2

All the steps worked till `npm install` which resulted in error

```
[15:54:16] Requiring external module babel-register
[15:54:28] Using gulpfile ~/ga-dev-tools/gulpfile.babel.js
[15:54:28] Starting 'javascript:webpack'...
[15:54:28] Starting 'javascript:embed-api-components'...
[15:54:28] Starting 'css'...
[15:54:28] Starting 'images'...
[15:54:28] Starting 'json'...
[15:54:28] Finished 'json' after 6.89 ms
[15:54:28] Starting 'serve'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn dev_appserver.py ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! ga-dev-tools@ start: `gulp watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ga-dev-tools@ start script 'gulp watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ga-dev-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ga-dev-tools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ga-dev-tools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gizmeon/ga-dev-tools/npm-debug.log
```

Here is the log file `ga-dev-tools/npm-debug.log`

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
> 2 info using npm@3.5.2
> 3 info using node@v4.2.6
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle ga-dev-tools@~prestart: ga-dev-tools@
> 6 silly lifecycle ga-dev-tools@~prestart: no script for prestart, continuing
> 7 info lifecycle ga-dev-tools@~start: ga-dev-tools@
> 8 verbose lifecycle ga-dev-tools@~start: unsafe-perm in lifecycle true
> 9 verbose lifecycle ga-dev-tools@~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/gizmeon/ga-dev-tools/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> 10 verbose lifecycle ga-dev-tools@~start: CWD: /home/gizmeon/ga-dev-tools
> 11 silly lifecycle ga-dev-tools@~start: Args: [ '-c', 'gulp watch' ]
> 12 silly lifecycle ga-dev-tools@~start: Returned: code: 1  signal: null
> 13 info lifecycle ga-dev-tools@~start: Failed to exec start script
> 14 verbose stack Error: ga-dev-tools@ start: `gulp watch`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at EventEmitter.emit (events.js:172:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at ChildProcess.emit (events.js:172:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:821:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 15 verbose pkgid ga-dev-tools@
> 16 verbose cwd /home/gizmeon/ga-dev-tools
> 17 error Linux 4.4.0-34-generic
> 18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> 19 error node v4.2.6
> 20 error npm  v3.5.2
> 21 error code ELIFECYCLE
> 22 error ga-dev-tools@ start: `gulp watch`
> 22 error Exit status 1
> 23 error Failed at the ga-dev-tools@ start script 'gulp watch'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the ga-dev-tools package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     gulp watch
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs ga-dev-tools
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls ga-dev-tools
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by philipwalton** [comment]
Is `dev_appserver.py` in your path?

**Comment by philipwalton** [comment]
Closing due to lack of response. My comment in https://github.com/googleanalytics/ga-dev-tools/issues/220#issuecomment-244140884 should solve this.

**Comment by A-baoYang** [comment]
I have the issue, may I ask that how should I get `dev_appserver.py`?
Is it generated from Google Cloud SDK?
And after I get that, where should I place in the whole `ga-dev-tools`?
directly put under `ga-dev-tools/` ?
