### ISSUE TITLE
Page gets stuck on account explorer

### ISSUE THREAD

**Issue by Valindo** [googleanalytics/ga-dev-tools#222]
![screen shot 2016-09-07 at 3 40 43 pm](https://cloud.githubusercontent.com/assets/5938336/18308322/a79e51b8-7511-11e6-9ad5-12e0a6d34077.png)

Gets stuck here, and there is a console error.

**Comment by philipwalton** [comment]
I believe the reason is because you don't have any Google Analytics accounts.

An actual error message is probably worth adding.

**Comment by Valindo** [comment]
Thank you, sorry for the trouble.

*Valindo Godinho*
Co-founder & CTO
Plugzee <http://www.plugzee.com/>/Wafer OÜ
www.plugzee.com
