### ISSUE TITLE
Query Explorer: Download button not working

### ISSUE THREAD

**Issue by ssssteve** [googleanalytics/ga-dev-tools#224]
The Query Explorer's "Download Results as TSV" button no longer seems to be working, although it correctly shows the pointer there's no action being carried out on click. We use the Query Explorer quite extensively (it's a great tool btw!) but the issue appears to have emerged this morning.

**Comment by Cyborygmos** [comment]
Confirmed.  The "Download Results as TSV" button is unresponsive.  For us, the issue appeared mid-morning yesterday, and is present across all browsers, OSes, etc.

**Comment by philipwalton** [comment]
Thanks for reporting. This should be fixed now. Let me know if you're still experiencing the issue.

**Comment by ssssteve** [comment]
Yes, that's fixed it, thanks for the rapid response.
