### ISSUE TITLE
Require fields of Campaign URL Builder tool

### ISSUE THREAD

**Issue by 1987yama3** [googleanalytics/ga-dev-tools#225]
Hi

I used to try Campaign URL Builder tools. I think that the Campaign Medium and Campaign Name fields are required. Besides, in [legacy URL Builder](https://support.google.com/analytics/answer/1033867?hl=en), they are required fields.

The Campaign Medium and Campaign Name were changed to NON required fields?

Thanks, Ryota.

**Comment by philipwalton** [comment]
Yes, those fields are not actually required.

It certainly doesn't hurt to have them, but tracking will still work without them. You can try a URL without the name and source fields, and you'll notice it'll still show up in your reports. Those dimensions will be reported as "(not set)".
