### ISSUE TITLE
Feature request: Sort dimensions and metrics alphabetically

### ISSUE THREAD

**Issue by proletm** [googleanalytics/ga-dev-tools#23]
It will be great to have functionality similar to Google Analytics UI where you can choose to see dimensions/metrics either grouped in their sections or alphabetically. See attached example from Google Analytics Dimensions in custom reports
![image](https://cloud.githubusercontent.com/assets/10093514/5325672/5e238328-7ca7-11e4-994f-1d922b5957cc.png)

**Comment by philipwalton** [comment]
Do you think this would still be helpful if your suggestion in https://github.com/googleanalytics/ga-dev-tools/issues/22 were implemented?

**Comment by proletm** [comment]
I think for me either one will work (provided the sort as you type in the above interface is there). This interface actually allows both view by category, alphabetical or sort as you type, which might be more helpful for people who are not as familiar with the dimensions and metrics. I think with the above interface Google actually did a great job allowing flexibility in finding the appropriate dimension for both beginners and advanced users.

And sorry I entered this suggestion, I probably should have modified #22 as both kind of arrive at the same result.

**Comment by philipwalton** [comment]
It's fine. I asked because I'm planning on implementing #22, but at this point I don't plan on implementing alphabetical sorting. I wanted to see if you agreed that #22 would be good enough, and it sounds like you do.
