### ISSUE TITLE
can't connect to query explorer

### ISSUE THREAD

**Issue by yannix50** [googleanalytics/ga-dev-tools#234]
Hi,

I want to use query exporer for analytics but when I open, nothing work.

Thanks

**Comment by philipwalton** [comment]
Please be specific about exactly what you did and exactly what didn't work.

**Comment by lp-lima** [comment]
Same here. The page shows the load bar, and nothing more. It works on another PC on my enterprise, but in the mine not. Signed out of Chrome users, private tab, reboot on PC... nothing makes it work. It just remains loading, eternally. What could this be?

**Comment by lp-lima** [comment]
![image](https://cloud.githubusercontent.com/assets/22321989/19269471/289a9986-8f91-11e6-806b-fdce4d5b7c90.png)

**Comment by lp-lima** [comment]
Same here. The shows the load bar, and nothing else. Tried signing out of Chrome user, private tab, reboot on PC... Nothing makes it work. On another PC in this same net, it works normally. But in the mine not. What could this be? It was working till yesterder here.


![image](https://cloud.githubusercontent.com/assets/22321989/19269543/8a5778ec-8f91-11e6-8cda-1e6b05241328.png)

**Comment by philipwalton** [comment]
Are you seeing any JavaScript errors in the developer console?

**Comment by philipwalton** [comment]
Closing due to lack of response. Feel free to comment if you're still having a problem.
