### ISSUE TITLE
Unique Events are not currently available for reporting in Query Explorer

### ISSUE THREAD

**Issue by Cyborygmos** [googleanalytics/ga-dev-tools#237]
The unique events metric (ga:uniqueEvents) is not currently available within Query Explorer.  It does not appear in the autopopulate menu, and typing it in manually doesn't work either, unfortunately.

Total events (ga:totalEvents) is still available and works fine.

**Comment by mcohoon** [comment]
The metric `ga:uniqueEvents` is under going a transition as indicated in the [Analytics Rerporting API change log](https://developers.google.com/analytics/devguides/reporting/core/v4/changelog#event_tracking), and as such it is technically *"deprecated"*. You can currently use the metric [`ga:uniqueDimensionCombinations`](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=session&jump=ga_uniquedimensioncombinations) to get the same values that `ga:uniqueEvents` would return. Eventually `ga:uniqueEvents` will be available with the new definition as described in the [Unique Events and Unique Dimension Combinations help docs](https://support.google.com/analytics/answer/7084499). 

As the [Query Explorer](https://ga-dev-tools.appspot.com/query-explorer/) uses the [Metadata API](https://www.googleapis.com/analytics/v3/metadata/ga/columns?pp=1) to get the list of only available [public](https://github.com/googleanalytics/ga-dev-tools/blob/7ef379173f1c1c73fc1eee5966a93c5c9d2a634f/src/javascript/query-explorer/actions/select2-options.js#L194) dimensions and metrics, `ga:uniqueEvents` does not show up as an available metric from the metric picker.

**Comment by Cyborygmos** [comment]
Thanks for the response, that makes sense.
