### ISSUE TITLE
Customised Campaign - URL Builder - not working

### ISSUE THREAD

**Issue by irisskrami** [googleanalytics/ga-dev-tools#239]
Campaigns that where correctly tracked last week as: 
- source: LinkedIn
- medium: cpc

are now not working properly without any change. 

Taking the Analytics ID from a new lead coming from this source/medium today, it can be seen as coming from (direct) / (none). 

No changes were made to the URL. 
The only change made to the landing page is the insertion of a Remarketing tag. 

Any ideas of where the problem might be?
Thanks

**Comment by philipwalton** [comment]
These issues are for reporting bugs with the demos and tools on this site. For product support please visit https://support.google.com/analytics.

**Comment by irisskrami** [comment]
Hi Philip, 

Thanks for commenting.
Precisely for that. 
Google is saying they cannot help with this. It is not under their responsibility. 

Might there be an issue with the URL builder?

**Comment by philipwalton** [comment]
> Might there be an issue with the URL builder?

You said the generated URL was working last week. That means it's not a problem with the URL Builder.

**Comment by irisskrami** [comment]
So, are you saying that it's a problem with Analytics? 

Thanks,

**Comment by philipwalton** [comment]
I'm saying these Github issues are not the right place to be asking that question. These issues are for reporting bugs with the tools on this site only. Please use the link I provided to find the right support channel for your question.
