### ISSUE TITLE
Weird data

### ISSUE THREAD

**Issue by CarlLee1983** [googleanalytics/ga-dev-tools#24]
Hi,
I had a weird data on my website.

ids:ga:31871614
metrics:ga:users
filters:ga:hostname==www.jajen90.com.tw
start-date:2014-11-01
end-date:2014-11-30

Get Data is 3.

ids:ga:31871614
metrics:ga:users
filters:ga:hostname==www.jajen90.com.tw
start-date:2014-11-07
end-date:2014-11-30

Get Data is 4.

Please tell me why.
Thanks for your help.

**Comment by philipwalton** [comment]
I'm going to close this issue due to its age. If you're still experiencing a problem, feel free to open up a new issue.
