### ISSUE TITLE
GA Query Explorer

### ISSUE THREAD

**Issue by ejonathan** [googleanalytics/ga-dev-tools#247]
The query explorer has been returning nonsensical results for the past week or so. It is returning many duplicate numbers for counts of events/users/sessions, for example reporting that 22 users had viewed every page listed, over 22 sessions each. This is not what is returned for the same parameters in the GA UI. I have witnessed this across multiple GA accounts/domains.

**Comment by philipwalton** [comment]
Without more details there's no way to take action on this report.
