### ISSUE TITLE
Feature Request: Add option to include view ID in "Share Report"

### ISSUE THREAD

**Issue by proletm** [googleanalytics/ga-dev-tools#25]
It looks like the Share report feature intentionally does not include the view, but it will be very helpful to have a check box to actually include that as part of the URL. I share configuration often with people and it seems like an extra step to have to specify separately which view the configuration applies to.

**Comment by philipwalton** [comment]
Add in https://github.com/googleanalytics/ga-dev-tools/pull/47.
