### ISSUE TITLE
Error 401: Cannot Authenticate Google Analytics Embed API?

### ISSUE THREAD

**Issue by KevinMind** [googleanalytics/ga-dev-tools#258]
My understanding is that cid is an integer allowing GA to detect returning visitors... 

The embed code for the [basic dashboard](https://ga-dev-tools.appspot.com/embed-api/basic-dashboard/) tells me to...

`clientid: 'REPLACE WITH YOUR CLIENT ID'
`

If I put my tracking ID, none of the widgets load.. If I leave it as is, I get a 401 error

Any ideas?

**Comment by philipwalton** [comment]
The client ID in this case is different from the client ID tracked by GA (yes, I see how it could be confusing).

Read the Embed API documentation here to find out how to get a client ID for use with the Embed API: https://developers.google.com/analytics/devguides/reporting/embed/v1/getting-started#client-id
