### ISSUE TITLE
Moment.js date formats broken for YOY in third party visualizations

### ISSUE THREAD

**Issue by laurenancona** [googleanalytics/ga-dev-tools#26]
It seems the changing of the year has broken the date formatting to calculate the year-over-year example in the third party visualizations example (https://ga-dev-tools.appspot.com/embed-api/third-party-visualizations/). I'm reviewing Moment.js docs to see if a different format may fix, but wanted to log the bug in the meantime.

The error is caused by end date preceding start date, visible in the hosted examples.
Many thanks for the work on this.

**Comment by philipwalton** [comment]
Thanks! Fixed via 8e1d340eb780312ef4980d98f5e6f196f95ef758.

**Comment by laurenancona** [comment]
Thanks!
