### ISSUE TITLE
Add use Hash Option to URL Builder

### ISSUE THREAD

**Issue by 1987yama3** [googleanalytics/ga-dev-tools#263]
I think it would be better to have an option to build as a hash parameter.
Because, in the adveriser community( [Japanese](https://www.ja.advertisercommunity.com/), [English](https://www.en.advertisercommunity.com/) ), there is a question in the case that the server side redirects are out of parameters and the campaign can not be measured. Using hash parameter is convenient because the parameter do not disappear in server side redirects. 

If there is no problem, I can implement to the feature. 

Thanks.

**Comment by philipwalton** [comment]
This option already exists. Below the generated URL, there's a checkbox next to a label that says:

> Set the campaign parameters in the fragment portion of the URL (not recommended).
