### ISSUE TITLE
Typo on Google URL builder page

### ISSUE THREAD

**Issue by mlgilbert** [googleanalytics/ga-dev-tools#264]
On this page:
https://ga-dev-tools.appspot.com/campaign-url-builder/

"required" is misspelled in the alert box near bottom of page.

![google-typo-url-builder](https://cloud.githubusercontent.com/assets/1382545/21857349/1da9ffb2-d7f3-11e6-9bda-192552c53f77.jpg)

**Comment by philipwalton** [comment]
Thanks! This has been fixed.
