### ISSUE TITLE
Javascript error when using Hit Builder on Chrome

### ISSUE THREAD

**Issue by yaykyle** [googleanalytics/ga-dev-tools#266]
When trying to load this page, it fails on Chrome:
https://ga-dev-tools.appspot.com/hit-builder/

It works on Safari.

Here is the console error.
![image](https://cloud.githubusercontent.com/assets/4280/22154873/3bd522dc-defb-11e6-952b-c4d92a8d669c.png)

**Comment by philipwalton** [comment]
I'm not sure about that error. The Hit Builder doesn't use sessionStorage, so perhaps the error is coming from one of your extensions?

Can you try disabling all your extensions and see if you still get the error?

**Comment by yaykyle** [comment]
I disabled all my extensions but it is still appearing. Seems to be something in my Google accounts, because if I add a new Person to Chrome (Using the "People" menu) the problem does not appear.

It's trying to load something from https://ssl.gstatic.com/accounts/o/XXXX-idpiframe.js

I'm going to close this out because it's probably unique to me. Thank you!

**Comment by yaykyle** [comment]
Aha! It is the "block third-party cookies" setting!

**Comment by philipwalton** [comment]
Glad you got it figured out!
