### ISSUE TITLE
request composer / histogram fails

### ISSUE THREAD

**Issue by belm0** [googleanalytics/ga-dev-tools#267]
Request button remains in "Loading..." state indefinitely.  Console error:

```
request-composer.js:17 Uncaught (in promise) TypeError: (intermediate value)[e] is not a function
    at t.u.initializeChart (request-composer.js:17)
    at t.u.componentDidMount (request-composer.js:17)
    at r.notifyAll (app.js:5)
    at r.close (app.js:12)
    at r.closeAll (app.js:2)
    at r.perform (app.js:2)
    at o.perform (app.js:2)
    at o.perform (app.js:1)
    at Object.C [as flushBatchedUpdates] (app.js:1)
    at r.closeAll (app.js:2)
```

I'm using a request exactly the same as the documented demo:

```
{
  "reportRequests": [
    {
      "viewId": "123841229",
      "samplingLevel": "DEFAULT",
      "dateRanges": [
        {
          "startDate": "2017-01-29",
          "endDate": "yesterday"
        }
      ],
      "metrics": [
        {
          "expression": "ga:sessions"
        }
      ],
      "dimensions": [
        {
          "name": "ga:sessionCount",
          "histogramBuckets": [
            "1",
            "10",
            "100",
            "200"
          ]
        }
      ],
      "orderBys": [
        {
          "fieldName": "ga:sessionCount",
          "orderType": "HISTOGRAM_BUCKET",
          "sortOrder": "ASCENDING"
        }
      ]
    }
  ]
}
```

Pivot and cohort requests work, only histogram is failing.

**Comment by philipwalton** [comment]
@mcohoon PTAL.

**Comment by mcohoon** [comment]
This appears to be an incompatibility between [react-chart and chart.js 2.X](https://github.com/reactjs/react-chartjs/issues). I have seen some working branches that we might switch to in the mean time:

    "react-chartjs": "git://github.com/venari/react-chartjs.git#chartjs-v2",

otherwise if we aren't reliant on any features in chart.js 2.X we could down grade to a stable 1.1.X version.

**Comment by philipwalton** [comment]
Cool, I reverted chartjs to a 1.X version for now since the Request Composer is the only tool using it. Once v2 of `react-chartjs` ships we can upgrade again.
