### ISSUE TITLE
Error: Command failed: gm identify: No decode delegate for this image format (ga-dev-tools/gmGjNd0s)

### ISSUE THREAD

**Issue by lucifer7** [googleanalytics/ga-dev-tools#269]
The error reported while running **npm start** when I try to run this site following your guidance . 
This vm cannot connect to google.com directly due to network, I am not sure whether that matters.

Version:
> CentOS Linux release 7.2.1511 (Core)
> node v6.9.4
> npm  v3.10.10
> Python 2.7.5
> GraphicsMagick 1.3.25
> Google Cloud SDK 143.0.0
> app-engine-python 1.9.50

```
[16:25:35] Starting 'serve'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error in plugin 'gulp-gm'
Error: Command failed: gm identify: No decode delegate for this image format (/usr/local/google-analytics/ga-dev-tools/gmGjNd0s).
gm identify: Request did not return an image.

    at finish (/usr/local/google-analytics/ga-dev-tools/node_modules/gulp-gm/index.js:40:21)
    at gm.<anonymous> (/usr/local/google-analytics/ga-dev-tools/node_modules/async/lib/async.js:485:30)
    at emitMany (events.js:127:13)
    at gm.emit (events.js:201:7)
    at gm.<anonymous> (/usr/local/google-analytics/ga-dev-tools/node_modules/gm/lib/getters.js:70:16)
    at cb (/usr/local/google-analytics/ga-dev-tools/node_modules/gm/lib/command.js:322:16)
    at ChildProcess.onExit (/usr/local/google-analytics/ga-dev-tools/node_modules/gm/lib/command.js:305:9)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)

npm ERR! Linux 3.10.0-327.36.3.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ga-dev-tools@ start: `gulp watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ga-dev-tools@ start script 'gulp watch'.

```

**Comment by philipwalton** [comment]
Looks like it's not finding  the `gm` binary in your `PATH`. What happens when you run `which gm`?

**Comment by lucifer7** [comment]
@philipwalton 
The output is:
```
# which gm
/usr/local/bin/gm
```
I guess it's due to missing image, but no error reported during installation. Maybe I should repeat the installation procedure to see if things would go right.

**Comment by gmcmenimen** [comment]
I am getting the same error on my Mac

<pre><code>events.js:160
      throw er; // Unhandled 'error' event
      ^
Error in plugin 'gulp-gm'
Error: Command failed: gm identify: No decode delegate for this image format (/var/folders/kn/3v6595596kj9fnp32d58y_vc0000gn/T/gmiCt6iP).
gm identify: Request did not return an image.</code></pre>

 and even after trying

<pre><code>./configure CC=clang</br>
make</br>
make install</br>
</code></pre>

And I also ran

<pre><code> which gm </br>
/usr/local/bin/gm
</code></pre>

**Comment by Lucretiel** [comment]
This issue appears to be a missing delegate in gm. I'm not especially familiar with how gm works, but I'll do my best.

Can you run this command, to see which delegates are currently installed?

    convert -list configure | grep '^DELEGATES'

**Comment by vijaykumarchettiar** [comment]
i am too facing this issue. any solution or patch

**Comment by diminishedprime** [comment]
This issue has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.
