### ISSUE TITLE
IP Address Regular Expression Tools

### ISSUE THREAD

**Issue by 1987yama3** [googleanalytics/ga-dev-tools#271]
Previously, I think that there was a Regular Expression Tool for IP Address on the Google Analytics Support Page. It seems that it has been deleted now.

That tool was very convenient.

Therefore, I want this to be available again with this application.

The same thing can be done by using tools of other sites, but I think that there is significance to be offered in this application that provides tools for developers of Google Analytics.

Thanks

**Comment by philipwalton** [comment]
Thanks for the suggestion. Since there are lot of tools online to help in writing regular expressions, it's unlikely we'll be able to prioritize building something like this for Demos & Tools.

If someone wanted to submit a pull request, I'd be happy to consider it.
