### ISSUE TITLE
Core Reporting API returns false results with filter ga:socialNetwork!=(not set)

### ISSUE THREAD

**Issue by ETENTION** [googleanalytics/ga-dev-tools#272]
Hi

Core Reporting API returns false results that include value "(not set)" when filter **ga:socialNetwork!=(not set)** is applied.

However, in Query Explorer this filter works as planned. The only way I managed to get correct results also from Core Reporting API was to change the filter to **ga:socialNetwork!@(not set)**.
After that it returns corrects results which do not include "(not set)" value.

**Comment by philipwalton** [comment]
The Query Explorer uses the Core Reporting API, so it should never behave differently. Are you sure you don't have extra whitespace or something like that messing up your tests?

**Comment by philipwalton** [comment]
Closing since there was no response.
