### ISSUE TITLE
npm install 

### ISSUE THREAD

**Issue by rdesai7070** [googleanalytics/ga-dev-tools#273]
Getting this log on `npm start`

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\<user_name>\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.2.0
3 info using node@v6.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ga-dev-tools@~prestart: ga-dev-tools@
6 silly lifecycle ga-dev-tools@~prestart: no script for prestart, continuing
7 info lifecycle ga-dev-tools@~start: ga-dev-tools@
8 verbose lifecycle ga-dev-tools@~start: unsafe-perm in lifecycle true
9 verbose lifecycle ga-dev-tools@~start: PATH: <path>
10 verbose lifecycle ga-dev-tools@~start: CWD: C:\Users\<user_name>\ga-dev-tools
11 silly lifecycle ga-dev-tools@~start: Args: [ '/d /s /c', 'gulp watch' ]
12 silly lifecycle ga-dev-tools@~start: Returned: code: 1  signal: null
13 info lifecycle ga-dev-tools@~start: Failed to exec start script
14 verbose stack Error: ga-dev-tools@ start: `gulp watch`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\<user_name>\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\<user_name>\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ga-dev-tools@
16 verbose cwd C:\Users\<user_name>\ga-dev-tools
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\<user_name>\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.4
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error ga-dev-tools@ start: `gulp watch`
23 error Exit status 1
24 error Failed at the ga-dev-tools@ start script 'gulp watch'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the ga-dev-tools package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     gulp watch
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs ga-dev-tools
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls ga-dev-tools
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by philipwalton** [comment]
It looks like you're running this on Windows, which I'm unable to test or support. If the tools I use to build the site don't support Windows, there's unfortunately not much I can do about it.
