### ISSUE TITLE
Run on server access from PC

### ISSUE THREAD

**Issue by keithschm** [googleanalytics/ga-dev-tools#274]
Looks like this on works if accessing from localhost. I have it installed on my server with no GUI. Can I see it from another PC?  I tried IP:8080 but i just get ERR_EMPTY_RESPONSE

**Comment by philipwalton** [comment]
I'm not sure what isn't working. Can you please be specific?

**Comment by keithschm** [comment]
I can run the server no problem but it can only be seen by my localhost. If
I try to access it from a different ip address it just shows
ERR_EMPTY_RESPONSE

**Comment by philipwalton** [comment]
What shows `ERR_EMPTY_RESPONSE`? The browser? The terminal? The JavaScript console? You're still going to have to be more specific.

Have you created your own project in the developer console as described here?
https://developers.google.com/identity/sign-in/web/devconsole-project

**Comment by keithschm** [comment]
Sorry, After starting the service on my server it works on that server. If
I try to access that server from my desktop which is not localhost and has
a different ip the browser gives that error. Is it because of how
the dev_appserver.py is started?  in looking at the ports the server is
only listening to localhost. (tcp        0      0 *127.0.0.1:8080
<http://127.0.0.1:8080> *         0.0.0.0:*               LISTEN)

**Comment by philipwalton** [comment]
Where does the browser display that error? In the developer console or on the screen? Can you upload a screenshot of what you're seeing?

Also you didn't answer my pervious question about whether or not you created a project in the developer console. If you didn't, that's most likely the issue because you have to whitelist specific origins.

**Comment by keithschm** [comment]
yes I created a project in the developer console and I have white-listed
the IP with the PORT in the console.  It works from the server if I use
http://localhost:8080. But if I use my chrome browser on my PC
http://10.0.1.56:8080
 I get the error.

[image: Inline image 2]

**Comment by keithschm** [comment]
http://tinypic.com/r/z4unl/9

**Comment by philipwalton** [comment]
Ahh, that looks like a networking error and not something related to this tool. If you have an IT department, I'd bring it up with them.

**Comment by keithschm** [comment]
Thank you for the help. From what I can tell the Issue id that the Server
running on port 8080 which is the dev_appserver.py is only listening for
requests from localhost 127.0.0.1 where it needs to be 0.0.0.0*
Do you know which file is calling dev_appserver.py si I can add the switch
--admin_host=

**Comment by philipwalton** [comment]
Ahh, I think I understand what you're saying now. Sorry about that.

You can modify the host by passing the `--host` option to the `dev_appserver.py` binary. I think you can modify [this line of gulpfile.js](https://github.com/googleanalytics/ga-dev-tools/blob/master/gulpfile.babel.js#L285) as follows:


```js
devServer = spawn('dev_appserver.py', ['--host="XX.XX.XX.XX"', '.']);
```

**Comment by keithschm** [comment]
THANK YOU!!!!!! That was it   devServer = spawn('dev_appserver.py',
['--host=xxx.xxx.xxx.xxx','.']);

no double quotes.

Thank you very very much
