### ISSUE TITLE
Wrong data from Query Explorer?

### ISSUE THREAD

**Issue by PeterGolovatyi** [googleanalytics/ga-dev-tools#275]
A few days ago, I noticed that Query Explorer and add-on for Google Sheets gives me back data with zero values. But earlier there wasn't such problem. And, for example, when I make the same report in Google Analytics Custom Reports - there is no zero values and everything is ok.
![oops](https://cloud.githubusercontent.com/assets/20299486/23211737/297ff0e6-f90c-11e6-94ea-cbfcd7f4952d.PNG)

**Comment by philipwalton** [comment]
I'm not sure this is actually a bug, but either way it's behavior related to the Core Reporting API, so it should be reported on the [Google Analytics Developers Issue Tracker](https://issuetracker.google.com/issues?q=componentid:187400) rather than here.
