### ISSUE TITLE
Google has introduced ga:uniqueEventsTemporary metric

### ISSUE THREAD

**Issue by dsharvit** [googleanalytics/ga-dev-tools#276]
Hi,

Google has introduced ga:uniqueEventsTemporary metric while ga:uniqueEvents metric is being fixed (for at least 6 months). 

Can we add the new metric to the Query Explorer?

Documentation is in the changelog: https://developers.google.com/analytics/devguides/changelog

Thanks,
Daniel

**Comment by mcohoon** [comment]
The six month deprecation period will be over on [March 26, 2017](https://developers.google.com/analytics/devguides/changelog#event_tracking) soon after that `ga:uniqueEventsTemporary` will stop working and `ga:uniqueEvents` will take on the new definition. As `ga:uniqueEventsTemporary` is not present in the [Metadata API](https://developers.google.com/analytics/devguides/reporting/metadata/v3/), I would vote not to hard code the temporary metric into the query explorer only to have to remove it in a few weeks time.
