### ISSUE TITLE
campaign url builder - url string - parameter order does not match form order

### ISSUE THREAD

**Issue by tmyang144** [googleanalytics/ga-dev-tools#278]
Why does the campaign url builder show source, medium, campaign name, term, and content but in the "generate url" portion, it shows up in the utm parameter as source, campaign name, medium, term, and content (medium and campaign name are flip flopped)?
![campaign url builder screenshot](https://cloud.githubusercontent.com/assets/26389474/23868266/31f30ff4-07f5-11e7-9d02-de70b1abda97.JPG)

**Comment by philipwalton** [comment]
Order does not matter in URL parameters, so the way the result gets generated can be somewhat random. Either way, it doesn't matter and won't affect your reports.

**Comment by tmyang144** [comment]
I understand that order doesn't necessarily matter for tracking into google analytics but I send my marketing teams to this form and it doesn't make sense that the url string doesn't match the form. I get a lot of questions when I send them to this form. Is there no way you guys can keep this consistent?

**Comment by philipwalton** [comment]
This should be fixed now.

**Comment by tmyang144** [comment]
Awesome, thank you so much! Also, thanks for the quick responses!
