### ISSUE TITLE
about the utm campaign builder

### ISSUE THREAD

**Issue by hyz901214** [googleanalytics/ga-dev-tools#279]
I am Haran, i have a problem about ga-dev-tools.appspot.com i see the utm campaigh bulider, i think this should be wrong,url is:https://ga-dev-tools.appspot.com/campaign-url-builder/, in this tools just the source is requierd, and medium and campaign didn't required, this is wrong,because the channels reports is base on medium and source to distingish the channel，  and the Campaign depend on campaign parament,if you just required the source, that means, in channels reports,most chanel will distingish to Others, and Campaign cann't distingish, what do you think?

**Comment by philipwalton** [comment]
This concern has already been addressed in https://github.com/googleanalytics/ga-dev-tools/issues/235.
