### ISSUE TITLE
Sidebar menu issue IE Mobile 11

### ISSUE THREAD

**Issue by plfstr** [googleanalytics/ga-dev-tools#28]
.Site-sidebar jumps to right-hand side of viewport when expanded
![ga-menu-issue-1](https://cloud.githubusercontent.com/assets/1652953/5638997/3fd1e3c8-9607-11e4-9d60-f294bc307558.jpg)

**Comment by philipwalton** [comment]
Hmmm, I can't reproduce this error on my VM using IE 11 with Window Phone emulation mode turned on. Are you by any chance able to help debug?

**Comment by plfstr** [comment]
Hi @philipwalton, I made a reduced test case on CodePen (see http://codepen.io/plfstr/pen/emgvVy).

The 3D transform seems to cause the jump right. Using a 2d translate works as expected (tested on a Lumia Handset). Hope that helps.

**Comment by philipwalton** [comment]
cc: @gregwhitworth

Greg, is this helpful at all in determining why this happens on a real device but not in emulation mode?

**Comment by plfstr** [comment]
I did some searching for IE translate3d issues and it seems it doesnt play well with position: fixed which may be why this is happening (see issue here https://github.com/jakiestfu/Snap.js/issues/24). 

When `.is-expanded`, the menu is positioned ~260px from the left in portrait or landscape orientation in IE.

**Comment by philipwalton** [comment]
Interesting, does changing it to absolute work for you in your demo?

**Comment by plfstr** [comment]
No, sadly not. I think this comment is applicable, https://github.com/jakiestfu/Snap.js/issues/24#issuecomment-24360890. 
After transition occurs the menu seems to discard all positioning styles and applies the 260px right translate.

**Comment by philipwalton** [comment]
I'm going to close this due to inactivity. If anyone wants to reopen, feel free.
