### ISSUE TITLE
Charts disappearing if state changed in angularJS

### ISSUE THREAD

**Issue by rmshkmr** [googleanalytics/ga-dev-tools#282]
Hey, I'm Using angular-ui-router. Embed API charts loading without any problem. But if i change the state using angular-ui-router, charts disappearing. Can i get any solution??

**Comment by philipwalton** [comment]
This sounds like a problem with your angular code, as it's probably clearing out the container element when the URL changes. This is most likely not an Embed API issue.

**Comment by rmshkmr** [comment]
@philipwalton I'm reloading the particular page using $state.reload but its not showing. If i reload the browser it showing the charts. Thanks
