### ISSUE TITLE
Implemention Demo

### ISSUE THREAD

**Issue by BWalekar** [googleanalytics/ga-dev-tools#283]
Need to see how it can it be implemented.

Thanks.

**Comment by philipwalton** [comment]
What is "it"?

**Comment by BWalekar** [comment]
Want to Integrate Google Analytics in my web application. Is there any place where I can see the demo how to integrate?

**Comment by philipwalton** [comment]
This site is not really intended for asking implementation questions. All the developer documentation related to Google Analytics can be found here:
https://developers.google.com/analytics/

And if you have questions, go here to see the best place to ask them:
https://developers.google.com/analytics/help/
