### ISSUE TITLE
Campaign URL Builder Tool

### ISSUE THREAD

**Issue by erickmvargas0911** [googleanalytics/ga-dev-tools#286]
Whenever I click the link from Campaign URL Builder Tool, I get the error below:

This site can’t provide a secure connection
www.followuppower.net uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

Can you provide some direction on what the issue is?

**Comment by philipwalton** [comment]
You're going to have to provide more details. A link to that URL is not found anywhere on this site.

**Comment by philipwalton** [comment]
Closing due to lack of response.
