### ISSUE TITLE
Unable to load page

### ISSUE THREAD

**Issue by ssssteve** [googleanalytics/ga-dev-tools#297]
Hi,

We have a bank of 7 computers. On three of them we have no issues with Query Explorer. On the other four we cannot get Query Explorer to load; we authorise the account then get the blue bar permanently displayed. The Console shows the following:

```
Uncaught SyntaxError: Unexpected token *				(index):48
Uncaught SyntaxError: Unexpected token =				common.js:48270
Uncaught ReferenceError: webpackJsonp is not defined			index.js:1
Uncaught ReferenceError: webpackJsonp is not defined			query-explorer.js:1
```

We've not manage to repeat the issue on any of the computers which do not show the problem. All are accessing the site through https://ga-dev-tools.appspot.com/query-explorer/

All computers are on the same IP address; the problem is repeatable in Chrome, Chrome in Incognito mode and in Firefox and Opera (we'd never logged in to Google or Query Explorer in Opera). We've cleared site cookies on both working and non-working computers, and pop-ups and 3rd party cookies are enabled. 

Although the issue first appeared on our primary Google account, we've tried using different accounts, and all these computers have been using the Query Explorer regularly for many months. We have no problems with Google Analytics itself, and another tool using OAuth works fine. This problem first appeared two days ago. And yes, we've turned the computers off and on again! :-)

Any suggestions?

**Comment by philipwalton** [comment]
Is this still happening? I'm not sure why some would work and not others, so I assume it's just a temporary issue with the JavaScript the server is sending?

**Comment by ssssteve** [comment]
I can confirm that it's still an issue on the machines that it wasn't working on last week.

**Comment by philipwalton** [comment]
Are you still seeing this one?

> Uncaught SyntaxError: Unexpected token *

I pushed a change yesterday that should have fixed that.

**Comment by ssssteve** [comment]
Yes, we've just tried it and we're still getting that issue, after both a hard reset and via Incognito.

There's one other possibility; these machines have old versions of Chrome, it's administrator locked and won't upgrade, so it's possible that there's an incompatibility somewhere. I'll see if we can get them upgraded via our Tech Support.

**Comment by cartbinder** [comment]
Yes i also have old chrome version and it has same issue. Have tried on new version on another device, works fine..

**Comment by ssssteve** [comment]
I'll agree, I think we can also confirm that the old Chrome version was the issue. We've one machine we're still waiting for elevation to upgrade Chrome, but on the other machines that appears to have done the trick.
