### ISSUE TITLE
Campaign Builder: # instead of ?

### ISSUE THREAD

**Issue by marcelolaiz** [googleanalytics/ga-dev-tools#298]
Hi,

I've been using this tool for some time now. But recently, the links built include a # instead of a ? on the tagging.

Cool
https://www.sams.com.mx/Pantalla-LG--43-Pulgadas-LED-Full-HD-Smart-TV/99947?utm_source=MRM&utm_medium=email&utm_campaign=msi-170512&utm_term=home-clic-ciego&utm_content=msi-clic-ciego

Not cool
https://www.sams.com.mx/Pantalla-LG--43-Pulgadas-LED-Full-HD-Smart-TV/99947#utm_source=MRM&utm_medium=email&utm_campaign=msi-170512&utm_term=home-clic-ciego&utm_content=msi-clic-ciego

This is an issue because, despite I could change it manually, the Shorten Tool wouln't work for me at the same page. I would have to access the goo.gl site to end my task.
This could make a faulty user experience.

Thanks for your time and answers! I hope there's a solution for this soon :)

Marcelo

**Comment by 1310L** [comment]
Hi Marcelo,

may I ask you where to find the Campaign Builder?
The old link https://ga-dev-tools.appspot.com/campaign-url-builder/
 is not working since yesterday.

Unfortunately I can't help with your issue, I'm sorry. :(

Thank you :)
Lisa

**Comment by philipwalton** [comment]
@marcelolaiz make sure the check box labelled "Set the campaign parameters in the fragment portion of the URL (not recommended)." is not checked. It sounds like you checked that some how and didn't notice.

<img width="711" alt="screen shot 2017-05-12 at 4 47 17 pm" src="https://cloud.githubusercontent.com/assets/326742/26020411/e110a1c4-3732-11e7-8f78-881bcca1d07c.png">
