### ISSUE TITLE
Request for a demo of embed analytics with auto login

### ISSUE THREAD

**Issue by MorganLicorn** [googleanalytics/ga-dev-tools#30]
I'd be very much interested in a demonstration showing how to embed an analytics with an access_token generated preventing the "authorize" button. 
I've read many articles regarding this feature, but I can't manage to make it work otherwise than with a token generetad from the oAuth playground... 
Do you think that could be possible ?

**Comment by miturchin** [comment]
I would be extremely interested in this as well!

**Comment by robinbirr** [comment]
yes, that would interest me much too.

**Comment by philipwalton** [comment]
Thanks, this is definitely on our to-do list.

**Comment by kulander** [comment]
Same here, the auto login would be of so much help!

**Comment by philipwalton** [comment]
This has been added in [9.0.0](https://github.com/googleanalytics/ga-dev-tools/releases/tag/9.0.0).
