### ISSUE TITLE
Campaign-url-builder fields not loading

### ISSUE THREAD

**Issue by west-pole** [googleanalytics/ga-dev-tools#300]
Hi All,
https://ga-dev-tools.appspot.com/campaign-url-builder/ requests fields to be populated in order to generate link, however the fields are not loading. Could you advise if it's known issue and if there are plans to resolve it?

Thanks,
West-Pole

**Comment by philipwalton** [comment]
I don't know what you mean by "the fields are not loading". Can you please be more specific or provide screenshots to clarify?

**Comment by west-pole** [comment]
Hi Philip,
Thanks for coming back to me so quickly. 
These fields: **https://ga-dev-tools.appspot.com/campaign-url-builder/ requests fields to be populated in order to generate link, however the fields are not loading**. If you'll go to the link provided you'll see that there are no fields at all, ergo I can't provide screenshot of something that's missing. I highlighted the part that's asking to fill in fields marked with * for your convenience. 
Please don't hesitate to contact me if you have any further questions.

Thanks for looking into it,
West-Pole
![fields](https://cloud.githubusercontent.com/assets/11430837/26389746/5bd5a124-4053-11e7-80c5-29d2cbbc3ad3.JPG)

**Comment by cartbinder** [comment]
Yes no input fields to create a campaign url..

**Comment by philipwalton** [comment]
This is what the form looks like for me:

<img width="763" alt="screen shot 2017-05-30 at 5 01 05 pm" src="https://cloud.githubusercontent.com/assets/326742/26609983/9e9e4898-4559-11e7-8828-390de6a53c22.png">

Can you check the JavaScript console to see if there are errors on your page? Or perhaps you're using an extension that's blocking something?

**Comment by cartbinder** [comment]
Got it. I have an old chrome version and its because of this its not getting supported. Have tried on new version on another device, works fine..
Thanks for helping.

**Comment by philipwalton** [comment]
I believe I discovered the root of this issue, and I think it should be working now, even in the older Chrome versions.

**Comment by west-pole** [comment]
Hi Philip,
thanks for sorting it out.
Apologies for delay I was AFK for a while. Just FYI I tested it initially in 3 browsers (FF, IE & chrome) and all had the same issue - so it wasn't just old version of chrome or add-ons (IE that I'm using is without any).

Thanks again for your help,
West-Pole
