### ISSUE TITLE
URL Generator

### ISSUE THREAD

**Issue by sagekreyol** [googleanalytics/ga-dev-tools#301]
I was using the developer tool to generate UTMs. The tool suggested
https://pevc2017.dealstreetasia.com/#utm_source=dealstreetasia&utm_medium=banner&utm_content=findoutmore

For one of my campaigns, but shouldn't the first hasthag after the destination URL be ? rather than #?
https://pevc2017.dealstreetasia.com/?utm_source=dealstreetasia&utm_medium=banner&utm_content=findoutmore

**Comment by mcohoon** [comment]
Uncheck the box which states "Set the campaign parameters in the fragment portion of the URL (not recommended)."
