### ISSUE TITLE
API for Firebase Analytics

### ISSUE THREAD

**Issue by fdibernardo** [googleanalytics/ga-dev-tools#304]
I've created an app inside Google Analytics which is linked to an app inside Firebase.
Has google yet provided public API to firebase analytics data?
 
I normally use this for testing Analytics Google Data:
https://ga-dev-tools.appspot.com/query-explorer/
 
But it does not work for Firebase object property...
Is there any way to query the Firebase dashboard, passing through the Google Analytics API?
 
Thanks

**Comment by Tamara-TDHI** [comment]
Sorry, no solution, but same question, so +1

**Comment by philipwalton** [comment]
No, the Query Explorer (or any Google Analytics reporting APIs) cannot be used on Firebase data.

**Comment by haoshuncheng** [comment]
+1

**Comment by haoshuncheng** [comment]
how can i get analytics data ?

**Comment by shubhamd** [comment]
+1

**Comment by apoorv7592** [comment]
+1

**Comment by ammarasim** [comment]
Hey @fdibernardo ! Have you found an solution?

**Comment by AlanSyue** [comment]
no solution

**Comment by phansch** [comment]
As far as I can tell, there is currently no way to do this. You'll have to connect with `BigQuery` to be able to fetch Firebase Analytics data in a programmatic way.
