### ISSUE TITLE
Real Time website traffic per second 

### ISSUE THREAD

**Issue by neetunandwani** [googleanalytics/ga-dev-tools#309]
Please add a demo  to embed chart in our website that will show requests per second or user per second data. It will be similar to as it is shown in 'https://console.developers.google.com/apis/dashboard' for analytics api.

**Comment by philipwalton** [comment]
The [Embed API's third party visualizations demo](https://ga-dev-tools.appspot.com/embed-api/third-party-visualizations/) shows an example of this. You can check out the code to see implementation details.

**Comment by neetunandwani** [comment]
Hi

But that demo does not show requests per second, it shows weekly data.
Even there is no dimentions to show per second data.

--
Regards,
Neetu Nandwani
Engineer - Grails
TO THE NEW

**Comment by philipwalton** [comment]
It shows Real Time data via the active users dimension.

Are you looking for visitor usage data or API usage data? If it's the latter than this is not the site for something like that. You'd want to look at cloud project APIs (I'm not sure they even exist).

**Comment by neetunandwani** [comment]
I am looking for the active users data per SECOND. And same data i can see
on analytics.google.com too in traffic graph.

But i am not able to embed same inmy wesite, is there any way i can show
per SECOND data in a graph

--
Regards,
Neetu Nandwani
Engineer - Grails
TO THE NEW

On Jul 6, 2017 12:06 AM, "Philip Walton" <notifications@github.com> wrote:

It shows Real Time data via the active users dimension.

Are you looking for visitor usage data or API usage data? If it's the
latter than this is not the site for something like that. You'd want to
look at cloud project APIs (I'm not sure they even exist).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/googleanalytics/ga-dev-tools/issues/309#issuecomment-313189354>,
or mute the thread

**Comment by neetunandwani** [comment]
Sorry, graph is not at analytic.google.com, it is at
https://console.developers.google.com/apis/api/analytics.googleapis.com/

It shows, traffic ,error and latency data.

--
Regards,
Neetu Nandwani
Engineer - Grails
TO THE NEW

**Comment by philipwalton** [comment]
Like I said, for programmatic access to data displayed on https://console.developers.google.com/apis, you're going to have to reach out to the Cloud team. I'm not sure what's possible there.

This site is for programmatic access to data displayed on analytics.google.com.

**Comment by neetunandwani** [comment]
Ok, thanks

--
Regards,
Neetu Nandwani
Engineer - Grails
TO THE NEW

**Comment by neetunandwani** [comment]
Can i please get any email reference where i can contact cloud team?

--
Regards,
Neetu Nandwani
Engineer - Grails
TO THE NEW

**Comment by philipwalton** [comment]
The site you linked to has help links. I'd start there.
