### ISSUE TITLE
Campaign URL Builder

### ISSUE THREAD

**Issue by sstickov** [googleanalytics/ga-dev-tools#310]
I keep trying to use campaign URL builder; however, I keep getting an error that my "rate limit is exceeded" when trying to shorten the URL. Not sure how or why this keeps happening, but I've only shortened one other url today. See error in screenshot. I am not a developer, this was the only way I could find support on the website: https://ga-dev-tools.appspot.com/campaign-url-builder/

![screen shot 2017-07-07 at 10 13 22 am](https://user-images.githubusercontent.com/29981244/27961592-326b910a-62fd-11e7-9bb6-b8ba547023f1.png)

**Comment by philipwalton** [comment]
Hmmm, not sure why that would be happening. Are you still seeing the error?

**Comment by sstickov** [comment]
I have not had to use Google URL shortener since I submitted this thread. I only use it about once a week... but this isn't the first time I've run into this issue. The first time it happened, I Googled it and a few forums recommended to just wait it out, which is what I did. This time, it happened after the first URL. I only shorten about 5-10 at a time so I shouldn't be exceeding any rate limits.

**Comment by philipwalton** [comment]
The quota limits apply to the project (the one I created for the site) not the user, and the only documented quota limitation is 1 million shortens per day:
https://developers.google.com/url-shortener/v1/getting_started#quota

My analytics show less than that for the last 30 days, so I'm not sure why this is happening. Perhaps there's an undocumented limit I'm not aware of.

**Comment by Lucretiel** [comment]
Per https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html, the Google URL shortener is going away, so we'll be converting the Campaign URL Builder to use a different shortener service (#377). This issue is therefore obselete, but we'll be sure to keep rate limiting concerns in mind when we switch.

**Comment by sstickov** [comment]
Thanks, so do I need an account with Firebase? FYI, the only way I could
get the Rate Limit Exceeded to go away was to clear my cache and use
Facebook's debugger tool to fetch new data. I began doing that every
Monday.


Best,

*Staci Stickovich*
*Marketing Program Manager*

DeBartolo Performing Arts Center
University of Notre Dame
574-631-1873 (Direct)
574-631-2800 (Ticket Office)
performingarts.nd.edu

<https://performingarts.nd.edu/presenting-series/>

+ Add the Presenting Series Calendar
<https://calendar.google.com/calendar/embed?src=nd.edu_bqhovktqqsda1u8grhnvkjlcf0%40group.calendar.google.com&ctz=America/New_York>

Connect with the DeBartolo Performing Arts Center!
Facebook <http://www.facebook.com/DeBartoloPerformingArtsCenter> | Instagram
<https://www.instagram.com/dpacnd/> | Twitter <https://twitter.com/DPACND> |
LinkedIn <https://www.linkedin.com/company/debartolo-performing-arts-center>
| YouTube <https://www.youtube.com/channel/UCOg_xDBi_W0ahMouvksB-hQ>

**Comment by Lucretiel** [comment]
You shouldn't have to change anything. I'll be updating the shortener code in Dev Tools to use the new service; the change should be invisible to the frontend (though obviously the shortened URLs will have a different domain)
