### ISSUE TITLE
Customer dashboard use case?

### ISSUE THREAD

**Issue by kaihendry** [googleanalytics/ga-dev-tools#311]
[I'm exploring the idea of using Google Analytics for a customer dashboard](https://twitter.com/kaihendry/status/884618844924502016), where errors related to a particular user ID is in one place for a support request to have a good picture of the errors he or she might be experiencing on the Web application.

Therefore a demo where you take https://developers.google.com/analytics/devguides/collection/analyticsjs/exceptions and show them via the reporting API would give me confidence your APIs could work. Thank you,

**Comment by philipwalton** [comment]
Thanks for the suggestion. While this is definitely something that would be possible to do with the reporting API, it's not something we'd likely show as a demo since a dataset like this doesn't really exist for this site.
