### ISSUE TITLE
active users with server-side-authorization/

### ISSUE THREAD

**Issue by metebalnueimat** [googleanalytics/ga-dev-tools#314]
Hello.
is it possible to get the activeusers widget in (server-side-authorization), because i want to share my current  real time activeUsers on cms pages without adding all team emails to google analytics account.

**Comment by metebalnueimat** [comment]
P.S : i want it similar to ActiveUsers in (third-party-visualizations), https://ga-dev-tools.appspot.com/embed-api/third-party-visualizations/

**Comment by Lucretiel** [comment]
This github repo contains all the source code for the GA Demos and Tools pages, so feel free to browse around! The active users widget is here: https://github.com/googleanalytics/ga-dev-tools/blob/master/src/javascript/embed-api/components/active-users.js
