### ISSUE TITLE
Feature Request: Account Explorer Export

### ISSUE THREAD

**Issue by 1987yama3** [googleanalytics/ga-dev-tools#316]
I would like to download all of my accounts(properties, views) to CSV( or Spreadsheet etc). 

This feature is usefull for checking what property I have. If I am an agency, the feature supports to find properties that are not currently needed. Since I can not judge whether it is necessary or not by myself, I need to be able to share it to team members.

If you agree this feature, I would like to develop it.

Thanks

**Comment by Lucretiel** [comment]
To my knowledge, we don't have an official UI for that feature, though feel free to peruse the Account Administration page at https://analytics.google.com/ to see if it exists.

If you'd like to develop such a feature yourself, by all means feel free! The [Management API](https://developers.google.com/analytics/devguides/config/mgmt/v3/) should have access to everything you need to convert your list of accounts, properties, and views to a CSV. If you come up with a working demo and would like to see it on the Demos and Tools page, feel free to open a pull request, and I'll work with you to get it integrated!
