### ISSUE TITLE
Cohort Request on Segments not working!

### ISSUE THREAD

**Issue by vj-repo** [googleanalytics/ga-dev-tools#317]
Hi there,

Do we have any issues with Cohort Request API? When i'm trying to add segment ID or choose the existed ones like gaid::-3, It is not filtering the result and showing all  cohortActiveUsers data .  

Kindly some one let me know what i'm doing wrong. Or is it something to do with API?

Thanks in advance.
V

**Comment by vj-repo** [comment]
<img width="770" alt="screen shot 2017-08-23 at 3 25 53 pm" src="https://user-images.githubusercontent.com/5690657/29620988-62ebe412-8817-11e7-9f32-4d7585be25e8.png">
<img width="1192" alt="screen shot 2017-08-23 at 3 24 14 pm" src="https://user-images.githubusercontent.com/5690657/29620943-4519fbd6-8817-11e7-8128-8d6e79df6b33.png">

**Comment by Lucretiel** [comment]
That does indeed appear to be a bug! It looks like the segment isn't actually getting set in the request. Will investigate further; thanks for the report!

**Comment by Lucretiel** [comment]
Quick update: this does appear to be deliberate, though I'm not sure why. I don't know enough about the API to know whether or not it doesn't make sense to combine segments with a Cohort report.

The relevant code is [here](https://github.com/googleanalytics/ga-dev-tools/blob/d258783ca4519fd24211936a7c1ed079b47d3373/src/javascript/request-composer/request.js#L197-L209)

Also, weirdly, it appears that the decision about whether to have segments apply to cohorts was reverted and re-reverted no less than 3 times: [here](https://github.com/googleanalytics/ga-dev-tools/commit/7cc220a548b9dc1bd40385e8edacd411b0726e59), [here])(https://github.com/googleanalytics/ga-dev-tools/commit/d937d4589ff045bd377db1b763304d342470fce1), and [here](https://github.com/googleanalytics/ga-dev-tools/commit/9248496c504dac6bdb10487bfa6dfc99db04c29f). I'll investigate why this was done. There are two possibilities:

- It is correctly suppressed, in which case I'll remove the UI element
- It is incorrectly suppressed, in which case I'll fix it.

**Comment by Lucretiel** [comment]
I also note that the segments UI element was re-added in 7b593065d45f49520877ceb874dc37781b222ed7.

**Comment by Lucretiel** [comment]
@vj-repo I pushed the updated version out today! Thanks for the report
