### ISSUE TITLE
ie11 issues w/ GA embed API

### ISSUE THREAD

**Issue by sbaldwin24** [googleanalytics/ga-dev-tools#318]
Keep getting an "Access is denied" error in ie11, works fine in Chrome.

[third party visual demo](https://ga-dev-tools.appspot.com/embed-api/third-party-visualizations/)

![ga-dev-chrome](https://user-images.githubusercontent.com/5033746/29753859-ac387f7e-8b3f-11e7-810a-d09214093411.png)

![ga-dev-ie11](https://user-images.githubusercontent.com/5033746/29753860-ac3fa650-8b3f-11e7-8feb-7e76ef689800.png)

**Comment by Lucretiel** [comment]
Do you have any privacy settings set, such as disable Local Storage, or disable third-party cookies? There's a known issue (#284) where disabling third party cookies causes errors that we can't currently handle gracefully.

**Comment by diminishedprime** [comment]
Hi. There's not enough to go on to address this issue. If you're still facing this problem, feel free to re-open this issue & add in further detail.
