### ISSUE TITLE
Anchor value to doc is wrong for certain prop names

### ISSUE THREAD

**Issue by donwilson** [googleanalytics/ga-dev-tools#319]
https://github.com/googleanalytics/ga-dev-tools/blob/2ec4ca7f7d4262bb09efda43322e838a9f63ddb6/src/javascript/components/help-icon-link.js#L29

this.props.name needs to be filtered to turn dashes into next character capitalization (eg: "start-date" -> startDate)

**Comment by philipwalton** [comment]
Where are you seeing this mess up on the site?

**Comment by donwilson** [comment]
https://ga-dev-tools.appspot.com/query-explorer/ - the (i) info icon to the right of start-date, end-date, include-empty-rows, start-index, max-results. They don't take you to the subsection in the docs since they've changed from #start-date to #startDate

**Comment by philipwalton** [comment]
Ahh, thanks, this should be fixed now.
