### ISSUE TITLE
Google Analytics API - Issue Experiment dimension

### ISSUE THREAD

**Issue by iagonovoa** [googleanalytics/ga-dev-tools#32]
Hello,

I noticed there is a bug in Google Analytics API while trying to read experiments data (AB Test) from it. I need to get number of sessions per experiment & variation. The number I get from GA API is much lower than the one I can see in web interface.

I have investigated a bit and discovered that any time I add experiment dimensions (ga:experimentId or ga:experimentVariant) in API query the results are wrong.

See below an example of the difference I am talking about. 

On 20th January 2015, GA says that we had over 12000 visits to an experiment (Experiment GA - 20150120)

![experiment ga - 20150120](https://cloud.githubusercontent.com/assets/10629292/5834602/c53fa60e-a15f-11e4-8ffe-437015a7be47.PNG)

While API returns just 3718 visits (Experiment API - 20150120)

![experiment api - 20150120](https://cloud.githubusercontent.com/assets/10629292/5834601/c53e8968-a15f-11e4-83ac-09735db5230a.PNG)

This issue affects to all our AB tests. Any advice on that?

Thanks a lot in advance.

Regards,

Iago.

**Comment by philipwalton** [comment]
I'm going to close this issue because of its age. If you're still experiencing a problem, feel free to submit a new issue.
