### ISSUE TITLE
 Dimensions & Metrics Explorer 

### ISSUE THREAD

**Issue by dozen1488** [googleanalytics/ga-dev-tools#320]
There are several bugs with d&m explorer
These combination marked as right
![Exampe](https://content.screencast.com/users/DDDima/folders/Jing/media/a8a135bc-9107-4593-b1fb-0eb719798e59/2017-09-11_1805.png)
but it's not
![Exampe](https://content.screencast.com/users/DDDima/folders/Jing/media/cccc521a-f53e-46b7-8c9d-24034916cb62/2017-09-11_1807.png)
I'm looking for other invalid combinations currently. But can you explain, why Dimensions & Metrics Explorer doesn't provide proper information?

**Comment by Lucretiel** [comment]
Those image links appear to be broken; can you update if the issue is still happening?
