### ISSUE TITLE
Hit Builder Screen constantly refreshes

### ISSUE THREAD

**Issue by kdawg1406** [googleanalytics/ga-dev-tools#328]
Hi,

The Hit Builder screen does not work for me.  When I navigate to it, it constantly refreshes.

I'm using the latest build of Chrome.

Thank you for any help,

Karl

**Comment by philipwalton** [comment]
I can't reproduce this myself. Can you record a video of what you're seeing, or send screenshots?

**Comment by kdawg1406** [comment]
![image](https://user-images.githubusercontent.com/5623887/31680207-a79edb78-b341-11e7-9180-c0f70af227b5.png)

**Comment by kdawg1406** [comment]
@philipwalton see how the lower section is grayed out.

**Comment by philipwalton** [comment]
Do you see any errors in the developer console?

**Comment by kdawg1406** [comment]
@philipwalton - great suggestion, here is the error:

Uncaught Object details: "sessionStorage is not available in the current environment."
error:  "idpiframe_initialization_failed"

![image](https://user-images.githubusercontent.com/5623887/31718902-8c861768-b3df-11e7-875a-1d71fb3d8b00.png)

**Comment by kdawg1406** [comment]
@philipwalton I had to allow third-party cookies for it to work.  

Too many sites are not needing this...

**Comment by philipwalton** [comment]
Yeah, unfortunately third-party cookies are required to use any third-party, client-side login system.

If you were building this yourself, you could do server-side login to get around this.
