### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by liketohelp** [googleanalytics/ga-dev-tools#330]
Hi,

I'm interested in using the Usage Trends tool:

https://ga-dev-tools.appspot.com/usage-trends/

for one of my client but wanted some information on the privacy policy as I need to understand the policy on information security and who would be responsible for misuse of our data.

I understand that Google own the domain appspot.com but does this guarantee that all applications hosted under this domain are governed by Google's privacy policy:

https://www.google.com/policies/privacy/

Many thanks in advance for your help.

Anil

**Comment by philipwalton** [comment]
The appspot.com domain is a publicly available for anyone to create any app. If you have privacy concerns, you can always run the app locally.

**Comment by liketohelp** [comment]
Hi.  

Do you mean download the usage trends code, build it locally and the deploy it to our server so it runs as per:

https://ga-dev-tools.appspot.com/usage-trends/

In this way are you saying that execution will be localised to our server?  If we connect our copy of the usage trends tool on our Google Analytics will external access be blocked?

Thanks again for your help.

**Comment by philipwalton** [comment]
> Do you mean download the usage trends code, build it locally and the deploy it to our server

Yes

> In this way are you saying that execution will be localised to our server? If we connect our copy of the usage trends tool on our Google Analytics will external access be blocked?

I don't know what you mean by external access. You're accessing Google Analytics data, which means you've already sent the data to Google, which means it already has access.

**Comment by Lucretiel** [comment]
@liketohelp Quick check that your questions have been resolved and we can close this issues

**Comment by Lucretiel** [comment]
I'm assuming this is resolved
