### ISSUE TITLE
`error Package "@bower_components/ga-dev-tools@" doesn't have a "version"` error when using yarn

### ISSUE THREAD

**Issue by sachin-gupta** [googleanalytics/ga-dev-tools#334]
While moving to yarn from npm and bower i've got this: `error Package "@bower_components/ga-dev-tools@" doesn't have a "version"` error. Yarn was able to install package ga-dev-tools successfully for first time with *version empty* in yarn.lock for first time.

Upon investigation i found file package.json does not contains "version" field. Please add `"version": "0.0.0"` to package.json in order to make this aware of modern package managers. A small change but makes a big difference.

**Comment by philipwalton** [comment]
What is the use case for installing this package from npm/yarn?

**Comment by philipwalton** [comment]
I meant what's the use case for installing the package this package at all? What code in here are you depending on?

> Bower is now off-life and few other dependencies already stopped compiling. It's high time to move packages to new Yarn/Npm. Bower recommends now Officially.

This site never supported bower, so I'm not sure why you're mentioning this.

**Comment by sachin-gupta** [comment]
My bad about writing for bower, while moving away from npm/bower to new yarn, `ga-dev-tools` not picked from github URL as its missing version number field in package.json. I want to put article on my non-commercial blog showcasing how easy with this tool is for google analytics with due credits.

Registration to node, bower or yarn is totally teams choice, this issue is raised requesting addition of version number field to "package.json" file.

**Comment by philipwalton** [comment]
Maybe I'm being unclear. Let me ask my question in another way. It sounds like you're asking for the ability for users to do this:

```sh
npm install github:googleanalytics/ga-dev-tools#master
```

I guess I'm wondering why someone would need to do that? What's the use case for installing from npm vs. doing a `git clone` as described in the README?

**Comment by sachin-gupta** [comment]
Even without registration of package on npm registry, npm can automatically pick new package revisions directly from git url that too wrt semver using packae.json.

One can define to pull new updates if version number is like 1.*.* indicating pick minor fixes only and not major changes. It does not mandate 'version' field, but new tool yarn requires.

Just in case adding a simple 'version:0.0.0' line to package.json will be good. 

I only intended to raise this point in good gesture to your work. 

⁣Sent from TypeApp ​

**Comment by philipwalton** [comment]
> One can define to pull new updates if version number is like 1.*.* indicating pick minor fixes only and not major changes. It does not mandate 'version' field, but new tool yarn requires.

I don't think this is true, when you `npm install` from Github I'm pretty sure you need to specify a commit hash, branch, or tag name. Either way, the ga-dev-tools repo is source code for a website ([Google Analytics Demos & Tools](https://ga-dev-tools.appspot.com/)) not a library, so we don't use versions and we don't have any git tags.

The only reason I can think of to install a package via npm/yarn is if you want it to be a dependency of another program/application or you want to install a CLI globally on your system. I don't see why anyone would want to do either with ga-dev-tools.

I've asked you _why_ you want to `npm install` the ga-dev-tools repo a few times and you haven't directly answered that question. Unless there's a good reason to do this, I don't want to put a fake version field in the package.json file.

**Comment by sachin-gupta** [comment]
You point is right no need to add version as you've added ga-dev-tools is
not library.

I guess "one can make calls to this publicly accessible code, unmodified,
as per mentioned APACHE 2.0 license for creation of simpler demo on
non-profit blog". If not allowed please update ?

**Comment by philipwalton** [comment]
>  guess "one can make calls to this publicly accessible code, unmodified, as per mentioned APACHE 2.0 license for creation of simpler demo on non-profit blog". If not allowed please update ?

It's allowed, I just don't think it's particularly useful for anyone to do so, and I don't want to encourage patterns that I think won't help people.

**Comment by sachin-gupta** [comment]
​Thanks for KT am newbie in the field :)​


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
