### ISSUE TITLE
How to create event using API in GA

### ISSUE THREAD

**Issue by BharviManvar** [googleanalytics/ga-dev-tools#340]
Hello Team,

I want to create dynamic event in Google Analytics using API .Please give me a suggestion .I have used below code:
$data = array("v"=>'1', 
			 "dh"=>"example.com",
			 "tid"=>"UA-XXXXXXX-1",
			 "cid"=>generateUUID(),
			 "t"=>'event',
			 "ec"=>'form',
			 "ea"=>'submit',
			 "el"=>'Test',
			 "ni"=>'1');
function generateUUID(){
	$uuid = array(
		  'time_low'  => 0,
		  'time_mid'  => 0,
		  'time_hi'  => 0,
		  'clock_seq_hi' => 0,
		  'clock_seq_low' => 0,
		  'node'   => array()
		 );
                 $uuid['time_low'] = mt_rand(0, 0xffff) + (mt_rand(0, 0xffff) << 16);
		 $uuid['time_mid'] = mt_rand(0, 0xffff);
		 $uuid['time_hi'] = (4 << 12) | (mt_rand(0, 0x1000));
		 $uuid['clock_seq_hi'] = (1 << 7) | (mt_rand(0, 128));
		 $uuid['clock_seq_low'] = mt_rand(0, 255);
		 for ($i = 0; $i < 6; $i++) {
		  $uuid['node'][$i] = mt_rand(0, 255);
		 }
		 $uuid = sprintf('%08x-%04x-%04x-%02x%02x-%02x%02x%02x%02x%02x%02x',
		  $uuid['time_low'],
		  $uuid['time_mid'],
		  $uuid['time_hi'],
		  $uuid['clock_seq_hi'],
		  $uuid['clock_seq_low'],
		  $uuid['node'][0],
		  $uuid['node'][1],
		  $uuid['node'][2],
		  $uuid['node'][3],
		  $uuid['node'][4],
		  $uuid['node'][5]
		 );
		 return $uuid;
}
$URL_Add = "https://www.google-analytics.com/collect";
$ch_Add = curl_init();
curl_setopt($ch_Add, CURLOPT_URL,$URL_Add);
curl_setopt($ch_Add, CURLOPT_USERAGENT,'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13');
curl_setopt($ch_Add, CURLOPT_TIMEOUT, 30); //timeout after 30 seconds
curl_setopt($ch_Add, CURLOPT_POST, true);
curl_setopt($ch_Add, CURLOPT_POSTFIELDS, $data);
curl_setopt($ch_Add, CURLOPT_RETURNTRANSFER,1);
$result=curl_exec ($ch_Add);
echo $status_code = curl_getinfo($ch_Add, CURLINFO_HTTP_CODE);   //get status code
curl_close ($ch_Add);
$json_Add = json_decode($result,true);

Thanks

**Comment by philipwalton** [comment]
Sorry, it's not at all clear what you're trying to achieve, so there's not much advice I can give.

Also, these issues are for reporting bugs or feature requests for the Demos & Tools site, not for asking general Google Analytics questions. Please see https://developers.google.com/analytics/help/ for the best place to get your questions answered.
