### ISSUE TITLE
Query Explorer: error 400: Selected dimensions and metrics cannot be queried together

### ISSUE THREAD

**Issue by jburkhardt** [googleanalytics/ga-dev-tools#341]
Dimension ```ga:productName``` and metric ```ga:transactions``` cannot be queried together, although the combination of both is defined in the [API documentation of the ecommerce section](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=ecommerce).

![bildschirmfoto 2018-01-08 um 17 02 53](https://user-images.githubusercontent.com/5146122/34679492-7115f1f4-f496-11e7-805d-e3c6d95a9942.png)

**Comment by philipwalton** [comment]
@pfrisella, can you look into this or assign someone? Is the dimensions and metrics explorer wrong here? I get this error too when I try to query this combination.

**Comment by Lucretiel** [comment]
Re-confirmed. Filed an internal bug to have the API documentation investigated: https://issuetracker.google.com/issues/110723625
