### ISSUE TITLE
npm start hung up while running locally

### ISSUE THREAD

**Issue by suribabu39** [googleanalytics/ga-dev-tools#347]
Hi, I have cloned the project(local machine) and installed all the dependencies(mentioned in requirements.txt and gcloud app Python Extensions). 
Next when I try to run 'npm start' it won't start server and hung up after "Finished 'build:core' after ", it's not throwing any errors.

![screen shot 2018-02-08 at 2 18 51 pm](https://user-images.githubusercontent.com/22599304/35963795-e983eabc-0cdb-11e8-89e7-64575de64004.png)

I have run 'npm test' and all the test cases are passed. 
I haven't set any environment variables or configured any keys. I think all the dependencies exist.
If you need any extra information please let me know.
Atleast let me know how to debug and isolate the bug.

Thank You in advance,

**Comment by philipwalton** [comment]
It's hard to say based on what you've shown. I'd recommend adding `console.log()` statements to the various tasks in `gulpfile.babel.js` and see where things are hanging.

**Comment by diminishedprime** [comment]
Hi. There's not enough to go on to address this issue. If you're still facing this problem, feel free to re-open this issue & add in further detail.
