### ISSUE TITLE
Google URL shortener: continual "Rate Limit Exceeded" errors

### ISSUE THREAD

**Issue by DavidMannIS** [googleanalytics/ga-dev-tools#350]
Google URL shortener repeatedly blocks me stating "Rate Limit Exceeded".
- At best I may need to shorten 10 URLs per day using Google URL shortener. A loooong way shy of the 1 million supposed cut-off.
- It's been happening on and off for months. It's getting ever more problematic and I'm getting ready to use an alternative... unless someone can help!?

Issue has been raised on a number of occasions - but always closed without solution!
e.g. https://github.com/googleanalytics/ga-dev-tools/issues/310
- Has anyone from Google, or anywhere, got a solution to this?

**Comment by DavidMannIS** [comment]
Yesterday: After 3 hours of "Rate Limit Exceeded" it suddenly allowed my to shorten URLs.

Today: 1st thing, "Rate Limit Exceeded". 
I've not changed anything on the browser. I've certainly not shortened a URL today.
![image](https://user-images.githubusercontent.com/32451620/37084017-3c87d42c-21e9-11e8-9552-726f4d0ce079.png)

**Comment by DavidMannIS** [comment]
I removed the cookie (again - I tried last week) and it seems to have fixed the issue, for now.
![image](https://user-images.githubusercontent.com/32451620/37086687-1c2b1f20-21f0-11e8-8e1b-da2f240a57b0.png)

A cookie issue?

**Comment by Lucretiel** [comment]
Duplicate #310

**Comment by bommasani** [comment]
we also tried for [inovies](https://www.inovies.com) couple of times but end in vein
