### ISSUE TITLE
Returning wrong values when requesting longer time span

### ISSUE THREAD

**Issue by dataah** [googleanalytics/ga-dev-tools#352]
Using "https://ga-dev-tools.appspot.com/query-explorer/" to return ga:sessions and ga:transactions returns wrong values when requesting longer time span in start-date (eg. 2018-01-14) and end-date (eg. 2018-03-09). In my case the date 2018-01-14 should return in total 29 transactions - and does if the date is selected specific. But gives 33 transactions in the longer time span request above.

Sample screendumps:
![image](https://user-images.githubusercontent.com/6449829/37197271-65c20208-237a-11e8-9145-7ea99c492264.png)

**Comment by diminishedprime** [comment]
Hi. There's not enough to go on to address this issue. If you're still facing this problem, feel free to re-open this issue & add in further detail.
