### ISSUE TITLE
Google Custom URLS

### ISSUE THREAD

**Issue by RobynN94** [googleanalytics/ga-dev-tools#354]
Hi I have set up custom URLs to track campaigns. 

However, it is showing new users etc. but no purchase goals. As the campaign went really well and the URLS were used in a lot of the promoting there definitely had to be purchases through the URLS.

Is there any reason why it is not showing purchases?

**Comment by Lucretiel** [comment]
This github repo is for reporting bugs with the GA Dev Tools site. It's not really a good place to get support. Feel free to explore our [Product documentation](https://support.google.com/analytics) and [developer documentation)[https://developers.google.com/analytics/] to see what the different reports show, and how campaign attributions work.
