### ISSUE TITLE
URL Builder CSS

### ISSUE THREAD

**Issue by mfoote** [googleanalytics/ga-dev-tools#357]
Firefox 59 show the url builder site, https://ga-dev-tools.appspot.com/campaign-url-builder/ very jumbled.

![screen shot 2018-03-28 at 10 16 23 am](https://user-images.githubusercontent.com/1304829/38034837-1aba8a68-3271-11e8-9f85-9f3a4d32698e.png)

**Comment by philipwalton** [comment]
@mfoote I don't see this when looking at FF59 on my machine. Can you confirm that it's still an issue?

**Comment by diminishedprime** [comment]
This issue has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.
