### ISSUE TITLE
over the recommended limit errors for cd and dp

### ISSUE THREAD

**Issue by appsforartists** [googleanalytics/ga-dev-tools#361]
I was trying to test adding App ID and App Version to my Page View event.  I also tried making a Screen View event without an App Name.

In both cases, I got a failure that whichever of `cd` or `dp` I used was "over the recommended limit".  This is an incorrect error message.  The actual problems were with other parameters (like the missing application name, or trying to add App fields to a Page View event).

Moreover, the Parameter Reference says Application Name is optional.  The Hit Builder disagrees.

**Comment by philipwalton** [comment]
Can you paste an example hit that fails?

**Comment by diminishedprime** [comment]
This issues has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.
