### ISSUE TITLE
Url shortener not available

### ISSUE THREAD

**Issue by GiuliaAgnola** [googleanalytics/ga-dev-tools#362]
Good morning, 

I am writing you as I have an issue when using Campaign Url Builder-Google Analytics (https://ga-dev-tools.appspot.com/campaign-url-builder/).

Once I enter  the website URL and campaign information I can get the "generated campaign URL" but the option of shorten the link is not available... could you help me fixing this issue?

Thanks!

Giulia

**Comment by philipwalton** [comment]
Are you still seeing this issue?

**Comment by GiuliaAgnola** [comment]
Hi!

Yes, I cannot see the section to make the link shorter.

Attached the screenshot on how my Campaign Url Builder page looks like.

Thank you!

Giulia

**Comment by Lucretiel** [comment]
Sorry, I don't think github can pick up email screenshots. Can you attach it manually in github.com?

**Comment by GiuliaAgnola** [comment]
![screen shot 2018-05-01 at 08 33 32](https://user-images.githubusercontent.com/38234423/39453688-62025374-4d1a-11e8-9ce4-378df78c222a.png)

Sure here it is!

**Comment by GiuliaAgnola** [comment]
Cab you properly see my attachment?

**Comment by Lucretiel** [comment]
Confirmed that those issues don't show up for me with those terms. Don't worry if this is not the case, but are you familiar with your browser's developer tools? If so, can you open the console, and see if any errors are being reported as you type in the parameters?

**Comment by diminishedprime** [comment]
This issue has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.
