### ISSUE TITLE
Shorten Problem

### ISSUE THREAD

**Issue by RobbieJen** [googleanalytics/ga-dev-tools#367]
I sometimes shorten my link from your website,but it occurred "oops an error occurred trying to shorten thee url" why did it happen. But sometimes I could turn my link suddenly after this error. What problem it is ?

**Comment by philipwalton** [comment]
Sometimes temporary errors with the service occur, and it's best to just wait and try again later. Are you still seeing the issue?

**Comment by Lucretiel** [comment]
Was the error a rate limit? If so, it's a know issue: #310. Feel free to comment if it was a different error.
