### ISSUE TITLE
Check links traffic in tabular and graph form in which google analytics code can be added

### ISSUE THREAD

**Issue by k1221** [googleanalytics/ga-dev-tools#372]
How can i check link traffic

**Comment by Lucretiel** [comment]
This github page is for reporting bugs in the ga devtools page, here: https://ga-dev-tools.appspot.com/. It is not a place to make support requests. Feel free to peruse our [product documentation](http://support.google.com/analytics) and [developer documentation](https://developers.google.com/analytics/).
