### ISSUE TITLE
Feature Request: User Deletion API Feature

### ISSUE THREAD

**Issue by 1987yama3** [googleanalytics/ga-dev-tools#373]
I think that it would be nice to have a feature using the "User Deletion API" in the demo tools.
Because it is difficult for NON-Engineers to use the User Deletion API when if we want to delete user information for GDPR.

Thanks

**Comment by Lucretiel** [comment]
Thanks for the request! I'm following up with the product team internally to see if there is (or is going to be) an official analytics UI element for User Deletion. If that's not in the immediate future, I agree that this would be the perfect place to build a sample UI using the API!
