### ISSUE TITLE
Api Pull Sessions Showing 30%+ Lower Than Dashboard

### ISSUE THREAD

**Issue by twarble** [googleanalytics/ga-dev-tools#375]
I use an API call to pull data for a large number of specific pages, and for at least since the end of April, which is when I first noticed it specifically, the sessions data is massively off. 

It appears to be an API problem as the query explorer, https://ga-dev-tools.appspot.com/query-explorer/, is showing lower sessions than the main dashboard. I am doing a regex filter (ga:pagePath=~/Burda Style May 2018) and the API is reporting 37% lower sessions than pulling directly out of GA for that specific example. 

I am using the higher_precision command in the API as well. How I am certain it is off is the sessions count is showing lower than the user count in the API. Any help is appreciated!

**Comment by Lucretiel** [comment]
Can you post screenshots of the Analytics dashboard and the Query Explorer results, showing the mismatched data? Can you also confirm that the regex filter is precisely the same on both reports?

**Comment by diminishedprime** [comment]
We were not able to reproduce this error.
