### ISSUE TITLE
URL Shortener Service is deprecated; port to something else

### ISSUE THREAD

**Issue by Lucretiel** [googleanalytics/ga-dev-tools#377]
Per https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html: The google url shortener service has been deprecated, in favor of Firebase Dynamic Links. The Campaign URL Builder should therefore move off of this service and onto FDL, bitly, or some other shortening service.

This doesn't resolve #310, but it does obsolete it. However, we should keep in mind that whatever service we move to may also have rate limiting we need to be aware of.

**Comment by Lucretiel** [comment]
Quick update: This work will be completed soon. The move will be to bitly, and the shortener will require authorization in order to use.

**Comment by Lucretiel** [comment]
This issue is being fixed by #379

**Comment by marienn** [comment]
Hi, I have a question, will marketers will still able to build URLs on https://ga-dev-tools.appspot.com/campaign-url-builder/? How Google analytics will track the information from these URLs?

**Comment by Lucretiel** [comment]
@marienn 

> will marketers will still able to build URLs on https://ga-dev-tools.appspot.com/campaign-url-builder/?

Yes! The URL builder is remaining exactly the same. The only thing that is changing is that, when you click "Convert URL to Short Link", the shortened url will be a bit.ly link, instead of goo.gl.

> How Google analytics will track the information from these URLs?

I'm not sure what you mean by this. The campaign tracking will work the same as it always has for your own sites and analytics properties. My team records statistics about how many URLs are shortened per day, and similar anonymous usage data for the URL builder, but we don't do any independent tracking of the links themselves.

**Comment by Lucretiel** [comment]
The port is complete and has been merged into master. You are free to run it and test it in your own deployments. I have published a notice to the [production page](https://ga-dev-tools.appspot.com/campaign-url-builder/), to warn people that this change is coming, and will deploy it in 1 week, on June 17.

**Comment by Romenmmm** [comment]
Hi, will old shortened URLs created with the tool continue to work as they do today?

**Comment by Lucretiel** [comment]
Yup! From the [goo.gl blog](https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html):

> While most features of goo.gl will eventually sunset, all existing links will continue to redirect to the intended destination.

**Comment by Lucretiel** [comment]
Deployment completed. I'm closing the issue, but feel free to comment here if you run into any issues.
