### ISSUE TITLE
Query Explorer data table not showing

### ISSUE THREAD

**Issue by ideajunction** [googleanalytics/ga-dev-tools#38]
After I press "Get Data" on the Query Explorer:
https://ga-dev-tools.appspot.com/explorer
...the results table loads into the source, but does not display on the page.

I think the issue may be:
`#resultTable .google-visualization-table { width: 0px; }`
...which is applied as an inline style.

Removing this inline style via inspect element shows the table.

**Comment by philipwalton** [comment]
Looks like some very recent changes to the Google Visualization library broke this. It should be fixed via 45330ef9c9d6b56ec8b49d353e583641e1ad1574.
