### ISSUE TITLE
Total events summation doesn't work

### ISSUE THREAD

**Issue by srclopez** [googleanalytics/ga-dev-tools#381]
Hi, I detected that summation for total events is not working properly. For example if I set (for that filter  ga:pagePath=@/5694f04b1561e806f8855fd2;ga:eventCategory!=Slide)

date-start: 06/27 to 07/03 it shown 1 event:

![imagen](https://user-images.githubusercontent.com/30128305/42264387-c3eb3fa0-7f70-11e8-9932-1bdc119c5997.png)

And now if a set more days date-start: 06/01 to 07/03 it shown 0 event. How is that possible?

![imagen](https://user-images.githubusercontent.com/30128305/42264423-d9d00102-7f70-11e8-9b7c-0005a64fe8e3.png)

Thank you for your time.

**Comment by Lucretiel** [comment]
Thanks for the report! Without seeing more specific details, I would expect that this is a data sampling issue. Notice that the report says "Contains Sampled Data: Yes". You can read more about Data Sampling here: https://support.google.com/analytics/answer/2637192?hl=en. If you examine the response for your query in chrome's network tools, you should be able to find where it gives more details about the sampling thresholds being used.
