### ISSUE TITLE
URL shortening issue

### ISSUE THREAD

**Issue by slq10** [googleanalytics/ga-dev-tools#384]
Hi!

Since url builder shortening service was migrated to bitly, I have been getting an error message that states "Failed to fetch" while trying to shorten a link.

![screen shot 2018-07-23 at 9 42 34 am](https://user-images.githubusercontent.com/41557498/43053852-67f41e6c-8e1e-11e8-8c7b-baec50ae877d.png)

I tried cleaning the cache and history with no luck, while my Bitly account is working fine on its own. 

Kindly advise. Thanks very much!

**Comment by Lucretiel** [comment]
That error means that there was some kind of error executing the HTTP request, as opposed to an issue with bit.ly.

- Do you have any policies enabled in your browser regarding AJAX to third party domains? 
- Are you familiar with your browser's developer console? If so, can you open it, and post any errors you see when attempting to shorten a URL?

**Comment by slq10** [comment]
Hi!

Please find screenshot of my browser's developer console attached below. I am not familiar with the programming/coding world. Hope it helps. Thanks!

![screen shot 2018-07-24 at 9 42 03 am](https://user-images.githubusercontent.com/41557498/43112022-873b91f4-8ee3-11e8-8837-abafd188ea20.png)

**Comment by Lucretiel** [comment]
What browser + version are you using? Also, are you using any browser extensions, especially privacy focused ones? I'm familiar with that error, but I'm not sure why you'd be uniquely experiencing it.
