### ISSUE TITLE
Authorization is not working

### ISSUE THREAD

**Issue by JimmyCerone** [googleanalytics/ga-dev-tools#385]
When attempting to authorize the account explorer the pop up comes up fine but when I click on an account to authorize, the window disappears and I am left unable to authorize my account to get my View ID for the Analytics API

**Comment by Lucretiel** [comment]
Can you elaborate a bit on what you're seeing? For instance, can you send a screenshot of the Account Explorer page, after you've clicked your account in the authorization popup?

**Comment by JimmyCerone** [comment]
Yep - sorry I just saw this. I'll send a video over! http://recordit.co/srIunLyG0F

**Comment by Lucretiel** [comment]
- Does authorization work with any other of your gmail accounts?
- Can you repeat the process? I don't mean simply "try again", but more specifically, can you loop this failure by repeatedly clicking on Authorize?
- Are you familiar with Chrome Developer tools? If so, can you retry, and report any errors that appear in the developer console?

**Comment by JimmyCerone** [comment]
I don't have any properties on my other gmail accounts and I know for sure 1 is a school account where I don't have access to GA. 

Yes I can repeat the process - it loops repeatedly.

And no but I will retry and give it a look.

**Comment by Lucretiel** [comment]
Did removing the plugin fix the issue?

**Comment by JimmyCerone** [comment]
No but it did make all the errors go away.

**Comment by Lucretiel** [comment]
Do you use other chrome extensions? If so, can you retry with all extensions disabled? Usually when we run into this sort of issue, there's a plugin interfering in some way with our site code.

The easiest way to do this would be to try it in Firefox, if you have it installed, or else to use [Chrome Guest Mode](https://support.google.com/chrome/answer/6130773)

**Comment by JimmyCerone** [comment]
Oh I bet I know which one it is - I'll try to disable it for that site first.

**Comment by JimmyCerone** [comment]
That did it - either Ghostery or Privacy Badger was messing with it!
