### ISSUE TITLE
bugs in ga-gender

### ISSUE THREAD

**Issue by aviyashar** [googleanalytics/ga-dev-tools#386]
hello,
I want to know the amount of visitors for gender, the numbers are similar to analytics,
But if I add a site the numbers change completely.
![analytics1](https://user-images.githubusercontent.com/41910398/43404352-d0f06446-9406-11e8-8040-4ba5c61c5e83.JPG)
https://guides.github.com/features/mastering-markdown/
![analytics2](https://user-images.githubusercontent.com/41910398/43404355-d69d7db6-9406-11e8-975e-72226800b115.JPG)
![capture3](https://user-images.githubusercontent.com/41910398/43404358-d890cda8-9406-11e8-88d2-e760ed572cf4.JPG)

Can you help me with this issue?

Thanks,
Avi

**Comment by Lucretiel** [comment]
This board is a place to report bugs in the Demos and Tools web page. Unless you have a clear demonstration of a bug, we can't offer other kinds of support.

The next step toward seeing if this is a real bug would be creating your own query with the API and ensuring that it is identical to both the GA website and the Demos and Tools page.

Keep in mind as well that Analytics has a 24-48 hour [Data Processing Latency](https://support.google.com/analytics/answer/1070983?hl=en#DataProcessingLatency), during which time it is common to see anomalies like this.

**Comment by Cookiemonstar10** [comment]
Sorry 99% of my mail has ways been junk.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
