### ISSUE TITLE
Account explorer unable to load after sign in

### ISSUE THREAD

**Issue by tatrosh** [googleanalytics/ga-dev-tools#391]
On this URL: https://ga-dev-tools.appspot.com/account-explorer/

I tried to access account explorer using both my personal and work email login with no success. The page never finishes loading as shown on the following screenshot
![account explorer](https://user-images.githubusercontent.com/8981969/43633262-faa2e188-9708-11e8-8144-e5b9e9960fb7.png)

I tried accessing this page in Chrome, Edge and Internet Explorer with no success. I tried clean reinstallation of Chrome with wiping AppData with no success.

I believe the issue is connected with the following console message (see also in screenshot
```
Uncaught TypeError: Cannot read property 'properties' of undefined
    at s (account-explorer.js:1)
    at account-explorer.js:1
    at h.r2 (cb=gapi.loaded_0:84)
    at xs (cb=gapi.loaded_0:87)
    at Wq (cb=gapi.loaded_0:87)
    at _.C.uea (cb=gapi.loaded_0:87)
    at Ap (cb=gapi.loaded_0:80)
```
![account explorer - console](https://user-images.githubusercontent.com/8981969/43633412-7567bd76-9709-11e8-8782-262b6b0f063a.png)

If there is a solution to access Account explorer, please, let me know, yet I believe this is an issue I am unable to resolve myself.

**Comment by weishiny** [comment]
I run into the same error with you and I would like to get my view id for demo of ga reporting by following instruction from https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/web-js,

does anyone have solution? thanks in advance.

**Comment by Lucretiel** [comment]
Judging based on you're screenshot, it looks like you have a lot of extensions installed. There's a known issue (#284) where some privacy or cookie-blocking extensions cause the page not to work.

Unfortunately, the issue is not with this page, but with analytics.js. As documented in #284, there is an error handler that should be fired when authorization fails for some reason, but it isn't being fired in this case. Until that issue is fixed, the only workaround is to identify and disable the problematic extension(s).

**Comment by tatrosh** [comment]
It's not the extensions, it happens in incognito mode as well. And for a different account, I have no problems opening this page.

**Comment by tatrosh** [comment]
I guess it was not an issue with any extension, as I have tried opening this page in incognito window as well. However, it does seems to work correctly now (while I did not uninstall any extension). Not sure if anything was updated on my side though.

**Comment by HLNAJAM** [comment]
Still not solved. Same issue..... help needed guys!

**Comment by shayaansiddiqui** [comment]
it's been 1.5 years and it is still not solved!

**Comment by Boggartfly** [comment]
Yes, this issue is also affecting me.

**Comment by diminishedprime** [comment]
Could you post the following:

Your Operating System:
Your Web browser:
Any errors that show up in the developer console

I checked with my accounts and on Chrome on a Macbook pro, I can't reproduce this issue.

**Comment by Samuelonoja** [comment]
This bug still exists

**Comment by Sumaid** [comment]
I am also facing this issue

Operating System: macOS Big Sur v11.1
Your Web Browser: issue persists on both Chrome & Safari
Developer console errors : 
1) No errors on Chrome
2) On safari : `The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.`

**Comment by 74io** [comment]
I am also experiencing this issue with macOS Big Sur 11.2.3 (Chrome and Safari tested, also tested with Canary). Without this it would seem that it is not possible to use the Analytics Reporting API.

Is this a dead end?

**Comment by cpamir321** [comment]
In my case, disabling my `ublock origin` extension solved the problem
