### ISSUE TITLE
creating short links

### ISSUE THREAD

**Issue by 466663** [googleanalytics/ga-dev-tools#394]
each time i try to create a short link i get a pop up message saying error. it says:
Oops, an error occurred trying to shorten the URL
NetworkError when attempting to fetch resource.
can you please help me resolve this issue.

thanks

**Comment by 466663** [comment]
HI

yes it does.

Not sure what you mean by the Chrome Developer console??

[cid:image001.jpg@01D3F1EE.775620C0]


joanna hannah | marketing coordinator
hours: m-f 9am-2.30pm
p: +64 3 943 8455
a: 2 long street, woolston, christchurch 8023
www.nood.co.nz<http://www.nood.co.nz/>

**Comment by 466663** [comment]
Ooh, ok, I was using firefox. would it be the same process here?

I can check with my IT team if it would be something blocking it.

Thanks

[cid:image001.jpg@01D3F1EE.775620C0]


joanna hannah | marketing coordinator
hours: m-f 9am-2.30pm
p: +64 3 943 8455
a: 2 long street, woolston, christchurch 8023
www.nood.co.nz<http://www.nood.co.nz/>

**Comment by Lucretiel** [comment]
Yes. I don't know how to access it, but firefox has a similar developer console which will have logs available.

**Comment by wang7z** [comment]
The site cannot convert short URL, which said:

Oops, an error occurred trying to shorten the URL
Error undefined from https://api-ssl.bitly.com/v4/user: INTERNAL_ERROR

**Comment by diminishedprime** [comment]
We were not able to reproduce this error.
