### ISSUE TITLE
URL buillder does not give the correct URL

### ISSUE THREAD

**Issue by thanhtran91** [googleanalytics/ga-dev-tools#399]
Hi,

I have a problem with the tool URL builder. As you can see in the photo, it give me a link with a "#" sign before "utm_source". I tried the link and my website page did not show up correctly (some elements are missing)

https://jobcampaign.ch/recrutement-cible/#utm_source=facebook&utm_medium=sponsorise&utm_campaign=trafic&utm_term=carrousel 

![image](https://user-images.githubusercontent.com/43372949/45681452-d96d0580-bb3d-11e8-825e-7899eaad7fa8.png)

However, I try another computer and it gives me a link with "?" sign. This time the page shows up correctly when I click the link

https://jobcampaign.ch/recrutement-cible/?utm_source=test&utm_medium=email&utm_campaign=qualification_database

Can you tell me what is the problem nd how to fix it? 

Thank you for your help.

Best,
Thanh

**Comment by Lucretiel** [comment]
It appears that you have "Set the campaign parameters in the fragment portion" checked. That will cause the UTM parameters to be in the `#` part of the URL, rather than the `?`
