### ISSUE TITLE
Query explorer always needs a refresh on changing attributes

### ISSUE THREAD

**Issue by kevalvegeto** [googleanalytics/ga-dev-tools#40]
Every time i input a wrong query in input fields like sort,filters,metrics etc the error persists even though the field has been corrected.It always needs a refresh , also while doing a refresh the data is not retained.
Also it would be great if there is a search in dimension and metric field since it is annoying to manually search to all field and select the proper check box

**Comment by philipwalton** [comment]
A new version of the query explorer is currently being developed, and it will include all of the things you mentioned. You can track its progress in issue #35 .
