### ISSUE TITLE
Discrepancy of user data in google analytics api

### ISSUE THREAD

**Issue by trishaamadeo** [googleanalytics/ga-dev-tools#402]
When i try google query explorer
![image](https://user-images.githubusercontent.com/36374381/46053476-320b5680-c16d-11e8-930b-93a938fcdf95.png)

but when i try to separate the query by date,, the number of users is not sync with the total of users by month
![image](https://user-images.githubusercontent.com/36374381/46053508-58c98d00-c16d-11e8-8597-201e95100b03.png)

**Comment by Lucretiel** [comment]
If I had to guess, this is the effect of overlap between days. For instance:

August 1: Users A, B, C visit your site
August 2: Users B, C, D visit your site

The naive sum would be six, but the accurate total would be 4.

**Comment by trishaamadeo** [comment]
oh right,, thank you @Lucretiel
