### ISSUE TITLE
 Google Analytics Embed Example outdated.

### ISSUE THREAD

**Issue by julian-r** [googleanalytics/ga-dev-tools#403]
https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/290

https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/ is outdatet.

```py
# service-account.py

from oauth2client.service_account import ServiceAccountCredentials

# The scope for the OAuth2 request.
SCOPE = 'https://www.googleapis.com/auth/analytics.readonly'

# The location of the key file with the key data.
KEY_FILEPATH = 'path/to/json-key.json'

# Defines a method to get an access token from the ServiceAccount object.
def get_access_token():
  return ServiceAccountCredentials.from_json_keyfile_name(
      KEY_FILEPATH, SCOPE).get_access_token().access_token
```

I have trouble making this work with `google-auth`:

My try:

```py
# service-account.py

from google.oauth2.service_account import Credentials

# The scope for the OAuth2 request.
SCOPE = 'https://www.googleapis.com/auth/analytics.readonly'

# The location of the key file with the key data.
KEY_FILEPATH = 'path/to/json-key.json'

# Defines a method to get an access token from the ServiceAccount object.
def get_access_token():
  return Credentials.from_service_account_file(KEY_FILEPATH, scopes=[SCOPE]).get_access_token().access_token
```

**Comment by Lucretiel** [comment]
Can you describe the exact issue you're experiencing, and what you're trying to do?

**Comment by julian-r** [comment]
@Lucretiel 

In your example you're using `oauth2client`. This is deprecated.

> Note: oauth2client is now deprecated. No more features will be added to the libraries and the core team is turning down support. We recommend you use google-auth and oauthlib. For more details on the deprecation, see oauth2client deprecation.

So it I guess since you are providing a google product, you might want to update your code example. :)

**Comment by Lucretiel** [comment]
Thanks! I'll test your code and see about updating the example

**Comment by tbussmann** [comment]
Unfortunately, these examples seems to be no longer part of the site after the rewrite. 

In case anyone else has the same issue when updating the old sample script for service account authorisation from `oauth2client` to `google.oauth2`, the trick is to call [`.refresh()`](https://google-auth.readthedocs.io/en/master/reference/google.oauth2.service_account.html#google.oauth2.service_account.Credentials.refresh) on the [`Credentials`](https://google-auth.readthedocs.io/en/master/reference/google.oauth2.service_account.html#google.oauth2.service_account.Credentials)-object to populate it before getting the `.token` out of it:

```python3
# service-account.py

from google.oauth2.service_account import Credentials
from google.auth.transport.requests import Request

# The scope for the OAuth2 request.
SCOPE = 'https://www.googleapis.com/auth/analytics.readonly'

# The location of the key file with the key data.
KEY_FILEPATH = 'path/to/json-key.json'

# Define a method to get an Credentials object from the service account
# key file, refresh that to populate an access token and return this
def get_access_token():
  cred = Credentials.from_service_account_file(KEY_FILEPATH, scopes=[SCOPE])
  req = Request()
  cred.refresh(req)
  return cred.token
```
