### ISSUE TITLE
UTM builder bug

### ISSUE THREAD

**Issue by advcdd** [googleanalytics/ga-dev-tools#404]
Hi,

There is a problem with the UTM builder on your website. The tags start with a hashtag instead of a question mark. Unfortunately I noticed it today, after have made many UTM's last week that are, obviously, not working.

Hope you can fix this problem soon! Thanks in advance!

Kids regards,

Annika

**Comment by davidpgero** [comment]
👋 @advcdd, thank you for reporting the issue. 

Let me ask you a clarification questions. 

Did you check the fragment portion checkbox when you generated the URLs? 

I could confirm the problem (`?` vs. `#` ) if I click the `Set the campaign parameters in the fragment portion of the URL (not recommended).`.

## Without fragment portion

<img width="600" alt="without_fragment_portion" src="https://user-images.githubusercontent.com/750998/46816741-84f02b00-cd75-11e8-8cc9-83a06c202d6c.png">

## With fragment portion

<img width="600" alt="with_fragment_portion" src="https://user-images.githubusercontent.com/750998/46816758-8de0fc80-cd75-11e8-948a-eafe34073c9e.png">
