### ISSUE TITLE
Error occurring trying to shorten URL

### ISSUE THREAD

**Issue by adelehumphries** [googleanalytics/ga-dev-tools#405]
![campaign url error](https://user-images.githubusercontent.com/44195457/47008524-6b166580-d132-11e8-8874-9975156738d7.jpg)

**Comment by Lucretiel** [comment]
What specific problem are you having? I can't diagnose from a screenshot.

**Comment by diminishedprime** [comment]
Hi. There's not enough to go on to address this issue. If you're still facing this problem, feel free to re-open this issue & add in further detail.
