### ISSUE TITLE
Hit builder does not work in Firefox

### ISSUE THREAD

**Issue by jvincent-siplay** [googleanalytics/ga-dev-tools#407]
The Hit Builder page (https://ga-dev-tools.appspot.com/hit-builder/) does not seem to work in Firefox.  If you click the "Validate hit" button, it displays the following error:

Oops, an error occurred while validating the hit
Check your connection to make sure you're still online. If you're still having problems, try refreshing the page.

It works in Chrome.  This is true both on PC and Mac.

**Comment by Lucretiel** [comment]
Thanks for reporting! Will try to reproduce and get back to you

**Comment by diminishedprime** [comment]
We were not able to reproduce this error.
