### ISSUE TITLE
Server-Side Authentication demo is not entirely clear about requirements

### ISSUE THREAD

**Issue by sofiazapatazavala** [googleanalytics/ga-dev-tools#409]
Hi!

**Introduction**
I'm starting to work with Python, and I'm working on a little project that's already using OAuth and getting data from Google Analytics, but I was asked to implement a solution without signing in, and that's where I thought the server side authentication demo could help me.

**Problem**
During step 3, you have to create a .py file to get the access token (I already tried the demo for using a service account so it wasn't painful). The thing is, you get the token and then the demo isn't explicit about what to do or where to "use" the token. Do you have to print it (which I did), and then paste it in a separate HTML file that you have to create along with the scripts (just like the other demos)? Do you have to store it somewhere, tying yourself to using a Python-dependant system (e.g. Django or another templating engine) to complete the tutorial?

**Possible solution**
If you only need this Python script to create the access token, it should be clearly stated that you have to create that script, and then you can work just like in the other demos, with a HTML file. If you must have a server-side infrastructure like the one that powers this site, it should be indicated too. Step 4 should be the proper place to do it.

I hope this suggestion can be helpful.

**Comment by Lucretiel** [comment]
Thank you for the suggestion! I've run into a few of these issues myself, so your feedback is very helpful. I'll add this to the list of things to work on when I do a work sprint on the Developer tools.
