### ISSUE TITLE
Request Git for Ibby's T-Shirt Shop 

### ISSUE THREAD

**Issue by jAusLs** [googleanalytics/ga-dev-tools#41]
Hello

Is the Enhanced E-Commerce demo website open source? See below for a link to the webpage I am talking about. Is there a git that exists for this website? I've searched but there cannot locate a git. If its not currently open source and available - are there any plans to make it open source?

https://enhancedecommerce.appspot.com/

**Comment by philipwalton** [comment]
Hello, no this is not currently open sourced, and at this point there are no plans to open source it, sorry.
