### ISSUE TITLE
Installation failed for python 3.7

### ISSUE THREAD

**Issue by noc2spam** [googleanalytics/ga-dev-tools#411]
Tried to install ga-dev-tools on my windows 10 laptop (python 3.7.0) but the requirements.txt failed to install because of PyCrypto [being dead](https://github.com/dlitz/pycrypto/issues/238). According to the linked thread, it is suggested to use PyCryptodome instead. 
I am not exactly sure how PyCrypto is used in ga dev tools as I have not looked into the project yet (and I am almost a n00b when it comes to python in general), but probably PyCryptodome should work the same way.

**Comment by Lucretiel** [comment]
Thanks for the report! Using outdated crypto is obviously a problem; we'll look into a fix as soon as we can
