### ISSUE TITLE
Google analytics report not getting refreashed.

### ISSUE THREAD

**Issue by soorajsskrishnan** [googleanalytics/ga-dev-tools#412]
Hi,

Am sending a post request to GA, even though am getting a success response(200) immediately, the report is not refreshing with my data sent.
https://www.google-analytics.com/collect?v=1&t=transaction&tid=UA-*******-2&cid=40524&dp=offline-sale&ti=P10013793R00&tr=928.29&
tt=60.7300000000&pa=purchase&pr1id=Car&pr1ca=Insurance&
pr1nm=Car&pr1va=Chery%2FJ1+1.3%2F30%25&pr1ba=ABCD%2520EFG&pr1premium=928.29&pr1qt=1&
ds=call-centre&qt=323000&cd5=Nil-Nil&
cd2=Single&cd10=Cash&uip=154.61.192.10&ec=Policy%2520Purchased&ea=Car&el=Car-off-off&ev=928.29&uid=40524&cn=Car-offline&cs=IDIT&cm=call

Please advise the possible reasons.

**Comment by Lucretiel** [comment]
Do you mean after sending hits? Google Analytics takes 24-48 hours to fully process all ingested data. For information, check our [data freshness documentation](https://support.google.com/google-ads/answer/2544985?hl=en)
