### ISSUE TITLE
Query explorer drop down field not filling in

### ISSUE THREAD

**Issue by MichaelMc64** [googleanalytics/ga-dev-tools#415]
After authorizing, the drop down menus, Account, property, and view, in the "Select a view" section do not load. I have tried in both Firefox and Chrome (Version 72.0.3626.121 (Official Build) (64-bit)).

**Comment by liesbethandressen** [comment]
I have the same issue. is your issue already fixed?would love to know the solution!

**Comment by Lucretiel** [comment]
Can't reproduce– can you provide any additional details that might be causing it? Have you tried in incognito mode or with browser extensions disabled?

**Comment by diminishedprime** [comment]
This issues has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.
