### ISSUE TITLE
Required fields for Campaign Builder

### ISSUE THREAD

**Issue by gvilcins** [googleanalytics/ga-dev-tools#420]
utm_source, utm_medium, and utm_campaign are now required parameters.
Campaign Builder documentation should be updated to reflect this.

https://ga-dev-tools.appspot.com/campaign-url-builder/

https://support.google.com/analytics/answer/1033863?visit_id=1-636207680827492939-1902274266&rd=1#parameters

**Comment by Lucretiel** [comment]
Thanks for the suggestion!

**Comment by Lucretiel** [comment]
This will be going out in our next deploy.

**Comment by Lucretiel** [comment]
This is now live! Thanks for the suggestion
