### ISSUE TITLE
URL Shortened - Authorization Required 

### ISSUE THREAD

**Issue by camilleotttriumph** [googleanalytics/ga-dev-tools#426]
Hi there,

I have an issue with the URL Campaign Manager. I cannot shorten the link with Bitly. It says I need a specific authorization. See the screenshot attached. 

Please advise on how to proceed.

Many thanks for your help,
Camille.
![URL bug](https://user-images.githubusercontent.com/51082389/58426955-6b9ab580-809e-11e9-8ca4-252b9aa16334.PNG)

**Comment by Lucretiel** [comment]
Thank you for the report! It appears we accidentally failed to attach our bitly oauth credentials during our recent update. This will be fixed by the end of the day. Sorry for the inconvenience!

**Comment by Lucretiel** [comment]
This is now fixed!
