### ISSUE TITLE
request composer page does not load

### ISSUE THREAD

**Issue by rikengct** [googleanalytics/ga-dev-tools#427]
I have no problem using Query Explorer (https://ga-dev-tools.appspot.com/query-explorer/) to make queries into the google analytics of my site.

However, i cannot access the Request Composer (https://ga-dev-tools.appspot.com/request-composer/) from any browser (desktop or mobile) using the same login information.
When I try to authorize, the page remains somewhat faded-out and the blue line under the tile continues to animate forever as if something is trying to load.

is this a known issue or something I am doing wrong?

![image](https://user-images.githubusercontent.com/19792265/58529872-7fb5f280-8217-11e9-9823-918c37b1ee3e.png)

**Comment by initializard** [comment]
I'm seeing this too.

Looks like it's related to the React version being updated from 15.3 to 16. Request Composer is trying to use React.createClass() which is not available in the newer version of React. Possibly related to dbdd05f23132eaac82745eaa22ec64ef776c5fa1.

React documentation: https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactcreateclass

Chrome console error: 
![ga-req-comp-console](https://user-images.githubusercontent.com/2012737/58823542-8d94ba80-85ff-11e9-9064-bb9bc63c5015.png)

**Comment by Lucretiel** [comment]
Thank you for the report! This was do to an unnoticed broken dependency in our recent update. A fixed version will be deployed by the end of the day.

**Comment by Lucretiel** [comment]
This is now fixed!
