### ISSUE TITLE
【Uegrnt】Problem creating shorten UTM URL, issue from developer side.

### ISSUE THREAD

**Issue by ianloh91** [googleanalytics/ga-dev-tools#428]
![123456780](https://user-images.githubusercontent.com/51307165/58773019-887f3d80-85f6-11e9-96fd-755d1df2b046.jpg)

Error occurred when creating shorten UTM url.
Problem from developer side.
Please refer to attached pictures.

Looking forward to your reply.
Thanks.

Ian. 
y-loh@jellyfish-g.co.jp

**Comment by Lucretiel** [comment]
This is now fixed! Thank you for the report
