### ISSUE TITLE
GA add-on in Google spreadsheets won't run

### ISSUE THREAD

**Issue by elised** [googleanalytics/ga-dev-tools#43]
I have reports set up in Google spreadsheets, but every time I try to run them (Add-ons -> Google Analytics -> Run reports) the popup freezes right before it runs. Usually it has a loading circle in the middle to signify that it's running, but it hasn't been showing up since yesterday afternoon. Attached is a picture showing what I mean. It's happening on every report I try, on both accounts that I have linked to GA. It doesn't seem to be an internet problem since I can query using the query tool just fine, and I've restarted my computer twice with no luck. I've also run these reports many times in the past, so it's not a report-specific problem. Any advice? Thanks!
![example](https://cloud.githubusercontent.com/assets/11408596/6576311/b1bbabd2-c70c-11e4-9475-427ccd5c9a71.jpg)

**Comment by philipwalton** [comment]
In the most recent release of Google Sheets, the team made some changes and now certain add-on features no longer work in Chrome 40.

If you can upgrade to Chrome 41, that's the easiest fix to this problem.

**Comment by philipwalton** [comment]
In the future, you can check and report bugs for the Google Analytics Spreadsheet Add-on via this Google Group:
https://groups.google.com/forum/#!topic/google-analytics-spreadsheet-add-on/0IOqj4RcdhU
