### ISSUE TITLE
Request Composer - Tab UI Missing

### ISSUE THREAD

**Issue by initializard** [googleanalytics/ga-dev-tools#432]
The top set of options to set the request type for the Request Composer have HTML indicating they are react-tabs of some kind but they are missing the tab styling and appear as default \<li\>'s There's no indication they are clickable or are used change what form is displayed below.

<img width="459" alt="ga-req-comp-tabs" src="https://user-images.githubusercontent.com/2012737/58895133-e3796900-86b8-11e9-938c-ac3c69b112e6.png">

**Comment by Lucretiel** [comment]
Will investigate, thanks for the report!

**Comment by Lucretiel** [comment]
This is now fixed! Thanks for the heads up
