### ISSUE TITLE
Value of ga:campaign set to "(not set)" when ga:keyword=="(not set)" or ga:adcontent="(not set)"

### ISSUE THREAD

**Issue by fzapfack** [googleanalytics/ga-dev-tools#438]
query1: `https://ga-dev-tools.appspot.com/query-explorer/?start-date=2019-07-01&end-date=2019-07-01&metrics=ga%3Asessions&dimensions=ga%3Acampaign&filters=ga%3Asource%3D~%5E.oogle&max-results=1000`

![image](https://user-images.githubusercontent.com/7347058/60682157-9abcf780-9e92-11e9-9111-e5729e7cc77c.png)

query2: `https://ga-dev-tools.appspot.com/query-explorer/?start-date=2019-07-01&end-date=2019-07-01&metrics=ga%3Asessions&dimensions=ga%3Acampaign%2Cga%3Akeyword&filters=ga%3Asource%3D~%5E.oogle&max-results=1000`

![image](https://user-images.githubusercontent.com/7347058/60682254-ebcceb80-9e92-11e9-8f1d-11c67d588607.png)

**Comment by diminishedprime** [comment]
Hi. There's not enough to go on to address this issue. If you're still facing this problem, feel free to re-open this issue & add in further detail.
