### ISSUE TITLE
Google Analytics discordance values (Source / Medium dimension)

### ISSUE THREAD

**Issue by Fiamgit** [googleanalytics/ga-dev-tools#441]
Hi,

I have an issue gathering the data from the query explorer GA dev tool.
When I go to source / medium values on Analytics, I can clearly see that there are Google / Organic session.
But when I extract the values from the query GA dev tool they disappear.

Please let me know what could be the problem.

Thanks,
Fiam

**Comment by diminishedprime** [comment]
This issue has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.
