### ISSUE TITLE
New Dimensions & Metrics Explorer: error in allowed combinations

### ISSUE THREAD

**Issue by lcrespilho** [googleanalytics/ga-dev-tools#444]
I am able to combine wrong metrics and dimensions in the new D&M Explorer (https://ga-dev-tools.appspot.com/dimensions-metrics-explorer/).

For example, I can make this combination:
dimensions: ga:product
metrics: ga:refundAmount

But this combination is not valid in GA Custom Reports, neither it is on the actual D&M Explorer (https://developers.google.com/analytics/devguides/reporting/core/dimsmets).

Regards.

**Comment by diminishedprime** [comment]
This issue has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.
