### ISSUE TITLE
Error: "gapi.analytics.ext is undefined" when trying out the examples

### ISSUE THREAD

**Issue by F-Ramos-B** [googleanalytics/ga-dev-tools#445]
Hello, I checked out the demos and saw the "Third Party Visualizations" example fits exactly what we wanted for our dashboard, but when trying to use the code provided, I get a "gapi.analytics.ext is undefined" error message in the console.

I was able to use the "Basic Dashboard", "Multiple Views" and "Interactive Charts" without issues.

I tried changing the import URLs to use this github and also tried downloading each of the imported files and put into a separate .js file and nothing worked. What exactly do I need to do to be able to use this example on my website?

**Comment by diminishedprime** [comment]
This issue has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.
