### ISSUE TITLE
Account explorer unable to load after sign in

### ISSUE THREAD

**Issue by AkashSurana** [googleanalytics/ga-dev-tools#449]
On this URL: https://ga-dev-tools.appspot.com/account-explorer/

I tried to access account explorer using both my personal and work email login with no success. The page never finishes loading as shown on the following screenshot
account explorer

I tried accessing this page in Chrome, Edge and Internet Explorer with no success. I tried clean reinstallation of Chrome with wiping AppData with no success.

I believe the issue is connected with the following console message . I do have an analytics account.
![image](https://user-images.githubusercontent.com/27774371/64684074-0f6b6e00-d4a2-11e9-9f67-e639bf53130a.png)

I'm following this document https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/web-js
 and need  to get the client id

**Comment by diminishedprime** [comment]
We were not able to reproduce this error.
