### ISSUE TITLE
Query Explorer Tool - 500 Internal server error when exporting results

### ISSUE THREAD

**Issue by paragshah79** [googleanalytics/ga-dev-tools#45]
I am using Query Explorer Tool for pulling up the analytics results. The results are showing up on clicking of 'Get Data' button. When I try to export the results using the 'Excel TSV' button it throws a 500 Internal server error on the page. I have been getting this error since March 18th 2015. The export was working prior to it.

Thanks
Parag

**Comment by philipwalton** [comment]
Can you provide more details (like browser, OS, query, etc.)? I can't reproduce this error.

**Comment by paragshah79** [comment]
Hello Philip,
I am using Windows 8.1 Enterprise OS. The issue is occurring across 2 browsers that I am using on my system. i.e. Google Chrome - Ver 41.0.2272.101 m, Firefox - Ver 37.0

I am using the below query to filter out results

b.	Dimension - ga:eventCategory,ga:eventLabel
c.	Metrics - ga:totalEvents
d.	Filters - ga:eventCategory=@STNE - Summarised View;ga:eventLabel=@14883

When I modify the filter and exclude "STNE -" and try to export the results are exported in TSV format. It seems to be problem with eventCategory value that I am using.

Hope this will help you.

**Comment by philipwalton** [comment]
It looks like this was an encoding error as the dash in your query results was a unicode en dash rather than the typical ascii hyphen-minus.

I've deployed a new version that should fix the issue. Let me know if you're still having problems.

**Comment by paragshah79** [comment]
Hello Philip
I am still facing same error while exporting the results

**Comment by philipwalton** [comment]
Have you changed the query you're using? I don't see any errors in the logs for "filters=ga:eventCategory=@STNE - Summarised View;ga:eventLabel=@14883"

**Comment by philipwalton** [comment]
If you use the "Share Report" button to share the query with me, it will be easier to track down the source of the error.
