### ISSUE TITLE
Dimensions and Metrics Explorer don't have formulas anymore

### ISSUE THREAD

**Issue by AzucenaCoronel** [googleanalytics/ga-dev-tools#451]
I've just realised that with the Dimensions and Metrics Explorer update, the formulas doesn't show up anymore in the dimension/metric description.
For example: 
Avg. Time on Pagega:avgTimeOnPage
The average time users spent viewing this page or a set of pages.
Data Type: TIME
Added in API Version 3
Permalink

Before it use to include the formula definition:
Time On Page / (Pageviews - Exits)

These definitions were very very useful, can you please bring them back again?
Thanks

**Comment by fundamentalandrew** [comment]
This really does need sorting out. We now need to go hunting around blog posts trying to work out how GA calculates values whereas before it was so simple. This was one of the best features from the dimension explorer and hopefully you can add it back in soon.

**Comment by gblazq** [comment]
Having clear, unambigous definitions for calculated metrics is critical for data teams to properly understand them and act on accordingly.

Please consider adding them back, thanks.

**Comment by diminishedprime** [comment]
This issue has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.

**Comment by fundamentalandrew** [comment]
Of course we are still facing this issue, you removed the calculations, we told you they are vital to us and you are ignoring that.
