### ISSUE TITLE
Hit builder doesn't use validation server

### ISSUE THREAD

**Issue by onepan** [googleanalytics/ga-dev-tools#454]
Hit builder sends the post request to `/collect` instead of `/debug/collect`, but claims to use the validation server

![image](https://user-images.githubusercontent.com/27863390/67121543-99dd7680-f1a0-11e9-91ba-1fdaa0e4a6cd.png)

Looks like [here](https://github.com/googleanalytics/ga-dev-tools/blob/master/src/javascript/hit-builder/components/hit-element.js#L73) the `sendHit` function is sending to `/collect` instead of using the `getHitValidationResult` function defined [here](https://github.com/googleanalytics/ga-dev-tools/blob/master/src/javascript/hit-builder/hit.js#L99), that correctly sends to `/debug/collect`

**Comment by diminishedprime** [comment]
This might have been an issue in the past, but the current code uses both `/debug/collect` & `/collect` depending on where in the flow the user is.
