### ISSUE TITLE
Loading dimensions and metrics...

### ISSUE THREAD

**Issue by PranavMall** [googleanalytics/ga-dev-tools#455]
<p>The Dimensions and Metrics Explorer always shows loading dimensions and metrics but doesn't show any results. Attaches screenshot for reference.</p>
<p>Also clear search logo within the search tab cannot be viewed.</p>
<img width="590" alt="Search Query on Dimensions and Metrics Explorer" src="https://user-images.githubusercontent.com/17159173/67177860-6ccbd680-f3e1-11e9-8650-177548a54629.PNG">
<img width="620" alt="Dimensions and Metrics Explorer" src="https://user-images.githubusercontent.com/17159173/67177862-6ccbd680-f3e1-11e9-9e09-740318a979fe.PNG">

**Comment by diminishedprime** [comment]
We were not able to reproduce this error.
