### ISSUE TITLE
Missing option which metrics or dimensions is combinable

### ISSUE THREAD

**Issue by FJR030** [googleanalytics/ga-dev-tools#458]
About NEW dimensions / metrics explorer https://ga-dev-tools.appspot.com/dimensions-metrics-explorer/

Missing prominent option / features > checkbox which metrics or dimensions don’t match or combinable - simply check.

_Here is an example_

![image](https://user-images.githubusercontent.com/52575635/68301655-b9313a80-00a0-11ea-956b-a665213365fe.png)

Also the information / definitions have been changed - important information are missing.

_Here is an example_

Missing: detail definition, calculation, group/scope

NEW

```
Bounce Ratega:bounceRate
**The percentage of single-page session (i.e., session in which the person left the property from the first page).**
Data Type: PERCENT
Added in API Version 3
```

PREVIOUS

```
   "id": "ga:bounceRate",
   "kind": "analytics#column",
   "attributes": {
    "type": "METRIC",
    "dataType": "PERCENT",
    "group": "Session",
    "status": "PUBLIC",
    "uiName": "Bounce Rate",
    **"description": "The percentage of single-page session (i.e., session in which the person left the property from the first page).",**
    **"calculation": "ga:bounces / ga:sessions",**
    "addedInApiVersion": "3"
```

**Comment by diminishedprime** [comment]
This issue has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.
