### ISSUE TITLE
Wrong curly braces

### ISSUE THREAD

**Issue by AiratHalitov** [googleanalytics/ga-dev-tools#459]
Example:
![image](https://user-images.githubusercontent.com/4050715/68885842-c0f37d80-0737-11ea-8ee7-f17f9541aa76.png)

Result: 
`https://google.com/?utm_source=yandex&utm_medium=cpc&utm_campaign=my_campaign&utm_term=%7Bkeyword%7D&utm_content=%7Bad_id%7D`

How it should be:
`https://google.com/?utm_source=yandex&utm_medium=cpc&utm_campaign=my_campaign&utm_term={keyword}&utm_content={ad_id}`

Could you not convert `{` and `}` into `%7B` and `%7D`?

**Comment by Lucretiel** [comment]
What's the exact issue with that? That's a standard URL encoding; any url decoder will correctly convert those back to `{` and `}`

**Comment by AiratHalitov** [comment]
For more info about URL parameters: 

- Google Ads: https://support.google.com/google-ads/answer/6277564
- Yandex Direct: https://yandex.ru/support/direct/statistics/url-tags.html?lang=en

**Comment by diminishedprime** [comment]
For now, we're going to keep the escaping behavior as is since generally speaking all content in these fields should be url encoded. 

If there is enough interest in special casing for this use-case, we can re-evaluate this decision in the future.
