### ISSUE TITLE
Query Explorer: no matches found for metrics and dimensions

### ISSUE THREAD

**Issue by michelepisani** [googleanalytics/ga-dev-tools#461]
Hi,
There is a problem with the operation of the query explorer (https://ga-dev-tools.appspot.com/query-explorer/), the values ​​of metrics and dimensions are no longer selectable.

Probably this error in the console may be the reason:

![Schermata 2019-12-05 alle 11 38 11](https://user-images.githubusercontent.com/8077996/70228354-81c3b580-1754-11ea-93c2-c11f9dfd4cd1.png)

Thanks for the support and best regards,
Michele

**Comment by LuKaa** [comment]
I get the same error on google chrome Version 78.0.3904.108 (64-Bit) and on safari.

Error message: `"Invalid value '[ga, ga]'. Values must match the following regular expression: 'ga'"`

<img width="1706" alt="ga-bug" src="https://user-images.githubusercontent.com/6472013/70241301-1cc98900-176f-11ea-99ee-70ec772b222e.PNG">

**Comment by stuartbrameld** [comment]
getting the same error here too

**Comment by radavidescu** [comment]
same error on Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by jjmalina** [comment]
Having the same issue

**Comment by pfrisella** [comment]
The team is aware of the issue and is working on a fix. ETA is a few hours.
It has to do with the underlying Metadata API request.

**Comment by pfrisella** [comment]
This should be working again, somewhat intermittently. If you refresh a few times and check it should load correctly at some point. We're also going to push an update to the Query Explorer soon to definitively resolve the issue.

**Comment by pfrisella** [comment]
This should be fixed now. Feel free to re-open if any other related issues come up.

**Comment by BarryCap** [comment]
I think I'm getting the same error on Chrome 91:
![Screenshot](https://user-images.githubusercontent.com/63713811/120915877-8731f100-c6a6-11eb-8ea4-31e2209e8148.png)
And I don't know why, but I can't add my Property (the pop-up is blank).

**Comment by diminishedprime** [comment]
the value for start and end date should not include `start-date=`, the tool handles that part for you. So the error message you're seeing in the console is explaining what's wrong. 

As for the no properties, this is most likely due to the fact that the account you picked having no UA properties. You might want to try the [GA4 Query Explorer](https://ga-dev-tools.web.app/query-explorer/) and see if you have properties for that account.

**Comment by BarryCap** [comment]
No property as well…
![noproperty](https://user-images.githubusercontent.com/63713811/121214756-b780b780-c87f-11eb-86c9-b9b2043f451e.png)

**Comment by diminishedprime** [comment]
> As for the no properties, this is most likely due to the fact that the account you picked having no UA properties.

I'm pretty confident this is the case, now. I think the "Barry Cap" account that you picked doesn't have any UA properties. You can confirm this by going to the GA UI and looking there.

**Comment by BarryCap** [comment]
I'm currently using my Google Analytics account, it works well and I use it for my [property](https://barrycap.com).

![property](https://user-images.githubusercontent.com/63713811/121820940-c1e2ed00-cc95-11eb-8661-9e6733bcc6a3.png)

**Comment by diminishedprime** [comment]
The screenshot you linked is for a Google Analytics 4 account. Google analytics 4 accounts will not show up in the Universal Analytics Query Explorer. I suggest you try the [GA4 Query Explorer](https://ga-dev-tools.web.app/query-explorer/).

**Comment by BarryCap** [comment]
Thanks! It works with the GA4 Query Explorer.
