### ISSUE TITLE
Embed API Script Errors

### ISSUE THREAD

**Issue by AgathopAlex** [googleanalytics/ga-dev-tools#464]
I am receiving errors on the scripts for the Embed API code  
![image](https://user-images.githubusercontent.com/43377329/70774226-4479ac00-1d82-11ea-8318-8bc6ff5cadf0.png)

**Comment by diminishedprime** [comment]
Hi. There's not enough to go on to address this issue. If you're still facing this problem, feel free to re-open this issue & add in further detail.
