### ISSUE TITLE
The "Placement Domain" Dimension doesn't return click metrics

### ISSUE THREAD

**Issue by Sergeev1745** [googleanalytics/ga-dev-tools#466]
Hello!
I tried to get clicks and impression metrics for the Placement Domain dimension, but Query Explorer does not return any value.
I checked it on the bunch of Google Analytics accounts and each time I got the same result. 
![Screenshot_4](https://user-images.githubusercontent.com/19285101/72085365-da670f00-330d-11ea-9dcd-d3de5acee882.jpg)

**Comment by diminishedprime** [comment]
Hi, could you elaborate on the problem you're facing here? What's the expected behavior vs actual behavior?

**Comment by diminishedprime** [comment]
This issue has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.
