### ISSUE TITLE
Is app+web supported in the GA Account Explorer app?

### ISSUE THREAD

**Issue by gerrywest** [googleanalytics/ga-dev-tools#468]
Simple Question:
Is app+web supported in the GA Account Explorer app?

I'm not seeing the Account/Property pair for any of our apps using 'app+web' tracking in GA Account Explorer.

OR is this an issue with insufficient access rights to the app via GA?

Thanks
GErry

**Comment by diminishedprime** [comment]
Yes, it is supported.
