### ISSUE TITLE
Unable to query fields ga:adContent and ga:transactionID together

### ISSUE THREAD

**Issue by cooldude679** [googleanalytics/ga-dev-tools#470]
According to Google API Dimensions & Metrics Explorer, we should be able to query fields ga:adContent and ga:transactionID together.

See:
https://ga-dev-tools.appspot.com/dimensions-metrics-explorer/

When i try to query the fields together, it gives an error "400 - Selected dimensions and metrics cannot be queried together." 

This is a big issue - being able to associate Ad content with Transaction ID is fundamental in eCommerce  and UTM (e.g. being able to determine which advertisement led to an order).

![image](https://user-images.githubusercontent.com/43767825/74249645-7a220f00-4cb7-11ea-9eb0-d263b1cfb98a.png)

**Comment by diminishedprime** [comment]
This issue has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.

**Comment by fleko** [comment]
Hey there @diminishedprime, I'm facing the same issue. Any way to re-open? Need to know if this is a problem with the API or with the metrics explorer. As @cooldude679 mentioned, this association is important in UTM/ecommerce, and it's actually doable in GA4.
