### ISSUE TITLE
Updated Query Explorer Interface

### ISSUE THREAD

**Issue by aprince** [googleanalytics/ga-dev-tools#49]
Seems to be a big step backwards - making it prettier at the cost of actual functionality. And no, the addition of 'sampling level' does not make up for it. 
First thing I tried to do was paste in pre-defined sets of metrics and dimensions, the interface lagged and had difficulty processing the string and breaking it up into visually appealing 'pills'. 

The Query explorer has previously been a great place to run very fast little tests and checks - the new interface kills much of that.

**Comment by philipwalton** [comment]
@aprince a lot of new functionality was added in addition to the "samplingLevel" field. Issue #35 details the complete list of new features, and as you can see, many of these features were requested by users.

In terms of the specific bug you mentioned, that has been fixed in #50.
