### ISSUE TITLE
Getting Blank Embed API Third Party Visualizations

### ISSUE THREAD

**Issue by maulayyacyber** [googleanalytics/ga-dev-tools#506]
im getting blank page on Embed API Third Party Visualizations
<img width="1392" alt="Screen Shot 2020-05-21 at 14 34 59" src="https://user-images.githubusercontent.com/11194525/82534983-58ff7300-9b70-11ea-9e82-def601eeaf3b.png">

**Comment by coliff** [comment]
The Third Party Visualizations demo stopped working recently too. Can you open up console in Developer Tools and post a screenshot of the errors?

**Comment by coliff** [comment]
This is fixed now. You close the issue if it’s resolved for you.
