### ISSUE TITLE
Add support for creating a hit with Google Optimize experiments

### ISSUE THREAD

**Issue by wuservices** [googleanalytics/ga-dev-tools#507]
There's official documentation at https://developers.google.com/optimize/devguides/experiments#add-ga-tracking-code-to-variations that says to set exp to send a Google Optimize experiment and variation to Google Analytics using `exp`, however the hit builder and protocol reference don't mention this.

It would be helpful if the hit builder supported this.

Separate from dev tools, it would be great if the documentation was also current, and if there was an example of how to send data for multiple experiments at once.

**Comment by diminishedprime** [comment]
This issue has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.
