### ISSUE TITLE
Bit.ly account will not refresh

### ISSUE THREAD

**Issue by rebechah** [googleanalytics/ga-dev-tools#508]
Hello! I'm reaching out because I can't seem to disconnect the bit.ly account I used for a client with the UTM builder. So far I've completely cleared my cache, cookies, and logged into different bit.ly accounts. If I use the UTM builder with another computer or incognito it doesn't have the same issue.

**Comment by diminishedprime** [comment]
I believe the only way to do this currently is to go to your bitly account -> **profile settings** -> **security** -> **Linked Apps**, then to remove "Google Analytics & Tools" from there. 

Not sure why this feature hasn't been requested yet! We can definitely look into making it easier to revoke the connected account.

**Comment by rebechah** [comment]
Hey Matt! 

Thank you for getting back to me so promptly. I tried this method and I still seem to be connected to the previous bit.ly <http://bit.ly/> account even though I don’t actually have access to it anymore. Is there any way to revoke this access without being logged into the said bit.ly <http://bit.ly/> account?

I really appreciate all of your help. Thank you, again.


Rebecha Herman
rebechah@icloud.com

**Comment by diminishedprime** [comment]
Another option should be to clear your local storage for the site. If you're not familiar how to do this, [this question](https://superuser.com/questions/519628/clear-html5-local-storage-on-a-specific-page) shows a way to do it for Google Chrome.

Also, make sure when you re-authorize bitly you're logged into the correct bitly account. The bitly authorization page should show who you're logged in as at the bottom.

**Comment by rebechah** [comment]
This last method worked! Thank you, again, Matt. 
I wasn’t aware of this site-data feature on chrome prior to this. I really appreciate the help and knowledge. 

Rebecha Herman
rebechah@icloud.com
(469) 438-3594
