### ISSUE TITLE
account-explorer menú loading issue

### ISSUE THREAD

**Issue by zaguad** [googleanalytics/ga-dev-tools#515]
Hi everyone! When I go to "[Account explorer](https://ga-dev-tools.appspot.com/account-explorer/)" menu, the page got stuck loading forever, I already login and logout multiple times, delete cache, cookies, change to firefox, etc, but every time I try, the website start to load and never end.

thank you very much for read! 😃

<img width="1243" alt="Screen Shot 2020-06-19 at 23 21 07" src="https://user-images.githubusercontent.com/6466500/85190168-9b0cf900-b283-11ea-85c1-a487ce572480.png">

**Comment by diminishedprime** [comment]
Hi, I'm not able to reproduce this error. 

Could you open the developer console and paste in any logs, particularly ones that indicate an error?

Can you also let me know which OS & internet browser you are using?

**Comment by zaguad** [comment]
**diminishedprime** thank you so much for your reply.

This is an screenshot from my developer console 
![Screen Shot 2020-06-22 at 18 22 09](https://user-images.githubusercontent.com/6466500/85341137-7730f980-b4b5-11ea-84ab-94e0391aef08.png)

Im getting a lot of errors, also Im running MacOs Catalina, and last versión from Chrome and Firefox.

Thank you again for your kind reply. 😄

**Comment by diminishedprime** [comment]
Strange. I actually get those errors in my console as well, but the demo still works for me. I'm not really sure why the error shows up since it's from an old code-path that shouldn't be reached anymore. 

Can you try hard reloading with a disabled cache. To do that in chrome, open your developer tools, then right click on the refresh button and you'll see "Empty cache and hard reload". You might have an old cached version of the demo.

**Comment by zaguad** [comment]
I did it before, disabling cache, deleting cookies, everything, firefox and chrome install from scratch, but got the same result.

![Screen Shot 2020-06-22 at 19 05 50](https://user-images.githubusercontent.com/6466500/85343650-65eaeb80-b4bb-11ea-8bbf-17ce94cc391a.png)

Anyway, yesterday I could find the ID in the "Query explorer" menu to keep working on my project, I hope in the future this work for me, thank you very much!

**Comment by diminishedprime** [comment]
I pushed out a fix that I think resolves this issue. Can you try the account explorer again when you get a chance?

**Comment by zaguad** [comment]
Same error, another funny thing is when I change to Autotrack menu this error flash.

![Screen Shot 2020-06-26 at 03 33 13](https://user-images.githubusercontent.com/6466500/85832341-e3ce2180-b75d-11ea-8292-ae4d9fde1dcb.png)

If you need more log errors or something I would be glad to help!

**Comment by diminishedprime** [comment]
The autotrack page should be working now. I updated the production deployment with a service account that didn't have access to the analytics account so there were a few issues for demos that relied upon that data. 

Are you still having issues with the account explorer?

**Comment by zaguad** [comment]
Autotrack is working perfectly! Account explorer is with the same issue, thank you very much team!

**Comment by arounde** [comment]
I have the same issue - unable to get to the verification screen. 
"One moment please" with spinner, then disappears.
The Account Chooser screen does not even appear.
Chrome Version 85.0.4183.121 (Official Build) (64-bit)

Have cleared all cookies, signed out of all Google accounts, am only signed into the one I want to connect.
Tried Empty cache and hard reload

in Dev Tools > Issues, this appears on page load:
"Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute"

in Dev Tools > Console, this appears AFTER the verification is attempted:
"[Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: Paint Timing. "

In Safari, am able to connect with a different Google account completely.

In Firefox, am able to choose a Google account, but then it does not progress to the "allow this App" screen.
The following appears in the Console:

```
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
UA-41425441-5 event User signin auth 
Array(20) [ "dl=https://ga-dev-tools.appspot.com/account-explorer/", "dp=/account-explorer/", "dt=Account Explorer — Google Analytics Demos & Tools", "gjid=", "cid=xxx.xxx", "cd1=lg", "cd2=(not set)", "cd3=(not set)", "cd4=2x", "cd5=landscape", … ]
index.js:16773:49
UA-41425441-7 event User signin auth 
Array(20) [ "dl=https://ga-dev-tools.appspot.com/account-explorer/", "dp=/account-explorer/", "dt=Account Explorer — Google Analytics Demos & Tools", "gjid=", "cid=xxx.xxx", "cd1=lg", "cd2=(not set)", "cd3=(not set)", "cd4=2x", "cd5=landscape", … ]
index.js:16773:49
Storage access automatically granted for origin “https://accounts.google.com” on “https://ga-dev-tools.appspot.com”.
Cookie “SIDCC” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

**Comment by diminishedprime** [comment]
This should be resolved in the newest version of the site: https://ga-dev-tools.web.app/
