### ISSUE TITLE
Third Party Visualizations Demo not working

### ISSUE THREAD

**Issue by coliff** [googleanalytics/ga-dev-tools#517]
This was working correctly a few weeks ago, but is broken now. I've tested in Chrome, new Microsoft Edge (Windows 10) and also on macOS. Screenshot below with console errors. Looks like similar issue to #515

![image](https://user-images.githubusercontent.com/1212885/85513773-4f1cd400-b636-11ea-88cd-675ada2f7d93.png)

**Comment by dumalagrenzcarlo** [comment]
I am having the same issue. All the websites I maintain cannot view their analytics dashboard.

**Comment by JayCeee** [comment]
Same issue, since today, all the websites I maintain cannot view their analytics dashboard too.
That's because  https://ga-dev-tools.appspot.com/public/javascript/app.js is missing...
Please keep us update quickly  ! :)

**Comment by coliff** [comment]
pinging @philipwalton who hopefully can help.

**Comment by diminishedprime** [comment]
> Same issue, since today, all the websites I maintain cannot view their analytics dashboard too.
> That's because https://ga-dev-tools.appspot.com/public/javascript/app.js is missing...
> Please keep us update quickly ! :)

Just as a quick aside - You absolutely should not be relying on this website hosting a javascript file for any websites you maintain.

**Comment by diminishedprime** [comment]
And in regards to the demo being down, looks like some credentials didn't get published during the publish. Will look into fixing this asap.

But again, to emphasize, please don't rely on hosted assets from a website you don't control for your site to work correctly.

**Comment by diminishedprime** [comment]
I pushed a fix out that should resolve this issue. Please let me know if you still can now see your data.

**Comment by coliff** [comment]
All working now. Thanks for the fix (yes, I'll self-host the CSS and JS for this moving forward :-D )
