### ISSUE TITLE
Hit builder doesn't accept G-XXX identifiers.

### ISSUE THREAD

**Issue by luizbim** [googleanalytics/ga-dev-tools#524]
Hi. I'm trying to log some subscription conversion events from my server and I'm trying to accomplish that using . When I try to test my call with [Hit Builder](https://ga-dev-tools.appspot.com/hit-builder/) I get an error message saying that my parameter tid is not valid. 
My analytics uses the version App+Web and I've created a new **Data Stream -> Web** which have returned me an ID starting with **G-**

Hi. I'm trying to log some subscription conversion events from my server and to accomplish that using the [GA Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1). When I try to test my call with [Hit Builder](https://ga-dev-tools.appspot.com/hit-builder/) I get an error message saying that my parameter tid is not valid.
My GA uses the version App + Web and I've created a new DataStream -> Web which have returned me an ID starting with G-. I can't see my property starting with UA- and the [Hit Builder](https://ga-dev-tools.appspot.com/hit-builder/) doesn't accept the G- identification. 
Is this a bug or I'm trying to do this in the wrong way?
How can I resolve this issue?

**Comment by diminishedprime** [comment]
This is expected behavior. The hit Builder (and the measurement protocol) does not support App + Web properties. In the future, there will be a measurement protocol for App + Web properties, but it is still in development.

**Comment by luizbim** [comment]
Thank you for the fast answer @diminishedprime. Just to clarify, today there is no way to send server-to-server events to any app + web properties?

**Comment by diminishedprime** [comment]
That is correct.
