### ISSUE TITLE
Usage Trends - Couldn't able to use it

### ISSUE THREAD

**Issue by joinwitraj** [googleanalytics/ga-dev-tools#540]
Hello Team,

While try to check the features of Usage Trends. i couldn't able to use the tool as it loads infinitely. Could you go through it the issue.

![usage trends - ga dev tools](https://user-images.githubusercontent.com/17198628/90106924-b537f480-dd65-11ea-86a8-fffe53cf9dca.PNG)

Regards
Rajkumar K

**Comment by diminishedprime** [comment]
Usage trends is not supported in the newest version of the site: https://ga-dev-tools.web.app/
