### ISSUE TITLE
Inaccurate description of Ecommerce Conversion Rate

### ISSUE THREAD

**Issue by eunicey** [googleanalytics/ga-dev-tools#543]
In Dimensions and Metrics Explorer, Ecommerce Conversion Rate metric is defined as "The average number of transactions in a session." However, https://support.google.com/analytics/answer/6014872 defines it as "percentage of sessions that resulted in an ecommerce transaction" which makes a lot more sense.

**Comment by diminishedprime** [comment]
This issue has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.
