### ISSUE TITLE
Campaign URL builder

### ISSUE THREAD

**Issue by gyurilee** [googleanalytics/ga-dev-tools#547]
Hi, I've used campaign URL builder to shorten and insert GA tag.
Normally, I set campaign name in Korean to identify where the events come from, but sometimes the campaign characters become broken like this: campaign=kr_skii_RNAC_Ã«Â·Â°Ã¬Â£Â¼Ã«Â¯Â¸_2009_2w_AA

Could you check how can I solve this problem? or do I need to set the campaign name in English only?

Thanks in advance

**Comment by diminishedprime** [comment]
This issue has been inactive for quite a while so it's being closed due to inactivity. If you're still facing this issue, feel free to re-open.
