### ISSUE TITLE
Query Explorer: properties not listed

### ISSUE THREAD

**Issue by rhofvendahl** [googleanalytics/ga-dev-tools#550]
After authorizing Query Explorer, my accounts show up but not the properties for any account (the dropdown is empty). The app does the same thing when browsing as guest, on a different computer, using both firefox & chrome and when I set up an entirely seperate google account. Maybe it's an issue with the way I'm setting up google analytics?

**Comment by rhofvendahl** [comment]
Update: When I tried creating a "Universal Analytics" property (under advanced options) the property showed up. Query Explorer doesn't support Google Analytics 4, then? Is there any way to access my Google Analytics 4 data with Query Explorere?

**Comment by diminishedprime** [comment]
Not yet, but we're working actively working on updating the demos to work with Google Analytics 4.
