### ISSUE TITLE
Account Explorer

### ISSUE THREAD

**Issue by Ackerman5** [googleanalytics/ga-dev-tools#551]
Good day, 

After authorise on the account explorer it is almost like the page goes into a loop, normally it takes a couple of seconds, for it to authorise and it going on and on. please help i see in the attachment that i provided that it did not pull my property name through, not sure why. please help i have been struggling a while now, thanks
![Screenshot 2020-10-29 at 17 17 18](https://user-images.githubusercontent.com/73641894/97594452-5e0ffa80-1a0b-11eb-8a64-17fdf4e9347a.png)

**Comment by diminishedprime** [comment]
This is fixed in the newest version of the site: https://ga-dev-tools.web.app/
