### ISSUE TITLE
GA API Tool Issue

### ISSUE THREAD

**Issue by chrisritzenthaler** [googleanalytics/ga-dev-tools#56]
New tool does not allow GoalXXConversions to be edited unless you type in the full line, defeating the purpose of the new search function.   Curently puts the metric as GoalXXConversions which isn't a valid metric and isn't editable if you don't type the entire thing out yourself.

![image](https://cloud.githubusercontent.com/assets/11839748/7029085/8467aa5a-dd0f-11e4-90f5-9a43d1b3e967.png)

Thanks

**Comment by philipwalton** [comment]
Yeah, this annoys me as well, but unfortunately there aren't a lot of open source typeahead / select widgets that support this use case. We're using [select2](https://select2.github.io/), and the new version will handle this better, but until it's out of beta we're stuck with the existing functionality.

One way we can improve this now is to use API methods like [`analytics.management.goals.list`](https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/goals/list), [`analytics.management.customMetrics.list`] (https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/customMetrics/list), and [`analytics.management.customDimensions.list`](https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/customDimensions/list) to populate the items in the select2 dropdown.

This is a feature I'd like to add at some point, so I'll keep this issue open to track it.

**Comment by philipwalton** [comment]
Circling back here, this is supported now. It was added in https://github.com/googleanalytics/ga-dev-tools/pull/66.
