### ISSUE TITLE
pycrypto pycryptodome / webpack

### ISSUE THREAD

**Issue by wluijk** [googleanalytics/ga-dev-tools#561]
Can the project been updated on more recent versions of pycrypto and webpack and gapi.auth2?
When i follow the instructions i got many stuck in search for workarounds / updates etc.

**Comment by diminishedprime** [comment]
We are currently in the process of re-writing this code base to no longer rely on python so once that work has landed this will no longer be an issue. If you're interesting in running the (in-progress migration) can can checkout the branch for #488 -- any feedback on the developer workflow or places that could use clarification are welcome.

**Comment by diminishedprime** [comment]
The new site is live here: https://ga-dev-tools.web.app/ and the repo is updated accordingly. Hopefully the gapi code makes sense to you!
