### ISSUE TITLE
Account Explorer keep loading

### ISSUE THREAD

**Issue by ljchok** [googleanalytics/ga-dev-tools#565]
When I access this page it keep loading. https://ga-dev-tools.appspot.com/account-explorer/

I clicked Account Explorer from here: https://developers.google.com/analytics/devguides/collection/ios/v3/campaigns#url-builder. 

![Uploading Screenshot 2020-12-30 at 7.47.27 PM.png…]()

**Comment by diminishedprime** [comment]
This is fixed in the new version of the site: https://ga-dev-tools.web.app/
