### ISSUE TITLE
ga:dateHour has wrong formatting

### ISSUE THREAD

**Issue by Bvz2001** [googleanalytics/ga-dev-tools#58]
**ga:dateHour** dimension value contains date + hour, while it is formatted to date only.
I think it should be more like: `moment().format('DD MMM YYYY, HH:mm')`

![image](https://cloud.githubusercontent.com/assets/1611259/7047887/28c379e0-de18-11e4-992b-d0c4de7f01ea.png)

**Comment by philipwalton** [comment]
Interesting. It looks like the standard [output](https://developers.google.com/analytics/devguides/reporting/core/v3/reference#output) format for this dimension is "YYYYMMDDHH", but when it's returned with the [output](https://developers.google.com/analytics/devguides/reporting/core/v3/reference#output) parameter set to `'dataTable` it returns the string `'Date(2015, 02, 23, 15, 55, 0)'` (in the case of the first row from your screenshot above).

It seems like the Embed API uses the `'medium'` options for its [date formatter](https://developers.google.com/chart/interactive/docs/reference#dateformatter) when displaying Google Visualization table charts. I'll look into seeing if it's possible to generalize this so it works for all date dimensions.

**Comment by Lucretiel** [comment]
Confirmed that this is an API bug, not a client bug. Reported here: https://issuetracker.google.com/71911639

**Comment by Lucretiel** [comment]
This bug should be fixed now
