### ISSUE TITLE
GA4 Event Buider - purchase - wrong initial params

### ISSUE THREAD

**Issue by alonnberg** [googleanalytics/ga-dev-tools#580]
I noticed that the GA4 Event Bulider in the tool have a "bug" for "purchase". 

It adds a default set of parameters, one I think should be "transaction_id". However, it says "transactions_id" and maybe you have added it like that so a tester will learn how to debug, but it feels like a bug and is prone to "learn" visitors the wrong key for the transaction id.

If the "buggy default parameters" is on purpose, please add a note of that atleast. But I suggest you fix it to the correct instead.

URL: https://ga-dev-tools.appspot.com/ga4-event-builder/

**Comment by diminishedprime** [comment]
This issue is resolved in the new version of the site: https://ga-dev-tools.web.app/ga4/event-builder/
