### ISSUE TITLE
Typo on Embed API Server-side Authorization demo page

### ISSUE THREAD

**Issue by Tyler-Hong** [googleanalytics/ga-dev-tools#581]
On this page: 
https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/

The comment in the code section of **Step 6** has a typo:

~~chart-3-container~~ &#8594; chart-2-container
![image](https://user-images.githubusercontent.com/35193760/113670077-3d00b380-96e7-11eb-82db-1e13a57b92b8.png)

**Comment by diminishedprime** [comment]
This demo is no longer supported on the new site so closing this bug. 

See https://ga-dev-tools.web.app for the new site.
