### ISSUE TITLE
Guided demos? Our team would love to know more

### ISSUE THREAD

**Issue by marinaako** [googleanalytics/ga-dev-tools#587]
Our team is looking to optimize our use of Google Analytics. Is there a resource to talk a representative to walk through using the tools and different capabilities in this dashboard?

**Comment by diminishedprime** [comment]
This repository is not designed for general help requests; it is only for reporting issues and requesting features for code contained in this repo. See [this link](https://support.google.com/analytics/answer/9026876/how-to-get-support?hl=en) for analytics support.
