### ISSUE TITLE
Account explorer keeps loading forever

### ISSUE THREAD

**Issue by christianjavan** [googleanalytics/ga-dev-tools#588]
Has anyone solved this? I have the same issue, no errors on console, it shows my account, but no properties are displayed in the box nor view. I´m using brave, already disabled the brave shields, I tried to do it in a private windows to ensure no pluggins where involved

![image](https://user-images.githubusercontent.com/4475349/115796503-c7ebda00-a386-11eb-9058-6eff5fa37ae7.png)
![image](https://user-images.githubusercontent.com/4475349/115796556-e0f48b00-a386-11eb-8b16-4b22441e4e25.png)
![image](https://user-images.githubusercontent.com/4475349/115796603-f7024b80-a386-11eb-981a-b41194835fd6.png)

**Comment by diminishedprime** [comment]
This issue should be resolved on the new site: https://ga-dev-tools.web.app
