### ISSUE TITLE
Module loading error with view-selector2.js

### ISSUE THREAD

**Issue by TimeTravellingExplorer** [googleanalytics/ga-dev-tools#592]
I'm setting up the sample code found at https://ga-dev-tools.appspot.com/embed-api/third-party-visualizations/ and I'm getting an error `SyntaxError: import declarations may only appear at top level of a module` on line 19 of view-selector2.js where it attempts to import `import accountSummaries from 'javascript-api-utils/lib/account-summaries';`

I was looking up what the issue might be and noticed that javascript-api-utils is deprecated, is this example out of date or is something wrong with my setup? I've copied the code exactly from the example. 

I'm working with ASP.NET Core 5, and I've added all of the example components used in that example to my project.

**Comment by diminishedprime** [comment]
We no longer recommend using the embed api. For most cases, [datastudio](https://datastudio.google.com) + embedded reports is a better solution.
