### ISSUE TITLE
Feature Request: provide access to the GTM account

### ISSUE THREAD

**Issue by yoraysa** [googleanalytics/ga-dev-tools#6]
Hi there,
not sure if this is the right place to ask, but an access to the GTM account for the enhanced ecommerce demo will be helpful. to see how things has been done behind the scene of GTM.

one thing i'm willing to know is how the GTM send the GA hit in POST
https://enhancedecommerce.appspot.com/

the access may be provided via general user or gtm api where users can give themselves view access directly from the demo page.

*same thing can be done for the GA account
cheers,

p.s
beautiful project! :+1:

**Comment by Lucretiel** [comment]
Unfortunately, due to scalability issues we probably won't be able to give direct access (even read-only access) to the GTM or GA account for the enhanced ecommerce demo.

In any case, If there is continued interest in this kind of feature, please voice it in this thread.
