### ISSUE TITLE
Is GA4 designed to be used on browser too? 'cause it exposes the api_secret

### ISSUE THREAD

**Issue by softmarshmallow** [googleanalytics/ga-dev-tools#604]
Is GA4 protocol designed to be used on server side only or universal? 'Cause if it's designed for browser as well, I'm curious if it is ok for the `api_secret` to be exposed by developer tool (in the requeset query)

**Comment by diminishedprime** [comment]
The GA4 Measurement Protocol is best used server-side. While it is technically okay to use it in the browser, in most (all?) web contexts, you should be using either GTM or gtag.js to send analytics data.

**Comment by softmarshmallow** [comment]
Yeah, but my web client is a embeded environment and cannot us gtag.js or sort of prebuilt js sdks.
I'm making a simple proxy server just to secure the api_secret.
>  I'm curious if it is ok for the api_secret to be exposed by developer tool (in the requeset query)
I hope you can answer this too!?

:)

**Comment by diminishedprime** [comment]
It is okay to expose the api_secret. Conceptually it's no different than exposing your measurement ID. It _does_ open the risk of someone sending spam, but based on the [api_secret docs](https://developers.google.com/analytics/devguides/collection/protocol/ga4/reference?client_type=gtag#api_secret) as long as you rotate this secret occasionally, it should be fine.
