### ISSUE TITLE
Account explorer keeps loading forever

### ISSUE THREAD

**Issue by katbast** [googleanalytics/ga-dev-tools#606]
Hi, i have seen others have the same issue, the account explorer just stays loading forever and has errors in the log console, it looks like its looping through this account, but i have checked and i don't have that account id on my analytics panel.

![image](https://user-images.githubusercontent.com/22032807/120105642-7241e480-c11f-11eb-9468-91e61872dfa3.png)

i really need to configure my api and i got no idea where i can find my view-id since i have analytics 4 and it doesn't show in the admin panel.

Thanks

**Comment by diminishedprime** [comment]
GA4 no longer has View Ids. See this SO question: https://stackoverflow.com/questions/64510635/how-do-i-get-view-id-from-google-analytics-4

Either way, the account explorer doesn't support GA4 properties. There is a new version here that should resolve the loading issue: https://ga-dev-tools.web.app/account-explorer/
