### ISSUE TITLE
The calendar is a bit cheesy

### ISSUE THREAD

**Issue by BarryCap** [googleanalytics/ga-dev-tools#612]
The calendar that can be seen in the [Query Explorer](https://ga-dev-tools.appspot.com/query-explorer/) is not in the same aesthetic as the rest of the website. I think it could be changed to something better, at least without those big grey gradients.

![calendar](https://user-images.githubusercontent.com/63713811/121219128-ab96f480-c883-11eb-81b5-c9c2febcb2c8.png)

**Comment by diminishedprime** [comment]
The [new version of the query explorer](https://ga-dev-tools.web.app/query-explorer/) doesn't have any calendar pop-ups so this is a non-issue for now. The one you linked to is no longer being actively developed.

**Comment by BarryCap** [comment]
If the old version of the query explorer is not actively developed and was replaced, why do we still end up on it?

**Comment by diminishedprime** [comment]
We're currently working on setting up redirects from the old site to the new. The new site is available (if you follow the link above), but the redirects aren't live yet.
