### ISSUE TITLE
503 or 500 error

### ISSUE THREAD

**Issue by justislav** [googleanalytics/ga-dev-tools#62]
I've been getting lots of 500 & 503 errors recently

https://dl.dropboxusercontent.com/u/9823550/appcraft/Screenshot%20from%202015-04-18%2019%3A46%3A51.png

There was an internal error.
There was a temporary error. Please try again later.

What is it?

**Comment by philipwalton** [comment]
Is this still happening?

**Comment by justislav** [comment]
It's all OK by now.

Still there are no comments or whatever from Google at https://goo.gl/vfeKNp
and similar submits https://goo.gl/3GLg81 https://goo.gl/pP2cG7
