### ISSUE TITLE
Response JSON tab in Request Composer isn't working

### ISSUE THREAD

**Issue by SkylarMacias** [googleanalytics/ga-dev-tools#621]
Showing this error:

Warning: Failed prop type: The prop `onSelect` is marked as required in `Tabs`, but its value is `undefined` or `null`.
`onSelect` is required when `selectedIndex` is also set. Not doing so will make the tabs not do anything, as `selectedIndex` indicates that you want to handle the selected tab yourself.
If you only want to set the inital tab replace `selectedIndex` with `defaultIndex`.
    in Tabs (created by ResultsViewer)
    in ResultsViewer (created by RequestComposer)
    in div (created by RequestComposer)
    in RequestComposer (created by ConnectFunction)
    in ConnectFunction
    in Provider

**Comment by diminishedprime** [comment]
This issue is fixed in the [new version of demos & tools](https://ga-dev-tools.web.app/request-composer/)

**Comment by SkylarMacias** [comment]
Yep, was just coming back to say sorry, I was using the old one. Thank you.
