### ISSUE TITLE
Issue with utm builder

### ISSUE THREAD

**Issue by CPMmediateam** [googleanalytics/ga-dev-tools#622]
We love using your utm builder and we are so grateful you created it, however, in the past couple weeks we have noticed a glitch. It has been adding a # symbol in front of the utm_source in the link. As a result, our forms are not capturing the utm source when we use bit.ly's from the utm builder. Is there any way this can be fixed?

**Comment by diminishedprime** [comment]
It will add `#` character if you have the "Set campaign parameters in the fragment protion of the URL" box checked. To make it not generate the `#` character, make sure that checkbox is unchecked.
