### ISSUE TITLE
Query explorer download and link share isn't working

### ISSUE THREAD

**Issue by moi-stern** [googleanalytics/ga-dev-tools#629]
When I try to download the results I obtain in the query explorer as a TSV file, I simply get a "csvhandler.html" file downloaded - which is empty. I'm not sure if I need to do something with this file, but I can't find any indication of it in the docs. Also, when I try to share the direct link or even look up the direct link in my browser, the query explorer home page comes up and not the data I want to share. Any help here would be greatly appreciated!

**Comment by diminishedprime** [comment]
This isn't relevant any more in the current version of the tool.
