### ISSUE TITLE
Chrome freezing even in anonymous mode when try to authorize account

### ISSUE THREAD

**Issue by hashik** [googleanalytics/ga-dev-tools#63]
Hey,

whenever I try to login, after selection of account and type in of my credentials, I get back to QE and Chrome freeze (with a blue bar stopped somewhere in the middle).

From chrome console I can see this:
Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

Different people with different computers got the same error. Could you please look at this or tell me what more do you want me to do for some additional debugging?

Thank you very much,

Vojta

**Comment by philipwalton** [comment]
Hmmm, I haven't seen this, but it sounds like there are some security limitation from accessing local storage in private browsing mode.

I tried reproducing the error but couldn't based on what you said. Can you see if you can reliably reproduce it and let me know the exact steps you took?

**Comment by hashik** [comment]
Everything is working now, thanks.
