### ISSUE TITLE
https://ga-dev-tools.appspot.com/public/javascript/embed-api/components/view-selector2.js is not accessible

### ISSUE THREAD

**Issue by yugox-deepak** [googleanalytics/ga-dev-tools#634]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by diminishedprime** [comment]
This was never supposed to code you directly depend on for other websites. It was only code used for this website. If you're interested in continuing to use this code, you can copy it from previous commits in this repo.
