### ISSUE TITLE
New version of query explorer : Impossible to test our queries because of custom dimensions

### ISSUE THREAD

**Issue by Marie-Les** [googleanalytics/ga-dev-tools#635]
**Describe the bug**
Compared to the previous version, I can't test my queries : when I want to use a custom dimension in particular (imagine : ga:dimension10), it blocks and only enables me to enter ga:dimensionXX. 
Thus, query won't load. 

**To Reproduce**
1. Go to 'https://ga-dev-tools.web.app/query-explorer/'
2. Enter a custom dimension in dimension : imagine : ga:dimension10
3. Enter no matter what metrics and other parameters

**Expected behavior**
Enter a precise number of custom dimension (allow us to replace the "XX")

Thanks !

**Comment by diminishedprime** [comment]
duplicate of #632
