### ISSUE TITLE
View Selector and Date Range Selector JavaScript files missing

### ISSUE THREAD

**Issue by alsjohnstone** [googleanalytics/ga-dev-tools#638]
I was using the files below in a project but they are now just redirecting to https://ga-dev-tools.web.app/. Do you know where can I find these files to download?

```
<!-- Google's Embed API scrips-->
<script src="https://ga-dev-tools.appspot.com/public/javascript/embed-api/components/date-range-selector.js"></script>
<script src="https://ga-dev-tools.appspot.com/public/javascript/embed-api/components/view-selector2.js"></script>
```

**Comment by diminishedprime** [comment]
These files are available via the commit history of this project. You may have to build the project as of a past commit hash in order to get them.
