### ISSUE TITLE
Direct link to this Report fails

### ISSUE THREAD

**Issue by justislav** [googleanalytics/ga-dev-tools#64]
Direct link to this Report returns nonempty segment while it's empty in request setup fields

https://ga-dev-tools.appspot.com/query-explorer/?start-date=30daysAgo&end-date=yesterday&metrics=ga%3Ausers%2Cga%3Atransactions%2Cga%3AeventValue%2Cga%3AtotalEvents%2Cga%3AtransactionRevenue&dimensions=ga%3AeventAction&segment=users%3A%3Acondition%3A%3Aga%3Atransactions%3E0

https://dl.dropboxusercontent.com/u/9823550/appcraft/Screenshot%20from%202015-04-28%2008%3A48%3A57.png

**Comment by justislav** [comment]
BTW ga-dev-tools runs request with segment with empty segment field thus data returned is wrong: e.g. users are 0

**Comment by philipwalton** [comment]
@justislav, as you know, there are issue with the select2 plugin. I'm working to replace it.

Would you be interesting in beta testing a new version and giving feedback once we have something up and running?

**Comment by philipwalton** [comment]
I cannot reproduce this error as of [7.0.0](https://github.com/googleanalytics/ga-dev-tools/releases/tag/7.0.0), so I believe the recent changes have fixed it. Feel free to re-open if you're still having problems.

**Comment by justislav** [comment]
Philip,

Thank you for the help & all the answers! I don't think I could help you
with beta testing due to we've bult our own similar tool. We had used
ga-dev-tool really a lot. It was very helpful for us. And for now our
business have grown up a little & the use cases have become more specific.

Good luck,
Justislav
