### ISSUE TITLE
No longer able to use  custom dimension in UA Query Explorer

### ISSUE THREAD

**Issue by hurbanom** [googleanalytics/ga-dev-tools#642]
**Describe the bug**
The updated version of UA Query Explorer is not accepting/showing custom dimensions entered for the query.

**To Reproduce**
1. Go to 'https://ga-dev-tools.web.app/query-explorer/'
2. Provide your account,property,view and start/end dates
3. Enter 'ga:users' for the metric
4. Enter 'ga:dimension1' for the dimension and that name dissapears
5.  Run the query

**Expected behavior**
The results show display the custom dimension but only show the number of users and in the dimension's input should appear the custom dimension name.

**Screenshots**
![image](https://user-images.githubusercontent.com/13169697/126392109-5f7677f3-dc15-4e71-8964-3e4d4b072b48.png)
![image](https://user-images.githubusercontent.com/13169697/126392178-857300c1-100f-40f0-b1e5-db15d59b708e.png)
![image](https://user-images.githubusercontent.com/13169697/126392522-470f4218-8f48-46d9-95d7-149440a216ba.png)

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: Chrome
 - Version: 91.0.4472.

**Comment by diminishedprime** [comment]
This was fixed early today and should be deployed soon.
