### ISSUE TITLE
loss of functionality - no Export Button and no report url generator

### ISSUE THREAD

**Issue by schuckfandre** [googleanalytics/ga-dev-tools#648]
The new version of query explorer lost some important and extremely practical features:

- Download data more easily;

- An option to include the access token when generating the request url for the API;
- Generate a url that "saves" different request options (enabling the user to more easily access request templates already created by him or others).

I.E.
In the previous version it was possible to generate a url similar to the url below and share/save it to access different report templates.

`https://ga-dev-tools.web.app/query-explorer/?ids=id&start-date=startDate&end-date=endDate&metrics=metrics&dimensions=dimensions&filters=filters`

I believe the intent of Query Explorer is to enable developers to test and see how the data will be made available when making an API call, but it turns out to be a very useful tool for those without programming knowledge as well.

**Comment by anmiles** [comment]
Agree, this was very useful feature, it allowed to copy a permalink on the report with all pre-filled fields and send it to someone. Current version doesn't allow to do this, could you please bring this back?
