### ISSUE TITLE
Will be nice to have a working demo of creating experiments using GA API

### ISSUE THREAD

**Issue by shalintripathi** [googleanalytics/ga-dev-tools#65]
Thanks

**Comment by philipwalton** [comment]
Thanks for the suggestion. We'll see if we can work that in.

**Comment by Igcorreia** [comment]
+1

**Comment by thallysondias** [comment]
+1

**Comment by Lucretiel** [comment]
Hey guys: I'm planning out work and new feature for Dev Tools for Q3. Is there still interest in this feature?

**Comment by Lucretiel** [comment]
I'll point out that Analytics Content Experiments have been deprecated in favor of Google Optimize, so I'm going to mark this as obsolete unless there is substantial interest in it.
