### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by GraphicProducts1970** [googleanalytics/ga-dev-tools#652]
In the Campaign URL Builder, "Set campaign parameters in the fragment protion of the URL (not recommended) *PORTION is misspelled.

Go to
https://ga-dev-tools.web.app/campaign-url-builder/

![image](https://user-images.githubusercontent.com/87864878/126792435-e888f7b3-f65e-4bb6-bf7c-6497b0a8779d.png)

Thanks

**Comment by diminishedprime** [comment]
Thanks, fixed!
