### ISSUE TITLE
I was using this link to show google analytics in my dashboard but no it show me some error

### ISSUE THREAD

**Issue by clubcodetown** [googleanalytics/ga-dev-tools#661]
I am facing an issue related to the viewSelector2.js file
I am using this link "https://ga-dev-tools.appspot.com/public/javascript/embed-api/components/view-selector2.js" but now it redirects to some other page and causing an issue for me. as now view selector is not available which have id and that I need to go with analytics API
Please let me know if have any solution for this issue

Thanks :)

**Comment by diminishedprime** [comment]
Hi, 

That code is deprecated. If you still need it for your own use, you can checkout a previous commit where it was still included and include the source code in your project as necessary.

**Comment by clubcodetown** [comment]
Thanks, @diminishedprime for your quick response
https://github.com/googleanalytics/ga-dev-tools/tree/4fdf63087ae52a0e17a72274e06a2b9e841af4f2
I downloaded the file before this version and put it on my server to check it but it seems not working
It gives me errors like this
"Uncaught SyntaxError: Cannot use import statement outside a module"

![Screenshot from 2021-08-12 18-58-37](https://user-images.githubusercontent.com/88352220/129205253-80d436d0-8afa-44fb-b77c-b79f97d9387b.png)

this error is in view-selector2.js file

**Comment by UmerFarooq78699** [comment]
I was having the same issue but I have made some changes to my code and things started working.

Firstly I removed the 
`<script type="text/javascript" src="https://ga-dev-tools.appspot.com/public/javascript/embed-api/components/view-selector2.js"></script>`

Second I updated the 
`var viewSelector = new gapi.analytics.ext.ViewSelector2({
            container: 'view-selector-container',
        }).execute();`

With
`var viewSelector = new gapi.analytics.ViewSelector({
            container: 'view-selector-container',
        });`

`gapi.analytics.auth.on('success', function(response) {
              viewSelector.execute();
            });`

Let me know if this helps.
