### ISSUE TITLE
Can't load the page

### ISSUE THREAD

**Issue by ksgremes** [googleanalytics/ga-dev-tools#663]
Hi,

I'm trying to access the query explorer, but am being redirected to a blank page.

Whenever I load the page, there is message "checking if you're logged in" for some time, and then the page goes blank.

Also, I can't use the "metrics & views" explorer (the page loads, but the content don't)

**Comment by diminishedprime** [comment]
Please recreate this bug, but use [this template](https://github.com/googleanalytics/ga-dev-tools/issues/new?assignees=&labels=&template=bug_report.md&title=)
