### ISSUE TITLE
Bitly integration on Campaign URL Builder

### ISSUE THREAD

**Issue by 2AJennJ** [googleanalytics/ga-dev-tools#664]
**Describe the bug**
After building out a tracking code, the site is unable to shorten the URL via Bitly

**To Reproduce**
1. Go to Campaign URL Builder
2. Complete the required fields
3. Click "SHORTEN URL"
4. Site displays Generated URL with semi-transparent characters over the first part of the link

**Expected behavior**
A shortened URL from Bitly should be available to share

**Screenshots**
SCREENSHOT ATTACHED

**Desktop:**
- MacBook Pro (16-inch, 2019)
 - Google Chrome
 - Version 92.0.4515.131 (Official Build) (x86_64)

**Additional context**

<img width="587" alt="Screen Shot 2021-08-03 at 11 41 36 AM" src="https://user-images.githubusercontent.com/88394384/128053754-01e01dfa-98c4-4bf8-b57f-484843c497a4.png">

**Comment by 2AJennJ** [comment]
So far, it's been every time. I had just updated Chrome and reconnected my Bitly account before it happened. Trying on Safari and Firefox now to see if it's an issue there as well.

**Comment by 2AJennJ** [comment]
https://user-images.githubusercontent.com/88394384/128073930-1d6d33bf-d954-4c85-9d28-dcb4ef8eb340.mov

I cleared my cache and restarted my computer, but I'm still experiencing the same issue.

**Comment by diminishedprime** [comment]
Hmm, I'm not sure what the issue is. Can you check your network tab & console to see if there are any errors there? My best guess is that the bitly request isn't working, but I'm not sure.

**Comment by diminishedprime** [comment]
I recently updated the tools to have improved error messaging. Please try again. Feel free to reopen if the new error message doesn't help you fix your problem.
