### ISSUE TITLE
idpiframe_initialization_failed"

### ISSUE THREAD

**Issue by VikasTandon** [googleanalytics/ga-dev-tools#671]
Not a valid origin for the client: http://127.0.0.…egister this origin for your project's client ID

cb=gapi.loaded_0?le=ili,ipu:218 Uncaught {error: "idpiframe_initialization_failed", details: "Not a valid origin for the client: http://127.0.0.…egister this origin for your project's client ID."}
(anonymous) @ cb=gapi.loaded_0?le=ili,ipu:218
setTimeout (async)
_.nj @ cb=gapi.loaded_0?le=ili,ipu:218
(anonymous) @ cb=gapi.loaded_0?le=ili,ipu:233
Kj @ cb=gapi.loaded_0?le=ili,ipu:225
Promise.then (async)
Fj @ cb=gapi.loaded_0?le=ili,ipu:225
_.Jj @ cb=gapi.loaded_0?le=ili,ipu:225
ck @ cb=gapi.loaded_0?le=ili,ipu:232
Lj @ cb=gapi.loaded_0?le=ili,ipu:231
(anonymous) @ cb=gapi.loaded_0?le=ili,ipu:226
(anonymous) @ cb=gapi.loaded_0?le=ili,ipu:351
lv.dispatchEvent @ cb=gapi.loaded_0?le=ili,ipu:261
_.hw.zv @ cb=gapi.loaded_0?le=ili,ipu:296
(anonymous) @ cb=gapi.loaded_0?le=ili,ipu:288
_.h.OX @ cb=gapi.loaded_0?le=ili,ipu:283
(anonymous) @ cb=gapi.loaded_0?le=ili,ipu:285
cb=gapi.loaded_0?le=ili,ipu:218 Uncaught {error: "idpiframe_initialization_failed", details: "Not a valid origin for the client: http://127.0.0.…egister this origin for your project's client ID."}
(anonymous) @ cb=gapi.loaded_0?le=ili,ipu:218
setTimeout (async)
_.nj @ cb=gapi.loaded_0?le=ili,ipu:218
(anonymous) @ cb=gapi.loaded_0?le=ili,ipu:233
Kj @ cb=gapi.loaded_0?le=ili,ipu:225
Promise.then (async)
Fj @ cb=gapi.loaded_0?le=ili,ipu:225
_.Jj @ cb=gapi.loaded_0?le=ili,ipu:225
ck @ cb=gapi.loaded_0?le=ili,ipu:232
Lj @ cb=gapi.loaded_0?le=ili,ipu:231
(anonymous) @ cb=gapi.loaded_0?le=ili,ipu:226
(anonymous) @ cb=gapi.loaded_0?le=ili,ipu:351
lv.dispatchEvent @ cb=gapi.loaded_0?le=ili,ipu:261
_.hw.zv @ cb=gapi.loaded_0?le=ili,ipu:296
(anonymous) @ cb=gapi.loaded_0?le=ili,ipu:288
_.h.OX @ cb=gapi.loaded_0?le=ili,ipu:283
(anonymous) @ cb=gapi.loaded_0?le=ili,ipu:285

**Comment by diminishedprime** [comment]
Please recreate this bug, but use [this template](https://github.com/googleanalytics/ga-dev-tools/issues/new?assignees=&labels=&template=bug_report.md&title=).
