### ISSUE TITLE
Unable to determine if I'm logged in

### ISSUE THREAD

**Issue by glennanj1** [googleanalytics/ga-dev-tools#672]
**Describe the bug**
directed to use link to https://ga-dev-tools.web.app/account-explorer/ to go to account explorer and grab my view id. 

**To Reproduce**
Edit: You need to disable 3rd party cookies to replicate. 
1. Go to https://ga-dev-tools.web.app/account-explorer/
2. Click on account explorer link in step 2
3. Wait for account-explorer to stop loading

**Expected behavior**
Expect to be able to login to account explorer to retrieve the view id for my api I'm building.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 (Latest Release) 21H1
 - Browser Chrome (Latest Release) Version 92.0.4515.131 (Official Build) (64-bit)

**Additional context**
It appears to be a session cookie issue. It's not recognizing I'm signed into my google account / google analytics account. I tried signing in and out of my account. I also tried clearing cookies and issue persists.

**Comment by glennanj1** [comment]
I was trying to access my account explorer for my google analytics account. Turns out since my property wasn't a universal analytic account I wasn't able to view the account explorer home page. That's my best guess. It's working now since making a clone property and enabling universal analytics.

**Comment by diminishedprime** [comment]
I'm glad you were able to solve it. Can you clarify what you were seeing before then? Did you get an error or did it just not have any accounts visible? Ideally, I'd like to add some clarification so future users don't run into this issue.

**Comment by glennanj1** [comment]
So it actually turns out it was a session issue. If you have 3rd party cookies disabled you can't access the account explorer. So when following the api tutorial for gav4 they 1. Don't mention that you need a universal analytics account to have a view (for step 3) and 2. That you need to have cookies enabled before proceeding with the account explorer link. I could replicate this issue following my steps from the root of this thread. All you have to do is block cookies then go into the account explorer home page from the link in the tutorial (step 2) then try to access your account info and it throws an error about not knowing if your logged in.

**Comment by diminishedprime** [comment]
Thanks for the thorough follow-up. I'll look into the 3rd party cookie dependency and see if there's a clean way to either

1. Inform the user 3rd party cookies are required in order to use this tool
2. Remove the dependency on 3rd party cookies (requires a refactor to use server-based oauth2)
