### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module after using old files

### ISSUE THREAD

**Issue by clubcodetown** [googleanalytics/ga-dev-tools#677]
https://github.com/googleanalytics/ga-dev-tools/issues/661
Thanks, @diminishedprime for your quick response

https://github.com/googleanalytics/ga-dev-tools/tree/4fdf63087ae52a0e17a72274e06a2b9e841af4f2

I downloaded the file before this version and put it on my server to check it but it seems not working
It gives me errors like this
"Uncaught SyntaxError: Cannot use import statement outside a module"

![Screenshot from 2021-08-12 18-58-37](https://user-images.githubusercontent.com/88352220/129207457-8268f5b9-f68b-4516-ae43-0642af09c6e8.png)

this error is in view-selector2.js file

**Comment by diminishedprime** [comment]
Sorry, I can't offer support for the old version of this code, especially for 3rd-party use.
