### ISSUE TITLE
Default view

### ISSUE THREAD

**Issue by Dukeofdork** [googleanalytics/ga-dev-tools#68]
Hi,
I have been trying these examples here https://ga-dev-tools.appspot.com/embed-api/third-party-visualizations/

But I have a problem, after some time the default view 'All Web Site Data' doesn't render any graphs, I must manually choose a different view from the drop down.
And when I do that, the graphs are drawn.

And it doesn't matter if I go to the demo site and authenticate, the components are still empty and I must select a different view.

Two questions.
* Does anyone know why the default view is empty sometimes?
* Is there a way in the code to select a different view as default/start view?

Br
/Isak

**Comment by philipwalton** [comment]
The default view is just whatever view is alphabetically first in your list of accounts, properties, and views. Are your "All Web Site Data" view has data?

**Comment by philipwalton** [comment]
I'm going to close this due to inactivity. Feel free to reopen if you're still having an issue.
