### ISSUE TITLE
Unable to load active-users.js, view-selector2.js and date-range-selector.js

### ISSUE THREAD

**Issue by mayuri-deopujari-amla** [googleanalytics/ga-dev-tools#682]
We are using embed API third-party visualizations for showing the Google Analytics dashboard on our website. But from around 15 days it has stopped working since the required scripts active-users.js, view-selector2.js and date-range-selector.js are not loading on the site, and hence the gapi.analytics.ext comes undefined. Due to this, the reports and view selection drop-down do not appear on the website. We are using the following script paths for loading the above scripts on the website:

<script src="https://ga-dev-tools.appspot.com//public/javascript/embed-api/components/view-selector2.js"></script>
<script src="https://ga-dev-tools.appspot.com//public/javascript/embed-api/components/date-range-selector.js"></script>
<script src="https://ga-dev-tools.appspot.com//public/javascript/embed-api/components/active-users.js"></script>

But now on browsing the above paths, it is redirecting to the https://ga-dev-tools.web.app/ URL. 

Please let us know the paths for the above-mentioned scripts so that we can use the above scripts on page load. 

Thank You

**Comment by diminishedprime** [comment]
You shouldn't rely on another public website's assets directly for your website. These files are all from an old version of the site that's no longer supported. If you need these files you can go to a previous commit where they existed and copy them to your site directly.
