### ISSUE TITLE
Not showing Realtime Data

### ISSUE THREAD

**Issue by nithushan** [googleanalytics/ga-dev-tools#683]
Hello Friends

I tried to use ga-dev-tools.web.app but sometime time i cant unable to get accurate campaign session,ctr,revenue, etc,,, there is any solution?

**Comment by diminishedprime** [comment]
Please recreate this bug, but use [this template](https://github.com/googleanalytics/ga-dev-tools/issues/new?assignees=&labels=&template=bug_report.md&title=)
