### ISSUE TITLE
White page after pasting Cyrillic text in item_name field

### ISSUE THREAD

**Issue by clockdev** [googleanalytics/ga-dev-tools#684]
**Describe the bug**
White page after pasting Cyrillic text in item_name field.

**To Reproduce**
1. Go to https://ga-dev-tools.web.app/ga4/event-builder/
2. Click on GA4 switcher
3. Scroll down to Items, item_name field
4. Enter Cyrillic text, for example: 'привет'
5. See a white page and an error in the console: Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

**Comment by diminishedprime** [comment]
Thanks for the clear issue. I didn't realize that btoa only supports Latin1 characters. Will look into an alternative implementation for creating URLs.
