### ISSUE TITLE
Sort Order Not Populating via Link

### ISSUE THREAD

**Issue by DT-Gary** [googleanalytics/ga-dev-tools#686]
![Untitled](https://user-images.githubusercontent.com/53053760/129600662-20de24df-13ea-4acf-8a69-46f1d088910f.png)

With the "old" system, it produced a sharable link (plus the API request link) that you were able to keep or share with other users. When the link was clicked, it would populate the form for you. Looks as though this feature is no longer available. The endpoint was: https://ga-dev-tools.appspot.com/query-explorer/?<and a whole bunch of query parameters>.

But in saying that, the functionality appears to work. https://ga-dev-tools.appspot.com/query-explorer/?ids=ga%3A[GA Tracking ID Here]&dimensions=ga%3Acountry%2Cga%3AsearchKeyword&metrics=ga%3AsearchUniques&start-date=yesterday&end-date=yesterday&start-index=1&max-results=10000

It would be nice if the frontend produced the "sharable link" again. The only expection that I found that doesn't populate the query form correctly is with the "sort" field. The query parameter does not populate that field. I suspect - if I recall correctly, is that it is now a dropdown list box vs a text field.

Thank-you.

**Comment by diminishedprime** [comment]
The following sharable link populates the sort field correctly:

https://ga-dev-tools.web.app/query-explorer/?a=41425441&b=UA-41425441-2&c=80866326&ids=ga%3A80866326&start-date=7daysAgo&end-date=yesterday&metrics=ga%3Ausers&dimensions=ga%3AuserType&sort=ga%3AuserType%40%40%40ASCENDING&d=0&include-empty-rows=1

Can you share a link that doesn't populate the sort correctly? 

** Note: you can simply remove the a, b, c & ids parameter if you're worried about sharing your analytics IDs **

**Comment by DT-Gary** [comment]
https://ga-dev-tools.appspot.com/query-explorer/?ids=ga%3A[GAID]&start-date=yesterday&end-date=yesterday&metrics=ga%3AsearchUniques&dimensions=ga%3Acountry%2Cga%3AsearchKeyword&sort=-ga%3AsearchUniques&filters=ga%3Aregion!%3D(not%20set)%3Bga%3Adimension2%3D%3DStraight&samplingLevel=HIGHER_PRECISION&start-index=00001&max-results=10000<https://ga-dev-tools.appspot.com/query-explorer/?ids=ga%3A%5bGAID%5d&start-date=yesterday&end-date=yesterday&metrics=ga%3AsearchUniques&dimensions=ga%3Acountry%2Cga%3AsearchKeyword&sort=-ga%3AsearchUniques&filters=ga%3Aregion!%3D(not%20set)%3Bga%3Adimension2%3D%3DStraight&samplingLevel=HIGHER_PRECISION&start-index=00001&max-results=10000>

Above is an example where the sort does not work. It’s field -ga:searchUniques.

I clicked on your link and your sort did populate (not sure why mine isn’t atm). However, see image below and there are fields being populated with a prior query. See the items circled in red … they are not part of the parameters in the query that you shared with me.

BTW – I was going to mention that the field ga:contentGroup(index) wasn’t working but appears it was fixed. The bug was only allowing you to select ga:contentGroupXX vs. (example) ga:contentGroup1 etc. Thanks. Glad that’s fixed.

***@***.***

Thanks for your help. Really appreciate it.

Gary.

**Comment by diminishedprime** [comment]
Ah, I see what the issue is.  Just push a quick fix and am deploying now. You should see the fix live in ~10 minutes. Let me know if you're still facing this issue after then.

**Comment by DT-Gary** [comment]
Confirmed. Working. Thank-you.
