### ISSUE TITLE
dimensions/metrics explorer not populating.

### ISSUE THREAD

**Issue by SheldonGrant** [googleanalytics/ga-dev-tools#691]
If related to my network, i've now tried it on two different networks.

Any help to clarify why the items don't load up would be awesome.
![image](https://user-images.githubusercontent.com/28047198/130196400-1bd1a9e4-1412-4037-8aae-a16af2184d97.png)

**Comment by diminishedprime** [comment]
I just deployed some changes that should give you additional information if any errors are being thrown. Can you try again and let me know if you see anything?

**Comment by diminishedprime** [comment]
Closing for now. Let me know if you're still facing this issue and we can reopen.
