### ISSUE TITLE
url shortener is not worrking

### ISSUE THREAD

**Issue by LauraChurchill** [googleanalytics/ga-dev-tools#692]
**Describe the bug**
Campaign URL Builder - Share the generated campaign URL - shorten URL is not working.

**To Reproduce**
1. Go to https://ga-dev-tools.web.app/campaign-url-builder/
2. Complete necessary fields
3. Scroll down to Share the generated campaign URL
4. Click shorten URL
5. See error

**Expected behavior**
A shortened URL should appear 

**Screenshots**

![error_GA](https://user-images.githubusercontent.com/45971881/130464978-276aab24-4894-49d9-9acb-0870fe9a0de5.JPG)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version Version 92.0.4515.131

**Comment by diminishedprime** [comment]
I recently updated the tools to have improved error messaging. Please try again. Feel free to reopen if the new error message doesn't help you fix your problem.
