### ISSUE TITLE
apple store tracker link

### ISSUE THREAD

**Issue by hasanrafian** [googleanalytics/ga-dev-tools#693]
we have a problem with making a tracker link for downloading our app from the apple store.
[https://ga-dev-tools.web.app/campaign-url-builder/ios/](url)

can't type in the application ID !!

**Comment by diminishedprime** [comment]
Please recreate this bug, but use [this template](https://github.com/googleanalytics/ga-dev-tools/issues/new?assignees=&labels=&template=bug_report.md&title=)
