### ISSUE TITLE
Shorten URL Issue

### ISSUE THREAD

**Issue by a-murray21** [googleanalytics/ga-dev-tools#694]
**Describe the bug**
Campaign URL Builder - Share the generated campaign URL - shorten URL is not working.

**To Reproduce**
Go to https://ga-dev-tools.web.app/campaign-url-builder/
Complete necessary fields
Scroll down to Share the generated campaign URL
Click shorten URL
See error below 

Expected behavior
A shortened URL should appear
![image](https://user-images.githubusercontent.com/89453288/130597005-e30328ec-ecd4-496a-91e6-9cc521fb1cbb.png)

Search Engine Used:
Google Chrome

**Comment by diminishedprime** [comment]
I recently updated the tools to have improved error messaging. Please try again. Feel free to reopen if the new error message doesn't help you fix your problem.

**Comment by a-murray21** [comment]
A new error seems to have occured with this fix. Before entering anything in the below error message appears. I copied a valid website URL and the message still appeared.

![image](https://user-images.githubusercontent.com/89453288/130673409-5c9b2618-5855-4512-a839-0f8f063728ed.png)

**Comment by diminishedprime** [comment]
Ah, I think I see what your problem is. You need to include http:// or https:// in your url.
