### ISSUE TITLE
Missing Metrics, when using the direct link to report feature

### ISSUE THREAD

**Issue by kowalskyd** [googleanalytics/ga-dev-tools#70]
I am using the direct link to the report possibility for a couple of years now and have built different reporting environments which make use of this feature. I generally love the query explorer, good job! This month I noticed that certain metrics were empty in some reports. Specfically goal conversion numbers.

Example: 
 
http://ga-dev-tools.appspot.com/explorer/?dimensions=ga%253Asource%252Cga%253Amedium%252Cga%253AdeviceCategory%252Cga%253Acountry%252Cga%253Aregion%252Cga%253Ayear%252Cga%253Amonth&metrics=ga%253Ausers%252Cga%253Asessions%252Cga%253Abounces%252Cga%253AsessionDuration%252Cga%253Atransactions%252Cga%253AtransactionRevenue%252Cga%253Agoal2Completions%252Cga%253Agoal3Completions&start-date=2014-08-01&end-date=2014-10-31&max-results=10000

Here the metrics:  goal2Completions and goal3Completions will be ignored and not be considered in the query explorer. Any hope for a fix on this?

**Comment by kowalskyd** [comment]
I found a workaround and probably the cause: The query does not contain account information or ids. The goals are custom goals and not available in the standard account set ( I manage a huge list of accounts ). If I set the id the goals will be considered again.

**Comment by philipwalton** [comment]
Yes, per-property and per-view dimensions and metrics is a new feature of the Query Explorer. It helps reduce developer errors when construction queries.

I can see how this would be less than ideal for your existing workflow, but hopefully it's just a one-time update to add an `ids` params to your saved query links.


I'm sorry this is affecting your workflow, but the intention of this feature was
