### ISSUE TITLE
Querying in Firebase - not possible to query custom dimensions 

### ISSUE THREAD

**Issue by Dominikaweglowska** [googleanalytics/ga-dev-tools#706]
**Describe the bug**
On the week of the 16th of August, we could query the custom dimensions from Firebase app in the query explorer. As from the 23th of August, those dimensions disappeared from the Query Explorer. Sometimes it appears again for 5 minutes but when trying to query, they disappear again.

**To Reproduce**
1. Go to Query explorer (https://ga-dev-tools.web.app/ga4/query-explorer/)
2. Select the firebase app we are trying to query
3. Try to select a custom dimensions from the "Dimensions" field
4. See error (none are appearing)

**Expected behavior**
We expect to see in the Query Explorer the following custom events:
![image](https://user-images.githubusercontent.com/89577385/131481880-7bc99a0e-2576-4792-82d0-c628206fa4d4.png)

This is what we could see up to the 16th August in Query explorer:
![image](https://user-images.githubusercontent.com/89577385/131482134-2cff3e14-8081-4fc8-988d-57451b3a656a.png)

This is what we see as of the 23th August:
![image](https://user-images.githubusercontent.com/89577385/131482576-f6ead9c7-0791-495d-a14e-6b9744c168ca.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome + Microsoft edge
 - Version 92.0.4515.159 (Official Build) (64-bit)

**Comment by diminishedprime** [comment]
I think this issue should be fixed now. Can you let me know if you're still facing this issue?

**Comment by Dominikaweglowska** [comment]
It works just fine again.
Many thanks !
