### ISSUE TITLE
Missing dimensions in Query Explorer

### ISSUE THREAD

**Issue by Dominikaweglowska** [googleanalytics/ga-dev-tools#719]
**What page is this happening on**
https://ga-dev-tools.web.app/ga4/query-explorer/  

**Describe the bug**
A dimension (returningUsers) is available in GA explorer but not in the Query Explorer

**To Reproduce**
1. Go to https://ga-dev-tools.web.app/ga4/query-explorer/  
2. Click on Metrics
3. Scroll down to find 'returningUsers'
4. See error > Dimension absent

![image](https://user-images.githubusercontent.com/89577385/132357943-960e11d4-c066-4bbf-ad8c-ee404e6921f3.png)
![image](https://user-images.githubusercontent.com/89577385/132358076-7b012e9f-0269-406c-85e8-ff2a0ddf83d8.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser chrome
 - Version 93.0.4577.63 (Official Build) (64-bit)

**Comment by diminishedprime** [comment]
This is expected behavior. That dimension is not available in the API at this point in time.
