### ISSUE TITLE
UA Dimensions & Metrics Explorer not loading

### ISSUE THREAD

**Issue by Bzlbzlbzl** [googleanalytics/ga-dev-tools#720]
The UA Dimensions & Metrics Explorer is stuck on loading. 
![image](https://user-images.githubusercontent.com/54183435/132755219-4f379b8d-2f01-4c75-9aad-c036b46c2bf1.png)

**Comment by diminishedprime** [comment]
Please recreate this bug, but use [this template](https://github.com/googleanalytics/ga-dev-tools/issues/new?assignees=&labels=&template=bug_report.md&title=)
