### ISSUE TITLE
Unable to load https://ga-dev-tools.web.app/ from my IP address

### ISSUE THREAD

**Issue by komz77** [googleanalytics/ga-dev-tools#726]
**What page is this happening on**
https://ga-dev-tools.web.app/

**Describe the bug**
I cannot open that site from my IP address (49.207.217.116) overnight. I have no idea what happened. The site loads over mobile data and using a VPN. I have tried multiple operating systems and browsers. The issue is not on my end. For some reason it looks like my IP is blocked but that makes no sense because I only use it for work related stuff to make tracking urls for our social posts? I just get the basic error "This site can't be reached". Please help. This is a pain and I have no idea why this has happened.

**Comment by diminishedprime** [comment]
I'm not sure why your IP would suddenly not be able to access the site. The first things that come to mind is your DNS resolver not being able to find the site's IP, or some sort of automatic system detecting issues with your IP. Either way, there's nothing I can do on my end, sorry.
