### ISSUE TITLE
Hit builder not validating on FF

### ISSUE THREAD

**Issue by kappaluppa** [googleanalytics/ga-dev-tools#729]
Using Firefox 92.0 on Mac Hit builder would not validate. It worked in Chrome.
There is nothing on the hit builder page that says Chrome must be used.

**Comment by diminishedprime** [comment]
Please recreate this bug, but use [this template](https://github.com/googleanalytics/ga-dev-tools/issues/new?assignees=&labels=&template=bug_report.md&title=)
