### ISSUE TITLE
Google Analytics- Bug Report

### ISSUE THREAD

**Issue by AshuMoh** [googleanalytics/ga-dev-tools#737]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by diminishedprime** [comment]
I can't help on this bug without reproduction steps. Please file again and fill out the template.
