### ISSUE TITLE
I can use my bitly account to authenticating Campaign URL Builder

### ISSUE THREAD

**Issue by Tsenlyn** [googleanalytics/ga-dev-tools#742]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by diminishedprime** [comment]
I can't help on this bug without reproduction steps. Please file again and fill out the template.
