### ISSUE TITLE
can't get a short link, can't get past the authorization

### ISSUE THREAD

**Issue by Vickybrown67** [googleanalytics/ga-dev-tools#746]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by diminishedprime** [comment]
I can't help on this bug without reproduction steps. Please file again and fill out the template.
