### ISSUE TITLE
Can't  receive the shorten URL

### ISSUE THREAD

**Issue by ivylinla** [googleanalytics/ga-dev-tools#748]
**What page is this happening on**
 https://www.roots.com.tw/ProductList/Detail/15835

**Describe the bug**
After insert the information and can not receive the shorten URL. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![image](https://user-images.githubusercontent.com/93651397/140047133-7f4403c9-b573-40f8-b65d-0279d43ffe70.png)

**Comment by diminishedprime** [comment]
I can't help on this bug without reproduction steps. Please file again and fill out the template.
