### ISSUE TITLE
how to query number of outbound clicks using query explorer?

### ISSUE THREAD

**Issue by sivajik34** [googleanalytics/ga-dev-tools#76]
I'm using laravel & integrated Google Analytics with following package https://github.com/spatie/laravel-analytics.
My site contain different websites links(different merchant products).I want to track every merchant outbound links.

can you give some information?

**Comment by philipwalton** [comment]
Hey @sivajik34, we're trying to reserve Github issue for this repo to bugs related to the demos and tools hosted on the site. For general reporting questions you can ask in the [reporting APIs forum](https://groups.google.com/forum/?fromgroups#!forum/google-analytics-data-export-api).

If you're ever unsure where to ask to get your Google Analytics questions answered, our [getting help](https://developers.google.com/analytics/help/) page should be able to point you in the right direction.
