### ISSUE TITLE
campaign-url-builder Error400

### ISSUE THREAD

**Issue by chantingct** [googleanalytics/ga-dev-tools#768]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 
https://ga-dev-tools.web.app/campaign-url-builder/

**Describe the bug**

**To Reproduce**
1. Go to '[...](https://ga-dev-tools.web.app/campaign-url-builder/)'
2. Click on 'shorten link'
4. See error 400

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/92226300/145142844-a351dfba-9298-4335-a23b-999c02fdf054.png)

**Comment by diminishedprime** [comment]
It's hard to be sure on what exactly went wrong since I can't see the logs or details from that error.

Could you past in your console output when you see this issue?
