### ISSUE TITLE
Issue With the Google Analytics Dev Tools Hit Builder

### ISSUE THREAD

**Issue by WebFX-dev** [googleanalytics/ga-dev-tools#769]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 
https://ga-dev-tools.web.app/hit-builder/

**Describe the bug**
I'm looking to send a hit to Google Analytics to remove the revenue data for transactions that have been refunded. However, when I go to validate and submit the hit, the hit won't validate. It keeps loading and saying "Validating hit" indefinitely. 

**Expected behavior**
I expect the hit to validate so we can then send the hit to Google Analytics

**Screenshots**
https://prnt.sc/22h8e9f

**Comment by 1951FDG** [comment]
Same issue here, it's says: Validating hit... indefinitely.

**Comment by WebFX-dev** [comment]
Your WebFX Support Request has been Received!

googleanalytics/ga-dev-tools,

Thank you for submitting your website request! This email is to confirm that your request has been received and added to our ticket queue. One of the WebFX Support team members will begin working on the ticket as soon as possible, and respond to you when complete.

You can check the status of or reply to the ticket at the following link: http://helpdesk.webpagefx.com/index.php?_m=tickets&_a=viewticket&ticketid=193613

    Using the following login:
    E-mail: ***@***.***
    Password: b7a61d3d


***If your website is down, and it is currently outside of our business hours of 8AM-5PM EST Monday through Friday, please call 717-609-0360 and select option #2.***

Thank you!
- WebFX Support Team
