### ISSUE TITLE
polymer elements demo for google analytics is down

### ISSUE THREAD

**Issue by OrenBochman** [googleanalytics/ga-dev-tools#77]
when clicking launch demo at: https://ga-dev-tools.appspot.com/polymer-elements/

I get a 404 page 

http://googlewebcomponents.github.io/google-analytics/components/google-analytics/demo.html is down

**Comment by philipwalton** [comment]
Thanks. Fixed via 7319010535f2b98dbf51d927698db049147732c0.

**Comment by philipwalton** [comment]
Though it looks like there are still some issues with the demo on the Google Web Components site. I'll look into getting those fixed as well, but at least now the link is correct.
