### ISSUE TITLE
UTM error

### ISSUE THREAD

**Issue by daniilkopiev** [googleanalytics/ga-dev-tools#778]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 
https://ga-dev-tools.web.app/campaign-url-builder/
**Describe the bug**
Every UTM I did today don't work, it gives me and my colleagues error in the format or in the data server
**To Reproduce**
1. Go to 'URL Builder'
2. Make the 'UTM'
3. Insert in 'Search Bar'

**Expected behavior**

**Screenshots**
![Schermata 2021-12-15 alle 16 14 19](https://user-images.githubusercontent.com/96192132/146212764-49a37a59-1c2e-4a99-b716-373b3d915119.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by diminishedprime** [comment]
This seems to be an issue with the site you created a campaign link to, not the campaign-url-builder itself.
