### ISSUE TITLE
Demo url for google analytics practice

### ISSUE THREAD

**Issue by matmanmo** [googleanalytics/ga-dev-tools#81]
Hi,

I am going through the online tutorials and have no website to use for the exercises.  I created a blog but it is not very useful.  Does anyone have a suggestion?

Thanks

**Comment by philipwalton** [comment]
Sorry, no, there's not currently any test account that is open to public usage.

Out of curiosity, why are you interesting in these demos and tools if you do not have a Google Analytics account? If you're doing client work, perhaps your client can give you access to their account?

**Comment by matmanmo** [comment]
Hi Philip,

Thank you for responding.  I do have a google analytics account but I don't
have access to real data.  I suspected that having to add the tracking code
to the html would prevent me from doing this, but I was wondering if there
were any options.  Does that sound correct?

Thanks,
Matt

**Comment by philipwalton** [comment]
No, unfortunately there are no test accounts you can just view data for. If you have friends or coworkers with accounts, I'd suggest asking them if you can have read-only access. Otherwise you'll have to add the tracking code to your site and see what data you get.
