### ISSUE TITLE
npm run watch does not automatically rebuilds source files

### ISSUE THREAD

**Issue by arunk-s** [googleanalytics/ga-dev-tools#85]

**Comment by philipwalton** [comment]
The `build` command is not intended to watch files, just to build them for production. The reason is `build` runs in production mode, so the source files are minified and obfuscated and therefore harder to debug.

`npm run watch` rebuilds files for me, what specifically isn't working for you?

**Comment by arunk-s** [comment]
I'm working on an ubuntu system and I tried `npm run watch` but however in my case npm doesn't rebuild the files automatically until I added `watch` as a task in `gulpfile.babel.js`.

**Comment by philipwalton** [comment]
`npm run watch` doesn't run the build tasks at all, so adding `watch` as a dependency of `build:all` will not affect the result of running `npm run watch`.

If that's happen on your system, you must have changed the gulpfile or package.json or something.

**Comment by arunk-s** [comment]
I have changed the package.json previously. I also checked without changing the package.json and `npm run watch` works. Why changing package.json changes the behaviour of `npm run watch` ?

**Comment by philipwalton** [comment]
`package.json` defines the various `npm run` commands, so changing it changes what it does.
