### ISSUE TITLE
Creating Custom Metrics and Dimensions

### ISSUE THREAD

**Issue by a-n-dcruz** [googleanalytics/ga-dev-tools#87]
Hi,

I'm new to using Google Analytics API. I would like to ask if it's possible for you to upload an actual demo on how to create custom metrics and dimension? I've tried following the documentation but I find it really difficult and I always get a reference error saying 'ga' is undefined.

thanks.

**Comment by philipwalton** [comment]
What documentation were you looking at? Can you provide a link?

**Comment by angeliadelacruz** [comment]
I've tried the following this: https://support.google.com/analytics/answer/2709828?hl=en

**Comment by philipwalton** [comment]
If you're getting an error that "`ga` is not defined", then you're probably not loading the tracking snippet. This repo actually does use custom dimensions in some of the tools, so you can refer to those implementations for an example.

- https://github.com/googleanalytics/ga-dev-tools/blob/master/src/javascript/query-explorer/index.js#L297
- https://github.com/googleanalytics/ga-dev-tools/blob/master/src/javascript/query-explorer/index.js#L555
