### ISSUE TITLE
GA Sheets Add-On is not functioning/not appearing in Google Marketplace. 

### ISSUE THREAD

**Issue by benclaflin** [googleanalytics/ga-dev-tools#874]
**What page is this happening on**
docs.google.com
https://ga-dev-tools.web.app/spreadsheet-add-on/

**Describe the bug**
The GA sheets add-on was removed from Sheets this morning. All reporting using this add-on is no longer possible. The add-on is also no longer visible on the Google Workplace Marketplace, and the links on https://ga-dev-tools.web.app/spreadsheet-add-on/ are giving Error 400 code: "The server cannot process the request because it is malformed. It should not be retried. That’s all we know." 

**To Reproduce**
1. Go to (https://ga-dev-tools.web.app/spreadsheet-add-on/)
Add-on is not available.

1. Open google sheets, select Add-ons
2. Google Analytics is not available.

**Desktop (please complete the following information):**
 - OS: Windows 10 & 11
 - Chrome
 - Version 100.0.4896.127

**Comment by ikuleshov** [comment]
Thank you for reporting this. The add-on listing has been restored.

**Comment by benclaflin** [comment]
thank you!
