### ISSUE TITLE
Variable name disagreement in Embed API Component Reference

### ISSUE THREAD

**Issue by albedoa** [googleanalytics/ga-dev-tools#88]
Hello, I don't know where else to report this. Within the Embed API Component Reference, there is variable name disagreement in the [Data component example](https://developers.google.com/analytics/devguides/reporting/embed/v1/component-reference#data-example):

```
var data = new gapi.analytics.report.Data({
  query: {
    ids: 'ga:XXXX',
    metrics: 'ga:sessions',
    dimensions: 'ga:city'
  }
});

report.on('success', function(response) {
  console.log(response);
});

report.execute();
```

Either the var name should be `report`, or `on()` and `execute()` should be called on `data`.

**Comment by philipwalton** [comment]
Thanks for reporting! I've updated the documentation.
