### ISSUE TITLE
Mk

### ISSUE THREAD

**Issue by Falslyaqused** [googleanalytics/ga-dev-tools#891]

**Comment by Giahieu1501** [comment]
> _Không có mô tả được cung cấp._

**Comment by Giahieu1501** [comment]
G6TYF5ZBKPHC

**Comment by Giahieu1501** [comment]
Mô hình: iPhone XS Max 64GB Space Grey Cellular [A Mô tả: IPHONE XS MAX SPACE GRAY 64GB AT & T-U

So IMEI: 353105101892966

Só sê-ri: G6TYF5ZBKPHC

SO IME12: 353105101918019

Só MEID: 35310510189296

Ngày mua dự kiến 3 tháng 4, 2019

Tình trạng bảo hành: Hết hạn bảo hành Tuổi của thiết bị. 2 năm, 10 tháng và 14 ngày

Thiết bị được thay thế. Không

Quốc gia Hoa Kỳ

Shi-Lock Đã mở khoá
