### ISSUE TITLE
Server-side Authorization Tutorial Returning AccessTokenRefreshError

### ISSUE THREAD

**Issue by mschmo** [googleanalytics/ga-dev-tools#90]
I followed the directions here: https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/

I can see that `_credentials` was generated properly from my JSON file that I generated with my service account. I've enabled the analytics API. And I've added the Project's email on my analytics console to have Read & Analyze permissions.

Is something missing from the tutorial that would generate `AccessTokenRefreshError: invalid_grant` when calling `get_access_token()`?

**Comment by philipwalton** [comment]
I don't think so. When are you receiving this error? Is it immediately or after more than an hour of using your app?

Looking at the Google API Client Library for Python source code I see the following comment at the point where the `AccessTokenRefreshError` error is raised:

```python
# An {'error':...} response body means the token is expired or revoked,
# so we flag the credentials as such.
```

**Comment by philipwalton** [comment]
I heard from someone else with this same problem, and generating a new JSON key file worked for him. There could be a bug in the developer console. Give that a try and let me know if it works.

**Comment by laurenancona** [comment]
I have had this happen on other projects using the Core Reporting API - as @philipwalton suggests, simply generating a new key file worked for me as well.

Another known issue is if your [server's clock is out of sync with NTP](https://developers.google.com/analytics/devguides/reporting/core/v2/gdataAuthentication#invalid-grant).

**Comment by philipwalton** [comment]
I'm going to close this as I assume it's no longer a problem. Feel free to re-open if it is.

**Comment by mschmo** [comment]
Hey guys,

It was the server's clock not being in sync with NTP like @laurenancona brought up. Sorry, I completely forgot to mention that and close this issue when I fixed it.

Can't believe it was as simple as clicking a checkbox in my laptop's date & time preferences. Thanks for all your help!
