### ISSUE TITLE
Including view-selector2.js and date-range-selector.js

### ISSUE THREAD

**Issue by ahadGitHub** [googleanalytics/ga-dev-tools#92]
Howdy,
I am building a dashboard and I need the client to choose the date range form a date range selector interface. But, I couldn't be sure how to include the view-selector2.js and date-range-selector.js. Every method I tried is firing an error.

Thanks.

**Comment by philipwalton** [comment]
There are many ways to include them:

The built and minified versions of those components are located in the [`build/javascript/embed-api/components`](https://github.com/googleanalytics/ga-dev-tools/tree/master/build/javascript/embed-api/components) directory. You can simply download those files and add them as script tags on your page, or include them in your site's main, bundled script.

If you're using an [AMD](https://en.wikipedia.org/wiki/Asynchronous_module_definition) script loader like [RequireJS](http://requirejs.org/), you can also just point to those built files as they're wrapped in a [UMD](https://github.com/umdjs/umd) wrapper.

If you're using a tool like [browserify](http://browserify.org/) or [webpack](http://webpack.github.io/), you can `npm install` this repo and `require` the files in the [`src/javascript/embed-api/components`](https://github.com/googleanalytics/ga-dev-tools/tree/master/src/javascript/embed-api/components) directory.

**Comment by ahadGitHub** [comment]
Thanks Philip, for the quick response.
I have already tried first method you proposed and am not getting any result, when I debug I get this error.
Uncaught ReferenceError: gapi is not definedgapi.client.request.path @ view-selector2.js:1e @ view-selector2.js:1t.__esModule.default @ view-selector2.js:1(anonymous function) @ view-selector2.js:1
date-range-selector.js:1Uncaught ReferenceError: gapi is not defined(anonymous function) @ date-range-selector.js:1e @ date-range-selector.js:1(anonymous function) @ date-range-selector.js:1(anonymous function) @ date-range-selector.js:1
angular.min.js:6 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=wguApp&p1=Error%3A…v.wgu.edu%2Fsites%2Fotr%2Fjobaids%2FPages%2Fjs%2Fangular.min.js%3A17%3A381)(anonymous function) @ angular.min.js:6(anonymous function) @ angular.min.js:35r @ angular.min.js:7g @ angular.min.js:34ab @ angular.min.js:38d @ angular.min.js:17uc @ angular.min.js:18Jd @ angular.min.js:17(anonymous function) @ angular.min.js:250b.Callbacks.c @ jquery-1.9.1.min.js:22b.Callbacks.p.fireWith @ jquery-1.9.1.min.js:22b.extend.ready @ jquery-1.9.1.min.js:22H @ jquery-1.9.1.min.js:22
Site-Analytics-Report.aspx:672 Uncaught TypeError: Cannot read property 'ViewSelector2' of undefined(anonymous function) @ Site-Analytics-Report.aspx:672yv @ cb=gapi.loaded_0:481(anonymous function) @ cb=gapi.loaded_0:482h @ cb=gapi.loaded_1:137(anonymous function) @ cb=gapi.loaded_1:123(anonymous function) @ cb=gapi.loaded_1:10_.T.E.__cb @ cb=gapi.loaded_0:60g @ cb=gapi.loaded_0:54c @ cb=gapi.loaded_0:45

Regards.
     Ahadu.

**Comment by ahadGitHub** [comment]
Now, after I made some twick in the way I use the script, I got this error ..
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=wguApp&p1=Error%3A…v.wgu.edu%2Fsites%2Fotr%2Fjobaids%2FPages%2Fjs%2Fangular.min.js%3A17%3A381)
Site-Analytics-Report.aspx:655 Uncaught TypeError: Cannot read property 'ViewSelector2' of undefined

**Comment by Wapples** [comment]
I'm getting a different issue. After including the 3 files necessary for the demo I see the account selector, but I do not see any of the tables. I do see errors in my console such as, 
"Uncaught SecurityError: Blocked a frame with origin "https://accounts.google.com" from accessing a frame with origin "http:/enter.url.here".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match."
