### ISSUE TITLE
How can I view the source code? The relevant source map does not work properly?

### ISSUE THREAD

**Issue by demusWiesbaden** [googleanalytics/ga-dev-tools#95]
Hi, this is the first time I tried to use source maps.

    <script src="//ga-dev-tools.appspot.com/public/javascript/embed-api/components/date-range-selector.js">

OR

    <script src="javascript/date-range-selector.js"></script>

OR

    <script src="date-range-selector.js"></script>

only shows as minified ({ } - or beautified) without the human readable identifier names.

It looks like this:

    !function(t){function e(r){if(i[r])return i[r].exports;var s=i[r]={exports:{},id:r [...]
    //# sourceMappingURL=view-selector2.js.map

---
I use Google Chrome and the box at "Enable JavaScript source maps" is checked. 
I always copied  "date-range-selector.js.map" to the same folder as the "date-range-selector.js".

**Comment by philipwalton** [comment]
The source maps are working just fine for me. What do you expect to happen, and what's not happening?

**Comment by demusWiesbaden** [comment]
my project: http://devuser.test.apozin.de/np/dashboard%20f%C3%BCr%20backoffice/00_Mein_Dashboard_001.html

date-range-selector: map does not seem to work properly for me:

![script-srcs_daterangeselector--map-works-apparently-not](https://cloud.githubusercontent.com/assets/12710670/9245368/c182672e-41a3-11e5-8a88-7cabeb75231e.png)

jquery map seems fine:

![script-srcs_jquery-map-works-apparently](https://cloud.githubusercontent.com/assets/12710670/9245369/c86f7f72-41a3-11e5-9f27-c707a013940f.png)

**Comment by philipwalton** [comment]
You're not referencing the minified jQuery version in your source, you're referencing the full version. So what you're looking at is not a source map representation, it's just the unminified file.

Using breakpoints and debugger statements, and stepping through the code is the main reason source maps exist. You can click on the `webpack://` section in the sources pane to see the source map versions of the files and add breakpoints wherever you like. Then refresh the page and the JS interpreter will stop and that point.

If you don't want to step through the code and you just want to see the original source, you don't need a source map for that. You can look at the files in the Github repo under [`src/javascript/embed-api/components`](https://github.com/googleanalytics/ga-dev-tools/tree/master/src/javascript/embed-api/components).
