### ISSUE TITLE
How to pull data from google analytics account using .net and display results on page?

### ISSUE THREAD

**Issue by nscherrer** [googleanalytics/ga-dev-tools#97]
My company used Google.GData.Analytics ver 1.6 for the last few years.  A couple of months ago our report feature on our site went dark.  According to various online sources google updated to a new authentication system.  I wanted to know if anyone could provide a step by step guide on how the new authentication system works and how to pull data into an object?

**Comment by philipwalton** [comment]
Sorry, but this is not really the place to ask a question like that. The issues reported here should be about the Google Analytics Demo & Tools site only.
