### ISSUE TITLE
Firefox - never get auth challenge

### ISSUE THREAD

**Issue by ccjon** [googleanalytics/ga-dev-tools#98]
Using FF 40.0
#uname -srvmvio
Linux 4.1.5-100.fc21.x86_64 #1 SMP Tue Aug 11 00:24:23 UTC 2015 x86_64 x86_64 GNU/Linux

reproduce: navigate to ga-dev-tools.appspot.com/hit-builder

page remains in a 'disabled' state with blue flashing animated across the top and never logged on or challenged for login

Other pages display 'Waiting for authorization...'

**Comment by philipwalton** [comment]
Do other pages let you log on fine? Did you notice any errors logged to the JS console? FWIW, I cannot reproduce this error on FF myself.

**Comment by ccjon** [comment]
I hadn't noticed that Privacy Badger blocked api.google.com .... I allowed and oauth worked fine..... Sorry about the noise

**Comment by philipwalton** [comment]
No worries, glad you figured it out.
