### ISSUE TITLE
no data displays in demo - any page

### ISSUE THREAD

**Issue by hosmi02** [googleanalytics/ga-dev-tools#99]
go to any demo sample - no data is displaying in graphs.

**Comment by philipwalton** [comment]
Perhaps you don't have any data in your first (alphabetically) Google Analytics view. I can't reproduce what you're seeing.

**Comment by hosmi02** [comment]
I am referring to the Google Analytic demo (on the demo page)....i am not
trying to rebuild the demo with the code provided....

is there a tip to view some data on the demo page(s)?

Should there be data in the two graph windows?

[image: Inline image 1]

**Comment by philipwalton** [comment]
@hosmi02 there are many demo pages, and the screenshot you linked to is not showing up. Please be more specific about what page you're looking at (include a URL), and if you're going to add a screenshot, try adding it through the Github interface rather than including it in your email.

**Comment by hosmi02** [comment]
https://ga-dev-tools.appspot.com/embed-api/basic-dashboard/

i just launch the first demo...

the sessions window appears with no data...

if i launch any of the demos the container appears with no data...

**Comment by philipwalton** [comment]
@hosmi02 like I said, I cannot reproduce what you're seeing. When I go to that page, I see data just fine.

Unless you provide me with more details or upload a screenshot, I can't help you figure out why you're not seeing any data. My best guess as to what's going on is still what I said above:

> Perhaps you don't have any data in your first (alphabetically) Google Analytics view.
